/** Each hint names the first operation for its particular question. */
export const completionHints:Record<string,string>={
 'ui-function-rules':'まず入力3を2倍する。その結果を自分自身に掛ける。',
 'um-function-rules':'外側の二乗を微分し、内側2t+1の変化率2も掛けてからt=1を代入する。',
 'ui-approximation':'ラジアンの角度に半径を掛ける。2×0.1を計算する。',
 'um-approximation':'近似式のxへ0.02を入れる。まず0.02を2で割る。',
 'um-vector-components':'まず3²+4²の平方根で長さを求める。全成分をその長さで割る。',
 'ui-cross-product':'力は腕に直角なのでsin90°=1。腕の長さに力を掛ける。',
 'um-cross-product':'右手系でx→y→zの順は正。順序を逆にすると符号が逆。',
 'ui-rate-equation':'位置は出発位置＋速度×時間。同じ速度でも出発位置の差が残る。',
 'ui-oscillation-equation':'一周期で位相は2π進む。2πをωで割る。',
 'um-oscillation-equation':'cos(2t)を二回微分し、3cos(2t)をxに戻す。',
 'ui-drag':'まず重力と抵抗の合力を求める。合力は速度ではなく加速度を決める。',
 'um-drag':'終端で合力mg−kv=0。mgをkで割る。',
 'ui-potential':'質量×重力加速度×上がった高さ。上がるので増加は正。',
 'ui-momentum':'右を正にして、質量2に速度+3を掛ける。',
 'ui-angular':'トルクは腕の長さと力の積。同じ力なら腕の倍率だけ変わる。',
 'um-angular':'中心まわりの円運動なので位置と速度は直角。m×r×vを計算。',
 'ui-pendulum':'低くなると重力による位置エネルギーが減る。抵抗なしならその分が運動エネルギーへ。',
 'um-pendulum':'周期は長さの平方根に比例する。√4はいくつ？',
 'ui-inertia':'各位置に質量を掛けて足し、全質量1+3で割る。',
 'um-inertia':'軸からの距離を二乗してから質量を掛ける。',
 'ui-rotation':'滑らないのでv=Rω。半径0.5に角速度4を掛ける。',
 'um-rotation':'N=Iαをαについて解く。トルクをIで割る。',
 'ui-reference-frame':'車内からの加速度＝地上での加速度−車の加速度。右が正。',
 'um-reference-frame':'慣性力は−mA。質量×座標系の加速度に負号を付ける。',
 'ui-electric-potential':'電位の変化は終点2−始点5。これに電荷2 Cを掛ける。',
 'ui-capacitance':'容量は電荷÷電圧。μは両方の単位に対応するので6÷3を計算。',
 'um-capacitance':'C=ε₀S/dの分母だけを2倍にする。',
 'ui-conduction':'平均電流は通過電荷÷かかった時間。6 Cを2 sで割る。',
 'um-conduction':'I=n|q|Svのうち変わるのはSだけ。',
 'ui-magnetic-force':'仕事率はF・v。二つの矢印が直角の内積を考える。',
 'um-magnetic-force':'垂直なのでsin90°=1。|q|×v×Bを計算する。',
 'ui-current-field':'巻数を長さで割る。0.5 mに100巻なら1 mには何巻？',
 'um-current-field':'B=μ₀I/(2πr)の分母だけを2倍にする。',
 'ui-induction':'誘導起電力は磁束の値でなく、時間あたりの変化に比例する。',
 'um-induction':'一巻きの変化率に巻数10を掛け、選んだ向きの負号を付ける。',
 'ui-circuit-time':'一周の電圧の増減は0。電池6 Vからコンデンサ2 Vを引く。',
 'um-circuit-time':'kは1000倍、μは100万分の1。単位を直してRとCを掛ける。',
 'ui-ac-waves':'1秒に50回なので、一回分の時間は1を50で割る。',
 'um-ac-maxwell':'ω=2πf。L一定ならωLの倍率はfの倍率と同じ。',
};
