import type { LevelChapter } from './schema';
import { r } from './schema';

/** 電磁気学・初級 — 矢印の地図と、道・面の小片。
 * 場を「場所ごとに矢印が決まった地図」として読み、
 * 「道に沿って小区間の仕事を足す」と「面の小タイルの束を足す」の二つだけを作る。
 * 電位は中級へ送る。∫ と ∮ は予告としてしか出さない。
 * 「本数」は数えるための比喩で、定義は場と面から決まる量だと図中に添える。 */
export const ui_em: LevelChapter = {
  id: 'ui-em',
  title: '電磁気学',
  subtitle: '矢印の地図と、道・面の小片',
  familyId: 'uem',
  level: 'intro',
  stages: [
    // ================= 1. 場を地図として読む =================
    {
      id: 'ui-field-map',
      title: '矢印の地図',
      subtitle: '場所ごとに矢印が1本決まる',
      enemy: { name: 'マップゴースト', emoji: '🧭', maxHp: 110 },
      theme: '場を、場所ごとに矢印が決まった地図として読む',
      goal: r`空間の各点に向きと大きさが決まる地図として場を読み、置いた電荷が受ける力を $\vec F=q\vec E$ から求められる。`,
      intro: '電場や磁場は目に見えない。けれど扱い方は単純で、「場所を決めれば矢印が1本決まる地図」だと思えばよい。まずはこの地図の読み方だけを固める。',
      outro: '場は場所ごとに矢印が決まった地図で、置いた電荷では変わらない。変わるのは電荷が受ける力のほうだ。この地図から取り出すのは、道に沿った足し算と、面を貫いた量の足し算の二つになる。',
      foundation: {
        known: '矢印が向きと大きさの両方を表すこと。掛け算と、正負の符号が向きを表すこと。',
        startingPoint: '「場所を決めれば矢印が1本決まる」という地図の見方から出発する。',
        conditions: '時間とともに変わらない外部の場を扱う。試す電荷で場を作る電荷配置が変わらない模型。矢印は代表点の値で、点の間にも値がある。',
        example: {
          given: '電場が 3 N/C の点に、+2 C の電荷を置く。',
          tex: r`F=qE=2\times3=6\,\mathrm{N}`,
          read: '単位も掛けると C×N/C=N。地図の矢印に電荷を掛けると、力の矢印になる。',
        },
      },
      glossary: {
        E: '各点の電場。正の1 Cが受ける力で測る [N/C = V/m]',
        q: '場に置いて調べる電荷 [C]。符号も含めて扱う',
        B: '各点の磁場（磁束密度）[T]。単位はテスラ',
        F: '電荷が受ける力 [N]。電場からの力は F = qE',
      },
      units: [
        { end: 3, goal: '場を、場所ごとに矢印が決まる地図として読む', gain: '空間の各点に矢印が1本ずつ決まっている。矢印の長さが強さ、向きが力の向きを表す。' },
        { end: 6, goal: '地図から、置いた電荷が受ける力を作る', gain: '力は電場に電荷を掛けたもの。負の電荷では向きが反転するが、地図そのものは変わらない。' },
        { end: 9, goal: '地図の上に道と面を置き、この章の目的地を見る', gain: '道に沿って足すと仕事、面を貫いた量を足すと束。どちらも小片に分けて足す形になる。' },
      ],
      slides: [
        {
          heading: '場所ごとに矢印が決まっているとは、どういうことだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'uie-map-grid',
          body: '空間のどの点にも、矢印が1本ずつ決まっている。これが「場」だ。',
        },
        {
          heading: '矢印の長さは、何の大きさを表すのだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'uie-map-strength',
          body: '矢印が長い場所ほど、電場が強い。単位 N/C は「1 C が受ける力」を表す。',
          formulaNote: '電場の単位 $\\mathrm{N/C}$ は「1 Cあたりの力」',
        },
        {
          heading: '置く電荷を変えたら、地図も描き直すのだろうか?',
          beat: '疑問',
          role: '問い',
          figure: 'uie-map-testcharge',
          body: '同じ点でも、+1 C と +2 C では受ける力が違う。地図も描き直すのだろうか。',
        },
        {
          heading: '電荷が受ける力は、地図からどう作るのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-map-force',
          body: '地図の矢印に電荷を掛ける。3 N/C の点に +2 C なら、力は 6 N。',
          formula: r`\vec F=q\vec E`,
          formulaNote: '単位は $\\mathrm{C}\\times\\mathrm{N/C}=\\mathrm{N}$',
          calculation: [
            { note: '力は、電荷と電場の積として決める', tex: r`F=qE` },
            { note: '数値を入れる', tex: r`F=2\,\mathrm{C}\times3\,\mathrm{N/C}` },
            { note: '単位も掛けると N になる', tex: r`F=6\,\mathrm{N}` },
          ],
        },
        {
          heading: '負の電荷を置くと、力の向きはどうなるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-map-negative',
          body: '−2 C なら力は逆向きで 6 N。裏返るのは力だけで、地図は変わらない。',
        },
        {
          heading: '点電荷のまわりの地図は、どんな形になるのだろう?',
          beat: '解決',
          role: '観察',
          figure: 'uie-map-point-charge',
          body: '正の点電荷なら外向きの放射状、負なら内向き。離れるほど矢印は短い。',
        },
        {
          heading: '磁場の地図は、電場の地図と何が違うのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'uie-map-magnet',
          body: '磁場にも同じ地図がある。単位は T。ただし矢印をつないだ線は実在のひもではない。',
        },
        {
          heading: '地図の上に道や面を置くと、何が読めるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-map-path-preview',
          body: '道を引けば、道に沿った後押しを足せる。面を置けば、貫いた量を数えられる。',
        },
        {
          heading: '矢印の地図から、これから何を取り出すのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'uie-map-summary',
          body: '取り出すのは、道の小片の和（仕事）と、面の小片の和（束）の二つだけだ。',
          formulaNote: '道の和が仕事、面の和が束。どちらも小片の足し算',
        },
      ],
      preview: {
        goal: r`\vec F=q(\vec E+\vec v\times\vec B)`,
        now: '場所ごとの矢印を読み、静止した電荷が電場から受ける力を出すこと',
        later: '動く電荷が磁場から受ける力、向きを外積で決めること',
      },
      leadsTo: ['ue-integrals', 'ue-lorentz'],
      problems: [
        {
          id: 'p-uiem-1',
          difficulty: 1,
          question: '電場が 4 N/C の点に、+3 C の電荷を置いた。受ける力の大きさは?',
          choices: ['12 N', '7 N', '1.33 N', '12 N/C'],
          answerIndex: 0,
          hint: '力は電場に電荷を掛ける。単位も一緒に掛けてみる。',
          explanation: r`$F=qE=3\times4=12$ で、単位は $\mathrm{C}\times\mathrm{N/C}=\mathrm{N}$ だから**12 N**。足し算では単位がそろわず、割り算では1 Nあたりの電荷になってしまう。答えの単位がNになるかを毎回確かめるとよい。`,
        },
        {
          id: 'p-uiem-2',
          difficulty: 1,
          question: '同じ点に置く電荷を +1 C から +2 C に変えた。その点の電場はどうなる?',
          choices: ['2倍になる', '半分になる', '変わらない', '0になる'],
          answerIndex: 2,
          hint: '地図の矢印は、どの量で決まっていたか。',
          explanation: '電場は場所だけで決まる地図の値で、置いた電荷では**変わらない**。2倍になるのは受ける力のほうで、$F=qE$ の $q$ が2倍になった結果。地図と、地図から作る力を混ぜないことが大切。',
        },
        {
          id: 'p-uiem-3',
          difficulty: 2,
          question: '3 N/C の電場の中に −2 C の電荷を置いた。受ける力として正しいものは?',
          choices: ['電場と同じ向きに 6 N', '電場と逆向きに 6 N', '電場と同じ向きに 1.5 N', '電場と逆向きに 1.5 N'],
          answerIndex: 1,
          hint: '大きさと向きを別々に考える。符号が表すのはどちらか。',
          explanation: '大きさは $|q|E=2\\times3=6$ で**6 N**、符号が負なので向きは電場と**逆**になる。負号は大きさを小さくするのではなく、向きを裏返す情報を運んでいる。1.5 Nは電荷で割ってしまった値。',
        },
        {
          id: 'p-uiem-4',
          difficulty: 2,
          question: '正の点電荷のまわりの電場の地図は、どのように見える?',
          choices: [
            '中心へ向かう矢印が並び、離れるほど長くなる',
            '外向きの矢印が放射状に並び、離れるほど短くなる',
            'どこでも同じ長さの矢印が、同じ向きに並ぶ',
            '矢印は中心の点にだけあり、まわりには何もない',
          ],
          answerIndex: 1,
          hint: '正の電荷は、正の試験電荷をどちらへ押すか。',
          explanation: '正の電荷は正の試験電荷を押しのけるので、矢印は**外向きの放射状**。距離が離れるほど力は弱まるので矢印は短くなる。内向きになるのは負の点電荷の場合で、どこでも同じ向きになるのは一様な電場の場合。',
        },
      ],
    },

    // ================= 2. 斜めの力を道方向へ分ける =================
    {
      id: 'ui-work-direction',
      title: '斜めの力を分ける',
      subtitle: '道方向の成分だけが効く',
      enemy: { name: 'ナナメスライサー', emoji: '📐', maxHp: 116 },
      theme: '斜めの力を、道方向の成分に分けてから仕事にする',
      goal: r`斜めに引く力の仕事を、道方向の成分 $5\,\mathrm{N}$ を取り出してから $W=5\times2=10\,\mathrm{J}$ と求められる。`,
      intro: '仕事は力×距離だった。では力が斜めを向いていたらどうするのか。矢印の長さをそのまま掛けてはいけない。ここで「道方向の成分だけを取り出す」手つきを作る。',
      outro: '斜めの力では、道方向の成分だけが仕事に効く。10 N を 60° 傾けて引くと右向きの成分は 5 N で、仕事は 5×2=10 J。中級では、この「道方向を取り出す」操作を内積として一息で書く。',
      foundation: {
        known: '一定の力なら仕事は力×距離であること。直角三角形の辺の比が読めること。',
        startingPoint: '斜めの力を、道方向の成分と道に垂直な成分の2本に分けるところから出発する。',
        conditions: 'この段では箱は右へまっすぐ 2 m 動く。力は一定で、右向きから 60° 上に傾いているとする。',
        example: {
          given: '10 N の力が、右向きから 60° 上に傾いている。',
          tex: r`F_{\parallel}=10\cos 60^\circ=5\,\mathrm{N}`,
          read: '右へ進めるのはこの 5 N。上向きの成分は、この図では床が支えていて移動を作らない。',
        },
      },
      glossary: {
        F: '斜めに引く力の大きさ [N]。この段では 10 N',
        'F∥': '力のうち、進む向きに沿った成分 [N]',
        'F⊥': '力のうち、進む向きに垂直な成分 [N]',
        W: '力がした仕事 [J]。J = N·m',
      },
      units: [
        { end: 3, goal: '矢印の長さをそのまま掛けられない場面を見る', gain: '斜めの力では、進んだ向きと力の向きが違う。10×2 では合わない。' },
        { end: 6, goal: '力を2本に分け、道方向の成分だけを取り出す', gain: '右向き成分は 10cos60°=5 N。垂直成分はこの図では移動を作らない。' },
        { end: 8, goal: '成分に距離を掛けて、仕事を確定する', gain: 'W=5×2=10 J。単位は N×m=J。掛けるのは道方向の成分だけ。' },
      ],
      slides: [
        {
          heading: '斜めに引かれた箱は、どちらへ動くのだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'uie-dir-scene',
          body: '箱を右へ 2 m 動かす。引く力は 10 N で、右向きから 60° 上に傾いている。',
        },
        {
          heading: '10 N に 2 m を掛けて、20 J としてよいのだろうか?',
          beat: '疑問',
          role: '問い',
          figure: 'uie-dir-question',
          body: '矢印の長さは 10 N。そのまま掛けると 20 J になる。だが箱が進んだのは右だけだ。',
        },
        {
          heading: '斜めの矢印を、2本に分けてみよう',
          beat: '解決',
          role: '操作',
          figure: 'uie-dir-split',
          body: '斜めの力を、右向きの矢印と上向きの矢印の合成とみなす。',
        },
        {
          heading: '右向きの成分は、いくつになるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-dir-component',
          body: r`右向きの成分は $10\cos 60^\circ=5$ N。矢印の長さのちょうど半分だ。`,
          formula: r`F_{\parallel}=10\cos 60^\circ=5\,\mathrm{N}`,
          formulaNote: '$\\cos$ は、傾いた矢印の道方向の長さを取り出す係数',
        },
        {
          heading: '上向きの成分は、右へ進めるのだろうか?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-dir-perp',
          body: '上向きの成分は右へは進めない。この図では床が支えていて、移動を作らない。',
        },
        {
          heading: '仕事には、どの数字を掛ければよいのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-dir-work',
          body: '掛けるのは右向きの 5 N と、進んだ 2 m だけだ。',
          formula: r`W=5\times2=10\,\mathrm{J}`,
          calculation: [
            { note: '道方向の成分に、進んだ距離を掛ける', tex: r`W=F_{\parallel}\,L` },
            { note: '数値を入れる', tex: r`W=5\,\mathrm{N}\times2\,\mathrm{m}` },
            { note: '仕事が確定する', tex: r`W=10\,\mathrm{J}` },
          ],
        },
        {
          heading: '単位を追うと、答えは何の量になるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-dir-units',
          body: r`$5\,\mathrm{N}\times2\,\mathrm{m}=10\,\mathrm{N\cdot m}$。この N·m に付けた別名が J。`,
          calculation: [
            { note: '数と一緒に単位も掛ける', tex: r`5\,\mathrm{N}\times2\,\mathrm{m}=10\,\mathrm{N\cdot m}` },
            { note: 'N·m に付けた別名が J', tex: r`1\,\mathrm{N\cdot m}=1\,\mathrm{J}` },
          ],
        },
        {
          heading: '斜めの力では、どの長さを掛けるのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'uie-dir-summary',
          body: '掛けるのは道方向の成分だけ。矢印の長さをそのまま掛けない。',
          formulaNote: '中級では、この取り出しを $\\vec F\\cdot\\Delta\\vec r$ と書く',
        },
      ],
      preview: {
        goal: r`W=\vec F\cdot\Delta\vec r`,
        now: '道方向の成分を取り出してから、距離を掛けること',
        later: 'この取り出しを内積として一息で書くこと',
      },
      leadsTo: ['ue-integrals'],
      problems: [
        {
          id: 'p-uiwd-1',
          difficulty: 1,
          question: '10 N の力が、進む向きから 60° 傾いている。進む向きの成分は?',
          choices: ['10 N', '5 N', '8.7 N', '0 N'],
          answerIndex: 1,
          hint: '$\\cos 60^\\circ$ は 0.5。',
          explanation: '$10\\cos 60^\\circ=10\\times0.5=5$ で**5 N**。矢印の長さ 10 N のちょうど半分になる。8.7 N は $\\sin 60^\\circ$ を使ってしまった値で、そちらは進む向きに垂直な成分。',
        },
        {
          id: 'p-uiwd-2',
          difficulty: 1,
          question: '進む向きの成分が 5 N の力で、右へ 2 m 動かした。この力がした仕事は?',
          choices: ['20 J', '10 J', '17.3 J', '5 J'],
          answerIndex: 1,
          hint: '掛けるのは成分と距離。矢印の長さではない。',
          explanation: '$W=5\\times2=10$ で**10 J**。単位も N×m=J とそろう。20 J は矢印の長さ 10 N をそのまま掛けた値で、進んでいない向きの分まで数えてしまっている。',
        },
        {
          id: 'p-uiwd-3',
          difficulty: 2,
          question: '進む向きに垂直な成分が仕事に効かないのは、なぜ?',
          choices: [
            '力が小さいから',
            'その向きには進んでいないから',
            '摩擦があるから',
            '単位がそろわないから',
          ],
          answerIndex: 1,
          hint: '仕事の定義に入っているのは「その向きに動いた距離」。',
          explanation: '仕事は「力の向きに動いた距離」で決まる。**その向きに進んでいなければ距離が 0** なので、その成分は仕事に足されない。垂直成分が別の向きの運動を作る場合もあるが、この図では床が支えていて移動を作らない。',
        },
        {
          id: 'p-uiwd-4',
          difficulty: 2,
          question: '斜めの力で、矢印の長さをそのまま距離に掛けると何が起きる?',
          choices: [
            '正しい仕事が求まる',
            '仕事を実際より大きく見積もってしまう',
            '答えは必ず 0 になる',
            '答えの単位が N になる',
          ],
          answerIndex: 1,
          hint: '成分と矢印の長さ、どちらが大きいか。',
          explanation: '道方向の成分は矢印の長さ以下なので、そのまま掛けると**大きく見積もる**ことになる。今回なら 20 J と 10 J の差が出る。単位は J のままなので、単位を見ただけでは誤りに気づけない点に注意。',
        },
        {
          id: 'p-uiwd-5',
          difficulty: 1,
          question: '同じ 10 N を、進む向きと同じ向きに引いて 2 m 動かした。仕事は?',
          choices: ['10 J', '20 J', '5 J', '0 J'],
          answerIndex: 1,
          hint: '傾きが 0° のとき、道方向の成分は矢印の長さそのもの。',
          explanation: '傾きが 0° なら $\\cos 0^\\circ=1$ で成分は 10 N のまま。$W=10\\times2=20$ で**20 J**。斜めのときに 10 J まで減っていたのは、道方向の成分が半分になっていたからだと分かる。',
        },
      ],
    },

    // ================= 3. 曲がる道の仕事 =================
    {
      id: 'ui-work-bent-path',
      title: '曲がる道の仕事',
      subtitle: '区間ごとに「前」を決める',
      enemy: { name: 'エルジクランカー', emoji: '📎', maxHp: 122 },
      theme: '曲がる道の仕事を、区間ごとの前向き成分で足す',
      goal: r`L字に曲がる道の仕事を、区間ごとの「前向き成分 × 長さ」の和として $7\,\mathrm{J}$ まで求められる。`,
      intro: '道がまっすぐなら「前」は1つだった。曲がる道では前の向きが区間ごとに変わる。そこで道を折れ線に切り、区間ごとに前を決めてから足す。',
      outro: '曲がる道の仕事は、区間ごとの「前向き成分 × 長さ」の和。今回は 3+2+2=7 J。道を逆向きにたどると、各区間の移動の向きが逆になり、仕事の符号も変わる。',
      foundation: {
        known: '力の道方向の成分だけが仕事に効くこと。成分に距離を掛けると仕事になること。',
        startingPoint: '曲がる道を、まっすぐな区間の連なりに切り分けるところから出発する。',
        conditions: 'この段ではL字の3区間を扱う。各区間で力は一定とし、その区間の前向き成分だけを読む。',
        example: {
          given: '区間1は右へ 1 m、前向き成分は 3 N。',
          tex: r`\Delta W_1=3\times1=3\,\mathrm{J}`,
          read: '単位は N×m=J。区間の中だけなら、まっすぐな道と同じ掛け算1回で済む。',
        },
      },
      glossary: {
        'Δr': '道を切った1区間の向きと長さ [m]。矢印が進む向き',
        'ΔW': '1区間でされた仕事 [J]。符号を含む',
        'F∥': 'その区間の前向きに沿った力の成分 [N]',
        C: '仕事を足し合わせる道につける印。向きも含めて指定する',
      },
      units: [
        { end: 3, goal: '曲がる道では「前」が1つに決まらないことを見る', gain: '区間ごとに進む向きが変わる。道全体で1つの前を選ぶことはできない。' },
        { end: 7, goal: '区間ごとの寄与を作って合計する', gain: '各区間は「前向き成分 × 長さ」。3 J、2 J、2 J を足して 7 J。' },
        { end: 10, goal: '向きの意味と、細かく切った場合を確かめる', gain: '道を逆にたどると符号が反転する。辺を増やすと折れ線が曲線に近づく。' },
      ],
      slides: [
        {
          heading: '道がL字に曲がると、何が変わるのだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'uie-bent-scene',
          body: '右へ 1 m、上へ 2 m、左へ 1 m と進む道を考える。進む向きが途中で2回変わる。',
        },
        {
          heading: 'どの向きを「前」とすればよいのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'uie-bent-question',
          body: '前向き成分を取りたい。しかし道全体では、前が1つに決まらない。',
        },
        {
          heading: '「前」は、区間ごとに決めればよいのだろうか?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-bent-directions',
          body: '区間の中では道はまっすぐ。前は区間1が右、区間2が上、区間3が左になる。',
        },
        {
          heading: '区間1の寄与は、いくつになるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-bent-seg1',
          body: '区間1は右へ 1 m。右向きの成分は 3 N なので、寄与は 3 J。',
          calculation: [
            { note: '前向き成分に、区間の長さを掛ける', tex: r`\Delta W_1=3\,\mathrm{N}\times1\,\mathrm{m}` },
            { note: '区間1の寄与', tex: r`\Delta W_1=3\,\mathrm{J}` },
          ],
        },
        {
          heading: '区間2の寄与は、いくつになるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-bent-seg2',
          body: '区間2は上へ 2 m。上向きの成分は 1 N なので、寄与は 2 J。',
          calculation: [
            { note: '前向きが上に変わったので、上向き成分を取る', tex: r`\Delta W_2=1\,\mathrm{N}\times2\,\mathrm{m}` },
            { note: '区間2の寄与', tex: r`\Delta W_2=2\,\mathrm{J}` },
          ],
        },
        {
          heading: '区間3の寄与は、いくつになるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-bent-seg3',
          body: '区間3は左へ 1 m。左向きの成分は 2 N なので、寄与は 2 J。',
          calculation: [
            { note: '前向きが左に変わったので、左向き成分を取る', tex: r`\Delta W_3=2\,\mathrm{N}\times1\,\mathrm{m}` },
            { note: '区間3の寄与', tex: r`\Delta W_3=2\,\mathrm{J}` },
          ],
        },
        {
          heading: '3つの寄与を合計すると、いくらになるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-bent-total',
          body: '3+2+2=7 J。区間ごとの掛け算を、順に足しただけだ。',
          formula: r`W=3+2+2=7\,\mathrm{J}`,
          calculation: [
            { note: '区間ごとの寄与を並べる', tex: r`W=\Delta W_1+\Delta W_2+\Delta W_3` },
            { note: '数値を入れる', tex: r`W=3+2+2` },
            { note: '合計する', tex: r`W=7\,\mathrm{J}` },
          ],
        },
        {
          heading: '道を逆向きにたどると、どうなるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-bent-reverse',
          body: '各区間の移動の向きが逆になるので、寄与の符号も逆。合計は −7 J になる。',
          formulaNote: '道には向きが付いている。逆にたどれば符号が変わる',
        },
        {
          heading: '辺を増やすと、道はどこへ近づくのだろう?',
          beat: '解決',
          role: '観察',
          figure: 'uie-bent-refine',
          body: '3辺を6辺、12辺と増やすと、折れ線はなめらかな曲線に近づく。足し方は同じだ。',
        },
        {
          heading: '曲がる道の仕事は、どう作ればよいのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'uie-bent-summary',
          body: '道を区間に切り、区間ごとに「前向き成分 × 長さ」を作って足す。',
          formulaNote: '上級編ではこの和を $\\int_C\\vec F\\cdot d\\vec r$ と書く。C は道の印',
        },
      ],
      preview: {
        goal: r`W=\int_C\vec F\cdot d\vec r`,
        now: '道を区間に切り、前向き成分×長さを符号つきで足すこと',
        later: '区間を限りなく細かくすること、C という向き付きの道の印を扱うこと',
      },
      leadsTo: ['ue-integrals'],
      problems: [
        {
          id: 'p-uiwb-1',
          difficulty: 1,
          question: 'L字の道の区間1は右へ 1 m で、右向きの成分は 3 N だった。この区間の寄与は?',
          choices: ['3 J', '1 J', '4 J', '0 J'],
          answerIndex: 0,
          hint: '区間の中はまっすぐ。成分に長さを掛ける。',
          explanation: '$3\\times1=3$ で**3 J**。単位も N×m=J とそろう。区間の中では道がまっすぐなので、まっすぐな道と同じ掛け算1回で済む。4 J は足し算をしてしまった値。',
        },
        {
          id: 'p-uiwb-2',
          difficulty: 1,
          question: '区間ごとの寄与が 3 J、2 J、2 J だった。この道全体の仕事は?',
          choices: ['5 J', '7 J', '12 J', '3 J'],
          answerIndex: 1,
          hint: '区間の寄与を順に足すだけ。',
          explanation: '$3+2+2=7$ で**7 J**。区間ごとの掛け算を順に足しただけで、新しい規則は使っていない。12 J は掛けてしまった値で、3 J は最初の区間だけを答えている。',
        },
        {
          id: 'p-uiwb-3',
          difficulty: 2,
          question: '曲がる道で「前」の向きを決めるとき、正しいやり方は?',
          choices: [
            '道全体で1つの向きに決める',
            '区間ごとに、その区間が進む向きに決める',
            '出発点での向きに固定する',
            '力の向きをそのまま前とする',
          ],
          answerIndex: 1,
          hint: '区間の中では道はまっすぐだった。',
          explanation: '曲がる道では前が1つに決まらないので、**区間ごとに、その区間の進む向きを前とする**。道全体で1つに決めたり出発点で固定したりすると、途中の区間で向きが合わなくなる。力の向きを前にするのは定義の取り違え。',
        },
        {
          id: 'p-uiwb-4',
          difficulty: 2,
          question: '同じ道を、同じ力のもとで逆向きにたどった。仕事はどうなる?',
          choices: ['同じ 7 J', '符号が変わって −7 J', '0 J', '2倍の 14 J'],
          answerIndex: 1,
          hint: '各区間の移動の向きが、すべて逆になる。',
          explanation: '各区間の進む向きが逆になるので、前向き成分の符号がすべて反転し、合計も**−7 J** になる。道には向きが付いていて、たどる向きを変えると仕事の符号が変わる。大きさは 7 J のままである点に注意。',
        },
        {
          id: 'p-uiwb-5',
          difficulty: 2,
          question: '折れ線の辺の数を 3、6、12 と増やしていくと何が起きる?',
          choices: [
            '合計が 0 に近づく',
            '折れ線がなめらかな曲線に近づく',
            '各区間の寄与が必ず負になる',
            '足し方の規則が変わる',
          ],
          answerIndex: 1,
          hint: '1辺は短くなるが、辺の数は増える。',
          explanation: '辺を増やすほど折れ線は**なめらかな曲線に近づく**。1辺あたりの寄与は小さくなるが辺の数が増えるので、合計が 0 になることはない。足し方は最後まで「前向き成分 × 長さ」を足すだけで変わらない。',
        },
      ],
    },

    // ================= 4. 電場の中の曲がった道 =================
    {
      id: 'ui-electric-work-path',
      title: '電場の中の曲がった道',
      subtitle: '4区間に分けて符号つきで足す',
      enemy: { name: 'カーブトレーサー', emoji: '🛤️', maxHp: 126 },
      theme: '電場の中の曲がった道の仕事を、4区間の和にする',
      goal: r`曲がった道に沿う電気力の仕事を、区間ごとの「道方向成分 × 長さ」の和として $3\,\mathrm{J}$ まで計算できる。`,
      intro: '力を電場からの力に取り替える。電荷 q が受ける力は qE なので、道方向の成分は電場の道方向成分に q を掛けたものになる。数え方はさっきと同じだ。',
      outro: '電気力の仕事は、区間ごとの「電場の道方向成分 × 電荷 × 長さ」の和。道に垂直な区間は 0、逆を向いた区間は負。今回は 3+2+0−2=3 J となった。',
      foundation: {
        known: '曲がる道を区間に切り、前向き成分 × 長さを足すこと。電荷が受ける力が qE であること。',
        startingPoint: '短い区間の中では、道は直線、電場は一定とみなせるという考えから出発する。',
        conditions: 'この段では道を4区間に切る。電荷は +1 C に固定し、各区間の道方向成分だけを読む。',
        example: {
          given: '道方向成分 3 N/C の区間を、+1 C が 1 m 進む。',
          tex: r`\Delta W_1=1\times3\times1=3\,\mathrm{J}`,
          read: '単位は C×N/C×m=J。区間の中だけなら、直線のときと同じ掛け算1回で済む。',
        },
      },
      glossary: {
        'Δr': '道を切った1区間の向きと長さ [m]。矢印は進む向き',
        'ΔW': '1区間の中でされた仕事 [J]。符号を含む',
        'E∥': '電場のうち、その区間の進む向きに沿った成分 [N/C]',
        q: 'この段では +1 C に固定した、道を運ばれる電荷 [C]',
      },
      units: [
        { end: 3, goal: '力を電場からの力に取り替える', gain: '電荷が受ける力は qE。道方向成分は電場の道方向成分に q を掛けたもの。' },
        { end: 7, goal: '4つの区間の寄与を1つずつ作る', gain: '各区間は「道方向成分 × 電荷 × 長さ」。垂直なら 0、逆向きなら負になる。' },
        { end: 9, goal: '寄与を合計し、細かく切った場合を見通す', gain: '合計は 3+2+0−2=3 J。区間を細かくすると、折れ線が本当の曲線に近づく。' },
      ],
      slides: [
        {
          heading: '電場の中では、どの力が仕事をするのだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'uie-path-recall',
          body: '+1 C が受ける力は qE。道に沿う成分が 3 N/C の直線を 1 m 進めば、寄与は 3 J。',
          formula: r`\Delta W=qE_{\parallel}\,\Delta r`,
          formulaNote: '$E_{\\parallel}$ は、進む向きに沿った電場の成分',
        },
        {
          heading: '曲がった道では、電場との角度はどうなるのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'uie-path-curve',
          body: '進む向きが場所ごとに変わるので、電場との角度も場所ごとに変わる。',
        },
        {
          heading: '曲線を、4本の直線矢印に置き換えてみよう',
          beat: '解決',
          role: '操作',
          figure: 'uie-path-split',
          body: '曲線を4つに区切り、進む向きの矢印 Δr₁〜Δr₄ を1本ずつ引く。',
        },
        {
          heading: '区間1では、電場のどの成分が効くのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-path-seg1',
          body: '電場 5 N/C が道から 53° 傾く。道方向の成分は 3 N/C、長さ 1 m で 3 J。',
          calculation: [
            { note: '道方向の成分に、電荷と区間の長さを掛ける', tex: r`\Delta W_1=qE_{\parallel 1}\,\Delta r_1` },
            { note: '数値を入れる', tex: r`\Delta W_1=1\times3\times1` },
            { note: '単位は C×N/C×m = J', tex: r`\Delta W_1=3\,\mathrm{J}` },
          ],
        },
        {
          heading: '区間2の寄与は、いくつになるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-path-seg2',
          body: '道方向の成分は 1 N/C、長さは 2 m。成分が小さくても長さで稼げる。',
          calculation: [
            { note: '成分 1 N/C に、長さ 2 m を掛ける', tex: r`\Delta W_2=1\times1\times2` },
            { note: '区間2の寄与', tex: r`\Delta W_2=2\,\mathrm{J}` },
          ],
        },
        {
          heading: '道に垂直な電場は、仕事をするのだろうか?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-path-seg3',
          body: '区間3は電場が真横を向く。道方向の成分は 0 N/C なので、寄与も 0 J。',
          calculation: [
            { note: '垂直なら、道に沿った成分は0', tex: r`E_{\parallel 3}=0\,\mathrm{N/C}` },
            { note: '長さを掛けても0のまま', tex: r`\Delta W_3=1\times0\times1=0\,\mathrm{J}` },
          ],
        },
        {
          heading: '進む向きと逆を向いた区間は、どう数えるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-path-seg4',
          body: '区間4は電場が真逆を向く。道方向の成分は −2 N/C、長さ 1 m で −2 J。',
          calculation: [
            { note: '逆向きの成分は符号を負にする', tex: r`E_{\parallel 4}=-2\,\mathrm{N/C}` },
            { note: '区間4の寄与は負', tex: r`\Delta W_4=1\times(-2)\times1=-2\,\mathrm{J}` },
          ],
        },
        {
          heading: '4つの寄与を合計すると、いくらになるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-path-total',
          body: '3、2、0、−2 を符号のまま足すと 3+2+0−2=3 J。',
          formula: r`W=3+2+0-2=3\,\mathrm{J}`,
          calculation: [
            { note: '4区間の寄与を符号のまま並べる', tex: r`W=\Delta W_1+\Delta W_2+\Delta W_3+\Delta W_4` },
            { note: '数値を入れる', tex: r`W=3+2+0-2` },
            { note: '合計する', tex: r`W=3\,\mathrm{J}` },
          ],
        },
        {
          heading: '区間を細かくすると、この和はどこへ向かうのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'uie-path-refine',
          body: '区間を増やすと折れ線が曲線に重なる。足し方は最後まで変わらない。',
          formulaNote: '上級編ではこの和を $q\\int_C\\vec E\\cdot d\\vec r$ と書く',
        },
      ],
      preview: {
        goal: r`W=q\int_C\vec E\cdot d\vec r`,
        now: '道を4区間に切り、道方向成分×長さを符号つきで足すこと',
        later: '区間を限りなく細かくすること、向きの掛け算を内積で書くこと',
      },
      leadsTo: ['ue-integrals', 'ue-potential'],
      problems: [
        {
          id: 'p-uiewp-1',
          difficulty: 1,
          question: '電場の道方向成分が 3 N/C、区間の長さが 1 m、運ぶ電荷が +1 C。この区間の寄与は?',
          choices: ['3 J', '1 J', '0 J', '−3 J'],
          answerIndex: 0,
          hint: '区間の中は直線扱い。成分に電荷と長さを掛ける。',
          explanation: '$1\\times3\\times1=3$ で**3 J**。単位も C×N/C×m=J とそろう。区間の中では道を直線、電場を一定とみなしているので、直線のときと同じ掛け算1回で済む。',
        },
        {
          id: 'p-uiewp-2',
          difficulty: 1,
          question: '電場が進む向きとちょうど垂直な区間がある。この区間の寄与は?',
          choices: ['区間の長さに比例して増える', '0 J', '電場の大きさに等しい', '必ず負になる'],
          answerIndex: 1,
          hint: '効くのは道に沿った成分だけ。垂直なとき、その成分は?',
          explanation: '垂直なら道方向の成分が 0 N/C なので、どれだけ長く進んでも $0\\times\\Delta r=0$ で**0 J**。電場が強くても、進む向きを後押ししていなければ仕事には効かない。横から押されているだけの区間だと考えるとよい。',
        },
        {
          id: 'p-uiewp-3',
          difficulty: 2,
          question: '4つの区間の寄与が 3 J、2 J、0 J、−2 J だった。道全体の仕事は?',
          choices: ['7 J', '3 J', '5 J', '−3 J'],
          answerIndex: 1,
          hint: '符号をそのままにして足す。',
          explanation: '$3+2+0-2=3$ で**3 J**。大きさだけを足すと 7 J、負の区間を無視すると 5 J になってしまう。符号は「合計を減らす向きに効いた区間」という情報なので、落とさずに足す。',
        },
        {
          id: 'p-uiewp-4',
          difficulty: 2,
          question: '曲がった道に沿う電気力の仕事を求めるとき、最初にすべきことは?',
          choices: [
            '曲線の式を作って微分する',
            '道を、ほぼ直線とみなせる短い区間に分ける',
            'いちばん強い電場を、道の全長に掛ける',
            '電場の大きさを平均してから全長を掛ける',
          ],
          answerIndex: 1,
          hint: '掛け算1回が使える形に、どうやって戻すか。',
          explanation: '短い区間の中なら道は直線、電場は一定とみなせるので、**掛け算1回が使える形に戻せる**。最強の電場を全長に掛けたり、単純に平均したりすると、向きの違う区間の寄与が混ざって答えが変わる。',
        },
        {
          id: 'p-uiewp-5',
          difficulty: 2,
          question: '道方向成分が −2 N/C、長さ 1 m の区間を +1 C が進んだ。この区間の寄与は?',
          choices: ['2 J', '−2 J', '0 J', '−1 J'],
          answerIndex: 1,
          hint: '成分の符号をそのまま掛ける。',
          explanation: '$1\\times(-2)\\times1=-2$ で**−2 J**。電場が進む向きの逆を向いているので、この区間は合計を減らす向きに効く。大きさ 2 J と答えると、向きの情報が落ちて合計がずれてしまう。',
        },
      ],
    },

    // ================= 5. 1枚のタイルを通る磁場 =================
    {
      id: 'ui-flux-one-tile',
      title: '1枚のタイルと磁場',
      subtitle: '正面から見た面積で決まる',
      enemy: { name: 'フラックスプレート', emoji: '🟦', maxHp: 124 },
      theme: '1枚の面を通り抜ける磁場の量を、向きも含めて数える',
      goal: r`垂直・平行・斜めを比べ、1枚の面を通る磁束を「正面から見た面積 × 磁場」として $\mathrm{T\cdot m^2=Wb}$ の単位で求められる。`,
      intro: '道に沿って足すのが仕事だった。もう一つの足し算は、面を貫いた量を数えることだ。まずは小さなタイル1枚を取り出し、磁場との向きの関係を見る。',
      outro: '1枚の面を通る磁束は、磁場と「正面から見た面積」の積。垂直なら最大、平行なら 0、斜めならその間になる。単位は T·m²=Wb。本数という言い方は数えるための比喩で、定義は磁場と面の向きから決まる量だ。',
      foundation: {
        known: '面積の求め方と、斜めから見ると面が細く見えること。矢印の向きが読めること。',
        startingPoint: '面の向きを法線という1本の矢印で表すところから出発する。',
        conditions: 'この段では磁場が一様で、タイルが平らな1枚の場合だけを扱う。B=2 T、面積 0.5 m² に固定する。',
        example: {
          given: 'B=2 T の磁場に垂直な、面積 0.5 m² のタイル。',
          tex: r`\Phi=B A=2\times0.5=1\,\mathrm{Wb}`,
          read: '単位は T×m²=Wb。垂直のときは面積がそのまま「正面から見た面積」になる。',
        },
      },
      glossary: {
        'Φ': '面を通る磁束 [Wb]。Wb = T·m²',
        'ΔA': 'タイル1枚の面積 [m²]。この段では 0.5 m²',
        '法線': '面に垂直な向きを表す矢印。面の表裏をこれで決める',
        'θ': '磁場と法線のなす角。0°で垂直、90°で平行',
      },
      units: [
        { end: 3, goal: '面の向きを法線で決め、垂直なときの磁束を作る', gain: '面の向きは法線1本で表す。垂直なら磁束は B×A で、単位は T·m²=Wb。' },
        { end: 6, goal: '平行・斜めのときに何が減るのかを見る', gain: '減るのは磁場ではなく「正面から見た面積」。平行なら 0、45°なら小さくなる。' },
        { end: 9, goal: '角度を連続で変え、本数という言い方を点検する', gain: '角度を変えると磁束はなめらかに変わる。本数は比喩で、定義は磁場と面の向きから決まる。' },
      ],
      slides: [
        {
          heading: '面を1枚置くと、何を数えることになるのだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'uie-tile-intro',
          body: '一様な磁場の中に、面積 0.5 m² のタイルを1枚置く。数えたいのは通り抜けた量だ。',
        },
        {
          heading: '面の向きは、どうやって1本の矢印で表すのだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'uie-tile-normal',
          body: 'タイルに垂直な矢印を1本立て、法線と呼ぶ。表裏の2つあるので、どちらを正か決める。',
        },
        {
          heading: '面に垂直な磁場は、どれだけ通り抜けるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-tile-perp',
          body: '磁場が法線と同じ向きなら最大。2×0.5=1 Wb になる。',
          formula: r`\Phi=BA=2\times0.5=1\,\mathrm{Wb}`,
          calculation: [
            { note: '垂直なら、磁場と面積を掛けるだけ', tex: r`\Phi=B\,A` },
            { note: '数値を入れる', tex: r`\Phi=2\,\mathrm{T}\times0.5\,\mathrm{m^2}` },
            { note: 'T·m² に付けた別名が Wb', tex: r`\Phi=1\,\mathrm{T\cdot m^2}=1\,\mathrm{Wb}` },
          ],
        },
        {
          heading: '面を磁場と平行にすると、通り抜ける量はどうなるのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'uie-tile-parallel',
          body: '寝かせると磁場は横をすり抜ける。面積は 0.5 m² のままなのに、磁束は 0 Wb。',
        },
        {
          heading: '斜めのとき、減っているのは何なのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-tile-tilt',
          body: '減るのは磁場でも面積でもない。減るのは「磁場の向きから見た面積」だ。',
        },
        {
          heading: '45°に傾けると、磁束はどうなるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-tile-projected',
          body: '正面から見た面積は 0.5 m² より小さく、およそ 0.35 m²。磁束はおよそ 0.71 Wb。',
          formula: r`\Phi=BA\cos 45^\circ\approx0.71\,\mathrm{Wb}`,
          calculation: [
            { note: '正面から見た面積を先に出す', tex: r`A_{\perp}=0.5\cos 45^\circ\approx0.35\,\mathrm{m^2}` },
            { note: '磁場を掛ける', tex: r`\Phi=2\times0.35\approx0.71\,\mathrm{Wb}` },
          ],
        },
        {
          heading: '角度を変えると、磁束はどう動くのだろう?',
          beat: '解決',
          role: '観察',
          figure: 'uie-tile-slider',
          body: '角を 0° から 90° へ動かすと、磁束は 1 Wb から 0 Wb へなめらかに減る。',
        },
        {
          heading: '「本数」という言い方は、どこまで正しいのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-tile-lines-caution',
          body: '線を引いて数えるのは比喩だ。定義は、磁場と面の向きから決まる量のほうにある。',
          formulaNote: '本数は数えるための絵。定義は面と磁場から決まる量',
        },
        {
          heading: '1枚の面の磁束は、どう書けばよいのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'uie-tile-summary',
          body: '磁束は「磁場の法線方向の成分 × 面積」。効くのは法線方向の成分だけだ。',
          formula: r`\Phi=B_{\perp}A`,
          formulaNote: '仕事で道方向の成分だけが効いたのと同じ読み方',
        },
      ],
      preview: {
        goal: r`\Phi=\int_S\vec B\cdot d\vec A`,
        now: '1枚の平らな面について、正面から見た面積×磁場で磁束を出すこと',
        later: '面を細かく分けること、曲面にすること、向きの掛け算を内積で書くこと',
      },
      leadsTo: ['ue-integrals', 'ue-faraday'],
      problems: [
        {
          id: 'p-uieflx-1',
          difficulty: 1,
          question: 'B=2 T の一様な磁場に垂直に置いた、面積 0.5 m² の面を通る磁束は?',
          choices: ['1 Wb', '4 Wb', '0.25 Wb', '2.5 Wb'],
          answerIndex: 0,
          hint: '垂直なら、磁場と面積を掛けるだけ。単位は T×m²。',
          explanation: '$\\Phi=BA=2\\times0.5=1$ で、単位は T·m²=**Wb**。垂直のときは面積がそのまま「正面から見た面積」になる。4 Wb は面積で割ってしまった値で、単位も Wb にならない。',
        },
        {
          id: 'p-uieflx-2',
          difficulty: 1,
          question: '同じ面を、磁場と平行になるように寝かせた。この面を通る磁束は?',
          choices: ['1 Wb', '0 Wb', '2 Wb', '0.5 Wb'],
          answerIndex: 1,
          hint: '磁場の向きから見ると、この面はどう見えるか。',
          explanation: '磁場の向きから見ると面は線にしか見えず、正面から見た面積が 0 になるので**0 Wb**。面積は 0.5 m² のままなので、面積だけでは磁束が決まらないことが分かる。効くのは法線方向の成分だけ。',
        },
        {
          id: 'p-uieflx-3',
          difficulty: 2,
          question: '同じ面を 45° 傾けた。このときの磁束として正しいものは?',
          choices: ['1 Wb のまま', '0 Wb', '0 Wb と 1 Wb の間の値', '2 Wb'],
          answerIndex: 2,
          hint: '正面から見た面積は、0 と 0.5 m² のどちらに近いか。',
          explanation: '傾けると正面から見た面積が 0.5 m² より小さくなるので、磁束は **0 Wb と 1 Wb の間**（およそ 0.71 Wb）。垂直でも平行でもない中間の値になる。角度が 0° に近いほど 1 Wb に、90° に近いほど 0 Wb に近づく。',
        },
        {
          id: 'p-uieflx-4',
          difficulty: 1,
          question: 'T（テスラ）と m² を掛け合わせた単位は?',
          choices: ['Wb', 'J', 'V', 'N/C'],
          answerIndex: 0,
          hint: '磁束の単位を思い出す。',
          explanation: 'T·m² に付けた別名が**Wb**（ウェーバ）で、面を通る磁束の単位。J は仕事、V は電位差、N/C は電場の単位で、いずれも面と磁場を掛けた量ではない。単位の並びを見れば何を掛けたかが読める。',
        },
        {
          id: 'p-uieflx-5',
          difficulty: 3,
          question: '磁力線の「本数」という言い方について、正しいものは?',
          choices: [
            '空間に実在するひもの本数を数えている',
            '量を見えるようにするための比喩で、定義は磁場と面の向きから決まる量にある',
            '本数は面の向きによらず決まる',
            '本数は磁場の大きさによらず決まる',
          ],
          answerIndex: 1,
          hint: '線を引く前から、磁束の値は決まっているか。',
          explanation: '線は量を数えやすくするために人が引く目印で、**定義は磁場と面の向きから決まる量のほうにある**。空間にひもが張られているわけではない。値は面の向きにも磁場の大きさにも依存するので、残りの選択肢は成り立たない。',
        },
      ],
    },

    // ================= 6. タイルを並べて足す =================
    {
      id: 'ui-flux-many-tiles',
      title: 'タイルを並べて足す',
      subtitle: '1枚ずつ作って合計する',
      enemy: { name: 'タイルスウォーム', emoji: '🧱', maxHp: 130 },
      theme: '面を小さなタイルに分け、寄与を足して全体の磁束を求める',
      goal: r`4枚のタイルの寄与 $1,1,0.5,0\,\mathrm{Wb}$ を足して、面全体の磁束 $2.5\,\mathrm{Wb}$ を求められる。`,
      intro: 'タイル1枚の磁束は作れるようになった。では大きな面はどうするか。仕事のときと同じで、小さく分けて1枚ずつ作り、順に足す。',
      outro: '面の磁束は、タイルごとの「磁場の法線成分 × タイルの面積」を足したもの。今回は 1+1+0.5+0=2.5 Wb。法線を逆向きに取り直すと、符号がまとめて反転する。',
      foundation: {
        known: 'タイル1枚の磁束が B×A で出ること。仕事を小区間に分けて足したこと。',
        startingPoint: '大きな面を、1枚ずつ扱えるタイルへ分けるところから出発する。',
        conditions: 'この段ではタイルは4枚、1枚の面積はどれも 0.5 m²。法線方向の磁場は場所ごとに違ってよい。',
        example: {
          given: '法線方向の磁場が 2 T、ΔA=0.5 m² のタイル1枚の寄与を求める。',
          tex: r`\Delta\Phi=B_{\perp}\,\Delta A=2\times0.5=1\,\mathrm{Wb}`,
          read: '単位は T·m²=Wb。この1枚を部品にして、4枚分を順に足していく。',
        },
      },
      glossary: {
        'ΔA': 'タイル1枚の面積 [m²]。この段ではどれも 0.5 m²',
        'ΔΦ': 'タイル1枚の寄与 [Wb]。符号を含む',
        'Φ': 'タイルの寄与を全部足した磁束 [Wb]',
        'B⊥': 'そのタイルの法線方向の磁場の成分 [T]',
      },
      units: [
        { end: 4, goal: 'タイル1枚の寄与を作り、同じ形で2枚目まで足す', gain: '1枚は B⊥×ΔA。2×0.5=1 Wb が2枚で 2 Wb。' },
        { end: 8, goal: '磁場が場所ごとに違う場合も、1枚ずつ作って足す', gain: '法線方向の成分が 1 T なら 0.5 Wb、0 T なら 0 Wb。合計は 2.5 Wb。' },
        { end: 12, goal: '仕事の和との対応と、法線の向きの効果を確かめる', gain: '道の小区間が面の小タイルに変わっただけ。法線を反転すると符号が反転する。' },
      ],
      slides: [
        {
          heading: 'タイル1枚の寄与を、もう一度作っておこう',
          beat: '基本事項',
          role: '観察',
          figure: 'uie-tiles-one',
          body: '法線方向の磁場が 2 T、面積が 0.5 m² のタイル。寄与は 2×0.5=1 Wb。',
          formula: r`\Delta\Phi=B_{\perp}\,\Delta A=2\times0.5=1\,\mathrm{Wb}`,
        },
        {
          heading: '面を4枚のタイルに分けると、何が見えるだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'uie-tiles-grid4',
          body: '面積はどれも 0.5 m²。法線方向の磁場は、タイルごとに 2 T、2 T、1 T、0 T だ。',
        },
        {
          heading: 'タイル1の寄与は、いくつになるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-tiles-cell1',
          body: '法線方向の磁場は 2 T。寄与は 2×0.5=1 Wb。',
          calculation: [
            { note: '法線方向の成分に、タイルの面積を掛ける', tex: r`\Delta\Phi_1=2\times0.5` },
            { note: 'タイル1の寄与', tex: r`\Delta\Phi_1=1\,\mathrm{Wb}` },
          ],
        },
        {
          heading: 'タイル2の寄与は、いくつになるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-tiles-cell2',
          body: 'タイル2も 2 T なので 1 Wb。ここまでの合計は 2 Wb。',
          calculation: [
            { note: '同じ形で2枚目を作る', tex: r`\Delta\Phi_2=2\times0.5=1\,\mathrm{Wb}` },
            { note: 'ここまでの合計', tex: r`\Delta\Phi_1+\Delta\Phi_2=2\,\mathrm{Wb}` },
          ],
        },
        {
          heading: '磁場が弱いタイルは、どう数えるのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'uie-tiles-weak',
          body: 'タイル3と4では、法線方向の磁場が 2 T より小さい。同じ掛け算でよいのだろうか。',
        },
        {
          heading: 'タイル3の寄与は、いくつになるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-tiles-cell3',
          body: '法線方向の磁場は 1 T。寄与は 1×0.5=0.5 Wb。掛け算の形は同じだ。',
          calculation: [
            { note: 'その場所の法線方向の成分を使う', tex: r`\Delta\Phi_3=1\times0.5` },
            { note: 'タイル3の寄与', tex: r`\Delta\Phi_3=0.5\,\mathrm{Wb}` },
          ],
        },
        {
          heading: 'タイル4の寄与は、いくつになるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-tiles-cell4',
          body: 'タイル4では磁場が面と平行で、法線方向の成分は 0 T。寄与は 0 Wb。',
          calculation: [
            { note: '法線方向の成分が0なら', tex: r`\Delta\Phi_4=0\times0.5` },
            { note: 'タイル4の寄与', tex: r`\Delta\Phi_4=0\,\mathrm{Wb}` },
          ],
        },
        {
          heading: '4枚を合計すると、磁束はいくらになるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-tiles-total',
          body: '1+1+0.5+0=2.5 Wb。1枚ずつ作って順に足しただけだ。',
          formula: r`\Phi=1+1+0.5+0=2.5\,\mathrm{Wb}`,
          calculation: [
            { note: 'タイルごとの寄与を並べる', tex: r`\Phi=\Delta\Phi_1+\Delta\Phi_2+\Delta\Phi_3+\Delta\Phi_4` },
            { note: '数値を入れる', tex: r`\Phi=1+1+0.5+0` },
            { note: '合計する', tex: r`\Phi=2.5\,\mathrm{Wb}` },
          ],
        },
        {
          heading: 'この足し算は、道の足し算と同じ形だろうか?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-tiles-analogy',
          body: '道では小区間の仕事を足した。面では小タイルの磁束を足す。骨組みは同じだ。',
          formulaNote: '道の小片が、面の小片に変わっただけ',
        },
        {
          heading: '面の向きを裏返すと、何が反転するのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'uie-tiles-flip',
          body: '法線を反対向きに取り直す。タイルも磁場も動かしていないのに、矢印だけが逆を向く。',
        },
        {
          heading: '裏返した面の磁束は、いくらになるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-tiles-negative',
          body: '法線方向の成分の符号が反転し、合計は −2.5 Wb。大きさは同じだ。',
          formula: r`\Phi=-2.5\,\mathrm{Wb}`,
        },
        {
          heading: 'タイルを16枚に増やしても、やることは同じだろうか?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'uie-tiles-refine16',
          body: '1枚ずつ「法線方向の成分 × 面積」を作って符号のまま足す。枚数が増えても同じだ。',
          formulaNote: '閉じた面では、外向きを正と決めることになる',
        },
      ],
      preview: {
        goal: r`\Phi=\sum_i\vec B_i\cdot\Delta\vec A_i\ \longrightarrow\ \int_S\vec B\cdot d\vec A`,
        now: 'タイルごとの寄与を、法線の向きに合わせて符号つきで足すこと',
        later: 'タイルを限りなく細かくすること、曲面にすること、内積で書くこと',
      },
      leadsTo: ['ue-integrals', 'ue-gauss'],
      problems: [
        {
          id: 'p-uiemt-1',
          difficulty: 1,
          question: '法線方向の磁場が 2 T、面積 0.5 m² のタイル1枚の寄与は?',
          choices: ['1 Wb', '0.5 Wb', '2 Wb', '4 Wb'],
          answerIndex: 0,
          hint: '1枚だけなら、法線方向の成分と面積を掛けるだけ。',
          explanation: '$\\Delta\\Phi=B_{\\perp}\\Delta A=2\\times0.5=1$ で**1 Wb**。単位は T·m²=Wb。これが全体を組み立てるための部品になる。0.5 Wb は磁場を掛け忘れた面積そのものの値。',
        },
        {
          id: 'p-uiemt-2',
          difficulty: 1,
          question: '面積 0.5 m² のタイルで、法線方向の磁場が 1 T だった。このタイルの寄与は?',
          choices: ['1 Wb', '0.5 Wb', '2 Wb', '0 Wb'],
          answerIndex: 1,
          hint: '掛け算の形は変わらない。数字だけが変わる。',
          explanation: '$1\\times0.5=0.5$ で**0.5 Wb**。磁場が弱くなっても掛け算の形は同じで、使う数字が変わるだけ。タイルごとに「その場所の法線方向の成分」を使うのがこの段の要点。',
        },
        {
          id: 'p-uiemt-3',
          difficulty: 2,
          question: '4枚のタイルの寄与が 1 Wb、1 Wb、0.5 Wb、0 Wb だった。面全体の磁束は?',
          choices: ['2 Wb', '2.5 Wb', '4 Wb', '0.5 Wb'],
          answerIndex: 1,
          hint: '順に足すだけ。0 のタイルも数に入れる。',
          explanation: '$1+1+0.5+0=2.5$ で**2.5 Wb**。寄与 0 のタイルは合計を増やさないが、数え忘れではなく「0 を足した」と扱う。2 Wb は 0.5 のタイルを落とした値。',
        },
        {
          id: 'p-uiemt-4',
          difficulty: 2,
          question: '面はそのままで、法線を反対向きに取り直した。磁束の値はどうなる?',
          choices: ['変わらない', '符号が反転する', '0になる', '2倍になる'],
          answerIndex: 1,
          hint: '磁束は、法線方向の成分で決まっていた。',
          explanation: '法線が反転すると、磁場の法線方向の成分の符号が反転するので、磁束も**符号が反転**して −2.5 Wb になる。大きさは同じ。符号は面の向きをどう決めたかに紐づいた情報で、閉じた面では外向きを正と決めてこの曖昧さをなくす。',
        },
        {
          id: 'p-uiemt-5',
          difficulty: 3,
          question: '仕事の足し算と磁束の足し算に共通している形は?',
          choices: [
            'いちばん大きい値を、全体に掛ける',
            'その場所の成分 × 小さな幅（または小さな面積）を、符号のまま足す',
            '平均値を求めてから2で割る',
            '最大値と最小値を足して比べる',
          ],
          answerIndex: 1,
          hint: '仕事では何と何を掛けて足したかを思い出す。',
          explanation: '仕事は「道方向の成分×区間の長さ」、磁束は「法線方向の成分×タイルの面積」。どちらも**その場所の成分に小片を掛けて、符号のまま足す**という同じ骨組み。変わったのは小片が長さから面積になったことだけ。',
        },
      ],
    },

    // ================= 7. 閉じた袋の出入り =================
    {
      id: 'ui-closed-bag',
      title: '袋の出入りを数える',
      subtitle: '入るが負、出るが正',
      enemy: { name: 'クローズドバッグ', emoji: '🛍️', maxHp: 132 },
      theme: '閉じた面を出入りする矢印を、符号つきで数える',
      goal: r`閉じた面では外向きを正と決め、出入りの寄与を足して正味の量を求め、合計が $0$ でも場が $0$ とは限らないと説明できる。`,
      intro: '面を袋のように閉じると、表と裏の迷いがなくなる。外向きを正と決めればよいからだ。ここでは袋を出入りする矢印を符号つきで数える。',
      outro: '閉じた面では外向きを正と決め、出る寄与を正、入る寄与を負として足す。合計が 0 でも、袋の中の場が 0 とは限らない。一様な電場を貫く箱がその反例で、入った分だけ出ていっただけだ。',
      foundation: {
        known: 'タイルごとに法線を立て、法線方向の成分×面積を足したこと。符号が向きを表すこと。',
        startingPoint: '閉じた面では法線を外向きに決める、という約束から出発する。',
        conditions: 'この段では静電場を扱う。箱の面は平らで、電場は面に垂直または平行とする。',
        example: {
          given: '3 N/C の一様な電場が、面積 2 m² の左右の面を垂直に貫く箱。',
          tex: r`(-6)+6+0+0+0+0=0`,
          read: '左の面が −6、右の面が +6、残り4面は 0。合計は 0 だが、箱の中の電場は 3 N/C のままある。',
        },
      },
      glossary: {
        '外向き法線': '閉じた面で、袋の外を向くと決めた法線。これを正とする',
        'ΔΦ': '1枚の面の寄与。出るとき正、入るとき負',
        E: 'この段の一様な電場 [N/C]。箱の中でも 3 N/C のまま',
        q: '袋の中に入れた電荷 [C]。符号で出入りの向きが変わる',
      },
      units: [
        { end: 3, goal: '閉じた面の向きを決め、出入りを符号で数える', gain: '外向きを正と決めれば、出る矢印は正、入る矢印は負として足せる。' },
        { end: 6, goal: '合計0と、場が0であることを区別する', gain: '一様な電場を貫く箱では合計が 0 になるが、中の電場は 0 ではない。反例として使える。' },
        { end: 9, goal: '袋の中の電荷と、正味の量を結びつける', gain: '中に正の電荷があると出るほうが増え、負なら入るほうが増える。袋の形は答えを変えない。' },
      ],
      slides: [
        {
          heading: '閉じた面では、どちらを正と決めるのだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'uie-bag-normal',
          body: '面を閉じると内と外が分かれる。そこで法線はいつも外向きに取ると決める。',
        },
        {
          heading: '入る矢印と出る矢印は、どう数え分けるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-bag-inout',
          body: '外向き法線と同じ側へ抜ける矢印は正、外から入る矢印は負として数える。',
          formulaNote: '出る寄与は正、入る寄与は負',
        },
        {
          heading: '一様な電場を貫く箱では、合計はいくつになるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-bag-uniform-box',
          body: '左の面は −6、右の面は +6、残り4面は電場と平行で 0。合計は 0 になる。',
          formula: r`(-6)+6+0+0+0+0=0`,
          calculation: [
            { note: '入る面は外向き法線と逆なので負', tex: r`\Delta\Phi_{\text{左}}=-3\times2=-6` },
            { note: '出る面は外向き法線と同じなので正', tex: r`\Delta\Phi_{\text{右}}=+3\times2=+6` },
            { note: '残り4面は電場と平行なので0', tex: r`(-6)+6+0+0+0+0=0` },
          ],
        },
        {
          heading: '合計が0なら、箱の中に電場はないのだろうか?',
          beat: '疑問',
          role: '問い',
          figure: 'uie-bag-zero-question',
          body: '出入りを足したら 0 になった。では、この箱の中には電場がないのだろうか。',
        },
        {
          heading: '合計0が語っているのは、何についてのことだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-bag-zero-answer',
          body: '箱の中の電場は 3 N/C のままある。0 が語るのは「入った分だけ出た」ことだけだ。',
          formulaNote: '合計0でも、場が0とは限らない',
        },
        {
          heading: '袋の中に正の電荷を入れると、数はどう変わるのだろう?',
          beat: '解決',
          role: '観察',
          figure: 'uie-bag-with-charge',
          body: '電荷から出た矢印が袋を突き抜ける。出ていく分が増え、正味の量は正になる。',
        },
        {
          heading: '負の電荷を入れたら、どうなるのだろう?',
          beat: '解決',
          role: '観察',
          figure: 'uie-bag-negative-charge',
          body: '矢印は内向きになる。入ってくる分が増え、正味の量は負になる。',
        },
        {
          heading: '袋の形を変えると、合計は変わるのだろうか?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-bag-shape',
          body: '丸い袋でも角ばった袋でも、正味の量は同じ。中の電荷が変わっていないからだ。',
        },
        {
          heading: '閉じた面の合計は、何を教えてくれるのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'uie-bag-summary',
          body: '教えてくれるのは、中にある電荷の正味の符号と量だけだ。',
          formulaNote: '場の強さや、中のどこにあるかは教えてくれない',
        },
      ],
      preview: {
        goal: r`\oint\vec B\cdot d\vec A=0`,
        now: '閉じた面の出入りを、外向きを正として符号つきで数えること',
        later: '任意の閉曲面にすること、面を細かく分けること、内積で書くこと',
      },
      leadsTo: ['ue-gauss', 'ue-integrals'],
      problems: [
        {
          id: 'p-uiebag-1',
          difficulty: 1,
          question: '閉じた面で、出ていく矢印と入ってくる矢印はそれぞれどう数える?',
          choices: ['どちらも正', '出るが正、入るが負', '出るが負、入るが正', 'どちらも負'],
          answerIndex: 1,
          hint: '法線を外向きに決めたことを思い出す。',
          explanation: '閉じた面では法線を外向きに取ると決めたので、法線と同じ側へ抜ける矢印が**正**、逆に入ってくる矢印が**負**になる。どちらも正として数えると打ち消し合いが起きず、中の電荷との対応が作れなくなる。',
        },
        {
          id: 'p-uiebag-2',
          difficulty: 2,
          question: '3 N/C の一様な電場が、面積 2 m² の左右の面を垂直に貫く箱がある。この2面の寄与は?',
          choices: [
            'ともに +6 N·m²/C',
            '左が −6、右が +6 N·m²/C で、合計は 0',
            'ともに −6 N·m²/C',
            'ともに 0',
          ],
          answerIndex: 1,
          hint: '外向き法線から見て、それぞれの面はどちら向きか。',
          explanation: '電場が入ってくる左の面は外向き法線と逆なので **−6**、出ていく右の面は同じ向きなので **+6**。足すと 0 になる。どちらも同じ符号にしてしまうと、一様な電場でも合計が 0 にならず、中に電荷がないことと合わなくなる。',
        },
        {
          id: 'p-uiebag-3',
          difficulty: 3,
          question: 'ある閉じた面で、出入りの合計がちょうど 0 だった。このとき確実に言えることは?',
          choices: [
            '面の内側に電場は存在しない',
            '面の内側の正味の電荷が 0 である',
            '電場はどこでも 0 である',
            '面の形が球である',
          ],
          answerIndex: 1,
          hint: '一様な電場を貫く箱を思い出す。合計は0だが、中はどうだったか。',
          explanation: '合計 0 が言っているのは「入った分だけ出ていった」ことだけで、**内側の正味の電荷が 0** であることに対応する。一様な電場を貫く箱では合計が 0 でも、中の電場は 3 N/C のまま存在する。合計0と場が0を混同しないこと。',
        },
        {
          id: 'p-uiebag-4',
          difficulty: 2,
          question: '袋の中に負の電荷を入れると、袋を出入りする正味の量はどうなる?',
          choices: ['正になる', '負になる', '0のまま', '2倍になる'],
          answerIndex: 1,
          hint: '負の電荷のまわりでは、矢印はどちらを向くか。',
          explanation: '負の電荷のまわりでは矢印が中心へ向かうので、袋へ入ってくる分が増える。入る寄与は負として数えるから、正味の量も**負**になる。符号がそのまま、中の電荷の符号を映していることになる。',
        },
        {
          id: 'p-uiebag-5',
          difficulty: 2,
          question: '同じ電荷を、丸い袋で囲んだ場合と角ばった袋で囲んだ場合を比べると、正味の量は?',
          choices: ['丸いほうが大きい', '角ばったほうが大きい', 'どちらも同じ', '袋の表面積に比例する'],
          answerIndex: 2,
          hint: '袋を取り替えたとき、中身は変わったか。',
          explanation: '袋の形を変えても、中に入っている電荷は変わらないので正味の量は**同じ**になる。面が広がれば1枚あたりの寄与は小さくなるが、面の枚数が増えて釣り合う。表面積そのものに比例するわけではない。',
        },
      ],
    },

    // ================= 8. 中心の電荷と球面 =================
    {
      id: 'ui-charge-and-flux-preview',
      title: '中心の電荷と球面',
      subtitle: 'ガウスの法則への入口',
      enemy: { name: 'スフィアセンチネル', emoji: '🔮', maxHp: 136 },
      theme: '中心の電荷と、それを囲む球面の出入りを結びつける',
      goal: r`球面を外向きに向き付け、中の電荷が増えると正味の量が増えることを数え、上級編のガウスの法則の形を見通せる。`,
      intro: '袋の出入りを符号つきで数えられるようになった。では、袋の中の電荷を増やすと数はどう変わるのか。中心に電荷を置いた球面で確かめる。',
      outro: '球面から出ていく正味の量は、中の電荷に比例して増える。球を大きくしても、矢印が弱まる分だけ面積が広がるので合計は変わらない。この対応を式にしたものが、上級編で扱うガウスの法則だ。',
      foundation: {
        known: '閉じた面では外向きを正とし、出る寄与を正、入る寄与を負として足すこと。',
        startingPoint: '中心に電荷を1個置き、それを球面で囲むところから出発する。',
        conditions: 'この段では静電場を扱い、球面の中心に点電荷を置いた場合だけを数える。',
        example: {
          given: '中心の正電荷から出る矢印を8本と数え、球面全体で数える。',
          tex: r`\Phi_{\text{正味}}=+8`,
          read: '本数は数えるための比喩。定義は電場と面から決まる量で、上級編で式として書く。',
        },
      },
      glossary: {
        'Q内': '閉じた面の内側にある電荷の正味の量 [C]',
        'Φ正味': '閉じた面を出入りする量の合計。出るが正、入るが負',
        r: '球面の半径 [m]。中心の電荷からの距離',
        'ε₀': '真空の誘電率 [F/m]。上級編で比例の係数として現れる',
      },
      units: [
        { end: 3, goal: '球面の向きを決め、中の電荷と正味の量を結ぶ', gain: '外向きを正とすると、中に正の電荷があるとき正味の量は正になる。' },
        { end: 6, goal: '電荷の符号・大きさ・球の半径を変えて確かめる', gain: '電荷に比例して増え、符号で向きが変わる。半径を変えても合計は変わらない。' },
        { end: 9, goal: '「本数」の限界を確かめ、上級編の形を見通す', gain: '本数は比喩で、定義は電場と面から決まる量。上級編では閉曲面の積分として書く。' },
      ],
      slides: [
        {
          heading: '球面で囲むとき、どちらを正と決めるのだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'uie-sphere-intro',
          body: '中心に電荷を置き、球面で囲む。閉じた面なので、法線は外向きに取る。',
        },
        {
          heading: '中心に正の電荷を1個入れると、どうなるのだろう?',
          beat: '解決',
          role: '観察',
          figure: 'uie-sphere-one',
          body: '矢印は外向きに並び、球面のどこでも外へ抜ける。正味の量は +8 と数えておく。',
        },
        {
          heading: '電荷を2倍にすると、出ていく量はどうなるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'uie-sphere-double',
          body: '各点の電場が2倍になる。面は変えていないので、正味の量も2倍の +16。',
          calculation: [
            { note: '電荷を2倍にすると、各点の電場も2倍', tex: r`E\to 2E` },
            { note: '面は変えていないので、正味の量も2倍', tex: r`\Phi_{\text{正味}}\to 2\Phi_{\text{正味}}` },
          ],
        },
        {
          heading: '負の電荷に取り替えたら、符号はどうなるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-sphere-negative',
          body: '矢印は内向きに並び、すべて外から内へ抜ける。正味の量は −8 になる。',
        },
        {
          heading: '球を大きくすると、合計は減ってしまうのだろうか?',
          beat: '疑問',
          role: '問い',
          figure: 'uie-sphere-bigger',
          body: '半径を2倍にすると、球面上の矢印は短くなる。正味の量も減るのだろうか。',
        },
        {
          heading: '弱くなる矢印と広くなる面積は、釣り合うのだろうか?',
          beat: '解決',
          role: '操作',
          figure: 'uie-sphere-balance',
          body: '電場は4分の1に弱まり、面積は4倍に広がる。積は変わらない。',
          calculation: [
            { note: '電場は距離の2乗に反比例して弱まる', tex: r`E\to\frac{E}{4}` },
            { note: '球の面積は半径の2乗に比例して広がる', tex: r`A\to 4A` },
            { note: '積は変わらない', tex: r`\frac{E}{4}\times 4A=EA` },
          ],
        },
        {
          heading: '電荷を球の外に置いたら、合計はどうなるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-sphere-outside',
          body: '矢印は片側から入り、反対側から出る。入った分だけ出るので正味は 0。',
        },
        {
          heading: '「本数」で数えてよいのは、どういう意味でだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'uie-sphere-lines-caution',
          body: '本数は比喩だ。定義は電場と面の向きから決まる量のほうにある。',
          formulaNote: '本数は絵。定義は電場と面から決まる量',
        },
        {
          heading: '上級編では、この対応をどう書くのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'uie-sphere-gauss-preview',
          body: '閉じた面を出る正味の量は、中の電荷で決まる。式にしたものがガウスの法則だ。',
          formulaNote: '上級編で $\\oint\\vec E\\cdot d\\vec A=Q_{\\text{内}}/\\varepsilon_0$ として扱う',
        },
      ],
      preview: {
        goal: r`\oint\vec E\cdot d\vec A=\frac{Q_{\text{内}}}{\varepsilon_0}`,
        now: '袋に出入りする矢印の数を、符号つきで数えること',
        later: 'タイルを細かくすること、任意の閉曲面にすること、内積で書くこと',
      },
      leadsTo: ['ue-gauss', 'ue-integrals'],
      problems: [
        {
          id: 'p-uiesph-1',
          difficulty: 1,
          question: '球面の中心に正の電荷を1個置いた。球面を出入りする正味の量は?',
          choices: ['正になる', '負になる', '0になる', '球の半径によって符号が変わる'],
          answerIndex: 0,
          hint: '正の電荷のまわりで、矢印はどちらを向くか。',
          explanation: '正の電荷のまわりでは矢印が外向きに並ぶので、球面のどこでも外へ抜けていく。出る寄与を正と数える約束だから、正味の量は**正**になる。半径を変えても符号は変わらない。',
        },
        {
          id: 'p-uiesph-2',
          difficulty: 2,
          question: '球面の中心の電荷を2倍にした。球面から出ていく正味の量は?',
          choices: ['半分になる', '変わらない', '2倍になる', '4倍になる'],
          answerIndex: 2,
          hint: '電荷を2倍にすると、各点の電場はどうなるか。',
          explanation: '電荷が2倍になると各点の電場も2倍になり、面は変えていないので正味の量も**2倍**。中の電荷に比例して増えるという対応が、そのまま数に現れている。4倍になるのは面積が半径の2乗で増えるときの話で、ここでは面を変えていない。',
        },
        {
          id: 'p-uiesph-3',
          difficulty: 3,
          question: '同じ電荷を囲む球面の半径を2倍にした。出ていく正味の量は?',
          choices: ['4倍になる', '4分の1になる', '変わらない', '2倍になる'],
          answerIndex: 2,
          hint: '電場の弱まり方と、面積の広がり方を比べる。',
          explanation: '電場は距離の2乗に反比例して4分の1に弱まるが、球の面積は4倍に広がる。積は $\\frac{1}{4}\\times4=1$ で打ち消し合うので、正味の量は**変わらない**。面の取り方によらず中の電荷だけで決まる、という性質の現れ。',
        },
        {
          id: 'p-uiesph-4',
          difficulty: 2,
          question: '電荷を球面の外側に置いた。この球面を出入りする正味の量は?',
          choices: ['0', '正になる', '負になる', '電荷の大きさに比例する'],
          answerIndex: 0,
          hint: '矢印は球にどう出入りするか、通り道を追う。',
          explanation: '外の電荷が作る矢印は球の片側から入り、反対側から出ていく。入る寄与が負、出る寄与が正なので打ち消し合い、正味の量は**0**。中にない電荷は合計に効かない。ただし球面上の電場そのものは 0 ではない。',
        },
        {
          id: 'p-uiesph-5',
          difficulty: 2,
          question: 'この段で言えるガウスの法則の位置づけとして、正しいものは?',
          choices: [
            '閉じた面の正味の量が中の電荷で決まるという法則で、式としては上級編で扱う',
            '袋の中の電荷を暗記するための規則である',
            '磁力線の実在する本数を数えるための規則である',
            '電位を求めるための規則である',
          ],
          answerIndex: 0,
          hint: 'いまできればよいことは何だったか。',
          explanation: '初級でできればよいのは、**閉じた面の出入りを符号つきで数えること**まで。その数え方と中の電荷の対応を式にしたものがガウスの法則で、面を細かく分けることや内積で書くことは上級編で扱う。暗記する規則ではない。',
        },
      ],
    },
  ],
};
