import type { LevelChapter } from './schema';
import { r } from './schema';

/** 電磁気学・中級 — 電場・磁場を足し合わせる。
 * 初級で作った「矢印の地図」「小片に分けて足す」を、ベクトルと有限和の式に翻訳する。
 * 1枚のスライドは1つの役割だけを持ち、式変形は一手ずつ別の枚に分ける。
 * 誤解を防ぐ条件（静電場・外向き法線・対称性）は、本文か図の中に必ず残す。 */

/** どのステージでも使う、この章の記号。基本セット（electric）に上書きして足す。 */
const emSymbols: Record<string, string> = {
  r_i: 'i番目の小区間・小タイルの代表点の位置ベクトル [m]。どの点の場の値を使うかを指す',
  'Δr_i': 'i番目の小区間を進む向きと長さを持つ矢印 [m]。長さが進んだ距離、向きが進む向き',
  n: '面に垂直で大きさ1の単位法線ベクトル。向きだけを運ぶ。閉じた面では外向きにとる',
  'ΔA': 'i番目の小タイルの面積 [m²]。向きを持たない正の数',
  'ΔA_ベクトル': '向き付き面積（面積ベクトル）。向きは法線と同じ、大きさは面積ΔA',
  C: 'この章では線積分をする曲線そのもの。出発点・到着点・進む向きまで含めて指定する',
  S: 'この章では面積分をする面全体。閉じた面のときは袋の表面すべてを指す',
  N: '曲線を分けた小区間の個数、または面を分けた小タイルの枚数',
  i: '小区間・小タイルに付けた通し番号。Σの添字として1からNまで動く',
  theta: 'この章では、2本のベクトルのなす角。力と小移動、または磁場と法線の間の角',
};

export const um_em: LevelChapter = {
  id: 'um-em',
  title: '電磁気学',
  subtitle: '電場・磁場を足し合わせる',
  familyId: 'uem',
  level: 'middle',
  stages: [
    // ================= 1. 小区間の仕事をベクトルで書く =================
    {
      id: 'um-line-element',
      title: '小区間の仕事',
      subtitle: '内積で一区間を書く',
      enemy: { name: 'ドットスライム', emoji: '🟦', maxHp: 118 },
      theme: '小区間の移動を矢印にして、仕事を内積で書く',
      goal: r`小区間の仕事を $\Delta W_i=\vec F(\vec r_i)\cdot\Delta\vec r_i$ と書き、同じ向き・直角・逆向きで符号がどうなるかを言える。`,
      intro: '初級では、道を小片に分けて仕事を足した。ここでは小片1つぶんを、ベクトルの式にする。使う道具は内積ひとつだけだ。',
      outro: '小区間の移動は $\\Delta\\vec r_i$ という矢印。効くのは力のうち道方向の成分 $|\\vec F|\\cos\\theta_i$ だけで、それに小移動の長さを掛けたものが内積 $\\vec F(\\vec r_i)\\cdot\\Delta\\vec r_i$。同じ向きなら正、直角なら0、逆向きなら負になる。',
      foundation: {
        known: '電場は位置ごとの矢印であること。初級で、道を小片に分けて仕事を足したこと。',
        startingPoint: '仕事は「力のうち進む向きに揃った成分 × 進んだ距離」である、というところから出発する。',
        conditions: '小区間の中では、力も場も一定とみなす。平面（xy面）の上で考える。',
        example: {
          given: '力(3,0) Nの中を、小区間(1,0) mだけ進む。',
          tex: r`\Delta W=3\times1+0\times0=3\,\mathrm J`,
          read: '内積は成分どうしの積の和。N×m=Jで単位もそろう。',
        },
      },
      glossary: {
        ...emSymbols,
        E_x: '電場のx方向の成分 [N/C]。符号が右向きか左向きかを表す',
        E_y: '電場のy方向の成分 [N/C]。符号が上向きか下向きかを表す',
        'ΔW_i': 'i番目の小区間でされた仕事 [J]',
      },
      units: [
        { end: 4, goal: '場を成分で書き、道が曲がると困ることを見つける', gain: '場は位置ごとの矢印で、成分の組で書ける。道が曲がると、掛けるべき距離が1つに決まらない。' },
        { end: 7, goal: '小移動の矢印と代表点、そして力を用意する', gain: '小区間は矢印Δr、場を読む場所は代表点r。電荷が受ける力はqEで、単位はN。' },
        { end: 11, goal: '有効な力から内積の式まで、一手ずつ進む', gain: '効くのは道方向の成分だけ。その成分×小移動の長さが内積で、小区間の仕事になる。' },
        { end: 14, goal: '符号の3つの場合を確かめ、誤りの型を押さえる', gain: '同じ向きは正、直角は0、逆向きは負。大きさだけを掛けると向きの情報が落ちる。' },
      ],
      slides: [
        {
          heading: '場とは、位置ごとに矢印が1本決まる地図だろうか?',
          beat: '基本事項',
          role: '観察',
          figure: 'ume-field-map-grid',
          body: '電場は、点ごとに矢印が1本決まる地図だ。位置を $\\vec r$、その点の電場を $\\vec E(\\vec r)$ と書く。',
          formulaNote: '括弧の中の $\\vec r$ は、値を読む場所を指定する',
        },
        {
          heading: '矢印は、どうすれば計算に持ち込めるだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'ume-e-components',
          body: '成分の組で書けばよい。右へ4、上へ3なら $\\vec E=(4,3)\\,\\mathrm{N/C}$。符号が向きを表す。',
          formula: r`\vec E=(E_x,\;E_y)`,
          formulaNote: '単位はどちらもN/C',
        },
        {
          heading: '一様な電場での仕事は、どんな式だったろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'ume-work-uniform-recall',
          body: '初級では $W=qE\\Delta x$ と書いた。$1\\,\\mathrm C$ が $3\\,\\mathrm{N/C}$ の中を $1\\,\\mathrm m$ 進めば $3\\,\\mathrm J$。単位は N/C×C×m=J。',
          formula: r`W=qE\Delta x`,
          formulaNote: '電場が一様で、進む向きが電場と同じときの式',
        },
        {
          heading: '道が曲がると、どの距離を使えばよいのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'ume-bent-path-question',
          body: '辺ごとに進む向きが違い、電場の向きとも揃っていない。$\\Delta x$ を1つに決められない。',
        },
        {
          heading: '進む向きと長さを、矢印1本にまとめられないだろうか?',
          beat: '解決',
          role: '操作',
          figure: 'ume-delta-r-arrow',
          body: 'i番目の小区間の移動を、矢印 $\\Delta\\vec r_i$ で表す。長さが進んだ距離、向きが進む向きだ。',
          formulaNote: '$\\Delta\\vec r_i$ は「どれだけ・どちらへ」を1本に詰めた矢印',
        },
        {
          heading: '場の値は、区間のどの点のものを使うのだろう?',
          beat: '解決',
          role: '観察',
          figure: 'ume-representative-point',
          body: '代表点 $\\vec r_i$ を1つ決め、そこでの値を区間全体に使う。ここでは中点を代表点にとる。',
          formulaNote: '$\\vec r_i$ は「どこの場の値を使うか」を決める点',
        },
        {
          heading: '電荷が電場から受ける力は、どう書けるだろう?',
          beat: '解決',
          role: '観察',
          figure: 'ume-force-is-qe',
          body: '電場は1 Cあたりの力なので、$q$ を掛けると力になる。$\\vec F=q\\vec E$ で、単位は N/C×C=N。',
          formula: r`\vec F(\vec r_i)=q\,\vec E(\vec r_i)`,
          formulaNote: '仕事の式に入るのは電場ではなく力',
        },
        {
          heading: '力のうち、実際に効くのはどの部分だろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-effective-force',
          body: '効くのは、道の向きに揃った成分だけだ。なす角を $\\theta_i$ として $|\\vec F|\\cos\\theta_i$ になる。',
          formula: r`F_{\parallel}=|\vec F|\cos\theta_i`,
          calculation: [
            { note: '力を、道方向の成分と道に垂直な成分に分ける', tex: r`F_{\parallel}=|\vec F|\cos\theta_i` },
          ],
        },
        {
          heading: '小区間の仕事は、何と何の掛け算になるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-work-piece-cos',
          body: '有効な力に、小移動の長さを掛ける。$\\Delta W_i=(|\\vec F|\\cos\\theta_i)\\,|\\Delta\\vec r_i|$ だ。',
          formula: r`\Delta W_i=\left(|\vec F|\cos\theta_i\right)|\Delta\vec r_i|`,
          calculation: [
            { note: '有効な力に、進んだ長さを掛ける', tex: r`\Delta W_i=\left(|\vec F|\cos\theta_i\right)|\Delta\vec r_i|` },
          ],
        },
        {
          heading: 'この形に、名前を付けてよいのだろうか?',
          beat: '解決',
          role: '操作',
          figure: 'ume-dot-definition',
          body: 'よい。「2本の大きさと、なす角の $\\cos$ の積」を内積と呼び、$\\cdot$ で書く。',
          formula: r`\vec F\cdot\Delta\vec r=|\vec F|\,|\Delta\vec r|\cos\theta`,
          calculation: [
            { note: '大きさと角の積という形に、内積という名前を付ける', tex: r`\vec F\cdot\Delta\vec r=|\vec F|\,|\Delta\vec r|\cos\theta` },
          ],
        },
        {
          heading: '小区間の仕事は、結局どう書けるのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'ume-dot-one-edge',
          body: 'この区間では力が一定で、移動は直線とする。$\\Delta W_i=\\vec F(\\vec r_i)\\cdot\\Delta\\vec r_i$。成分なら $F_x\\Delta x+F_y\\Delta y$ で計算できる。',
          formula: r`\Delta W_i=\vec F(\vec r_i)\cdot\Delta\vec r_i`,
          formulaNote: '力の大きさではなく、道方向の成分×小移動',
        },
        {
          heading: '同じ向きと直角では、値はどう変わるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-perpendicular-zero',
          body: '同じ向きなら $\\cos0^\\circ=1$ で最大の正。直角なら $\\cos90^\\circ=0$ で、仕事は0になる。',
        },
        {
          heading: '逆を向いた区間では、符号はどうなるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-negative-edge',
          body: '$\\cos180^\\circ=-1$ なので負になる。負号は、エネルギーを取り返した側という向きの情報だ。',
        },
        {
          heading: '大きさどうしを掛けるのでは、なぜいけないのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'ume-not-just-product',
          body: '$|\\vec F||\\Delta\\vec r|$ は、2本が揃ったときの最大値だ。内積はそこに $\\cos\\theta$ を掛け、向きの情報を残す。',
          formulaNote: '内積はただの掛け算ではない。向きの関係が入っている',
        },
      ],
      preview: {
        goal: r`W=\int_C\vec F\cdot d\vec r`,
        now: '小区間1つぶんの仕事を、内積で書けること',
        later: '小区間を全部足すこと、区間を限りなく細かくすること',
      },
      leadsTo: ['ue-integrals', 'ue-potential'],
      problems: [
        {
          id: 'p-umle-1',
          difficulty: 1,
          question: '力 $(3,\\;0)\\,\\mathrm N$ の中を、$(0,\\;2)\\,\\mathrm m$ だけ進んだ。この小区間の仕事は?',
          choices: ['$6\\,\\mathrm J$', '$0\\,\\mathrm J$', '$3\\,\\mathrm J$', '$-6\\,\\mathrm J$'],
          answerIndex: 1,
          hint: '2本のなす角は何度か。',
          explanation: '内積は $3\\times0+0\\times2=0$ なので**0 J**。力は横向き、移動は縦向きで直角だから $\\cos90^\\circ=0$ になる。6 Jは大きさ3と長さ2をそのまま掛けた値で、**向きの情報を捨ててしまった誤り**にあたる。',
        },
        {
          id: 'p-umle-2',
          difficulty: 2,
          question: '内積 $\\vec F\\cdot\\Delta\\vec r$ が「ただの掛け算」ではないと言えるのは、なぜ?',
          choices: [
            '答えが必ず負になるから',
            '$|\\vec F||\\Delta\\vec r|$ に $\\cos\\theta$ が掛かり、2本の向きの関係が入るから',
            'ベクトルは掛け算できないから',
            '単位が変わってしまうから',
          ],
          answerIndex: 1,
          hint: '直角のときに0になるのは、どの因子のおかげか。',
          explanation: '$\\vec F\\cdot\\Delta\\vec r=|\\vec F||\\Delta\\vec r|\\cos\\theta$ で、**$\\cos\\theta$ が向きの関係を持ち込む**。だから直角で0、逆向きで負になる。大きさだけの積は、2本が揃ったときの最大値にすぎない。単位は $\\mathrm{N\\cdot m=J}$ のままで変わらない。',
        },
        {
          id: 'p-umle-3',
          difficulty: 2,
          question: '$\\vec F$ と $\\Delta\\vec r$ のなす角が $180^\\circ$ のとき、小区間の仕事は?',
          choices: [
            '正の最大値',
            '$0$',
            '負で、大きさは $|\\vec F||\\Delta\\vec r|$',
            '角度によらず一定',
          ],
          answerIndex: 2,
          hint: '$\\cos180^\\circ$ の値を入れてみる。',
          explanation: '$\\cos180^\\circ=-1$ なので $\\Delta W=-|\\vec F||\\Delta\\vec r|$、つまり**負で大きさは最大**。力が進む向きと真逆なので、エネルギーを取り返す側になる。0になるのは直角($90^\\circ$)のときで、別の場合。',
        },
        {
          id: 'p-umle-4',
          difficulty: 1,
          question: '電場 $\\vec E$ の中に置いた電荷 $q$ が受ける力の単位を確かめると?',
          choices: [
            '$\\mathrm{N/C}\\times\\mathrm C=\\mathrm N$',
            '$\\mathrm{N/C}\\times\\mathrm C=\\mathrm J$',
            '$\\mathrm{N/C}\\times\\mathrm C=\\mathrm V$',
            '$\\mathrm{N/C}\\times\\mathrm C=\\mathrm{Wb}$',
          ],
          answerIndex: 0,
          hint: '電場は「1 Cあたりの力」だった。',
          explanation: '$\\mathrm{N/C}$ に $\\mathrm C$ を掛けると $\\mathrm C$ が約分されて**N**が残る。これが $\\vec F=q\\vec E$ が力である理由。さらに距離 m を掛けると $\\mathrm{N\\cdot m=J}$ で仕事になる。VはJ/C、WbはT·m²で別の量。',
        },
      ],
    },

    // ================= 2. 有限和から線積分へ =================
    {
      id: 'um-line-integral-entry',
      title: '有限和から線積分へ',
      subtitle: 'Σ を ∫ に置き換える',
      enemy: { name: 'リミットリーパー', emoji: '➰', maxHp: 132 },
      theme: '有限和の極限として、線積分の記号を組み上げる',
      goal: r`曲線をN分割した $W_N=\sum\vec F(\vec r_i)\cdot\Delta\vec r_i$ から、$W=\int_C\vec F\cdot d\vec r$ までを順に並べられる。`,
      intro: '小区間1つの仕事は書けた。次は道全体だ。力や電場は場所ごとに変わるので、まとめて掛け算はできない。分けて足し、細かくする。',
      outro: '曲線CをN個の短い直線に分け、代表点の力と小移動の内積を足すと $W_N$。Nを増やすと折れ線が曲線に近づき、値が落ち着く。その極限に付けた名前が $\\int_C$。$\\vec F=q\\vec E$ を入れれば $W=q\\int_C\\vec E\\cdot d\\vec r$ になる。',
      foundation: {
        known: '小区間1つの仕事が、内積 $\\vec F\\cdot\\Delta\\vec r$ で書けること。',
        startingPoint: '曲線をN個の短い直線に分けて、区間ごとの内積を足すところから出発する。',
        conditions: '力や電場は場所ごとに変わってよい。ここでは静電場も電位も前提にしない。',
        example: {
          given: '4つの小区間の仕事が、順に3 J、2 J、0 J、−2 Jだった。',
          tex: r`W_4=\sum_{i=1}^{4}\vec F(\vec r_i)\cdot\Delta\vec r_i=3+2+0-2=3\,\mathrm J`,
          read: '添字iは区間の番号。上端の4が、足した区間の総数を表す。',
        },
      },
      glossary: {
        ...emSymbols,
        W_N: 'N個の小区間を足した仕事の近似値 [J]。Nを増やすと落ち着く',
        F: 'この章では、小区間で物体や電荷にはたらく力 [N]',
      },
      units: [
        { end: 4, goal: '場所ごとに変わる力を、分割して扱う準備をする', gain: 'まとめて掛け算はできない。曲線をN個の短い直線に分け、代表点と小移動を決める。' },
        { end: 7, goal: '有限和を作り、添字と範囲を読む', gain: 'W_N はN個の内積の和。添字iは区間の番号で、上端が区間の総数を表す。' },
        { end: 10, goal: '分割を細かくして、極限に記号を付ける', gain: 'Nを増やすと折れ線が曲線に近づき値が落ち着く。その極限に付けた名前が積分。' },
        { end: 14, goal: '電場の式に直し、Cと向きの意味を確かめる', gain: 'F=qE を入れると電場の式になる。Cは曲線の目印で、逆向きに進むと符号が反転する。' },
      ],
      slides: [
        {
          heading: '小区間1つぶんは、もう書けているだろうか?',
          beat: '基本事項',
          role: '観察',
          figure: 'ume-piece-work-dot',
          body: '力が変わる道では、小区間の力を代表点の値で近似する。$\\Delta W_i\\simeq\\vec F(\\vec r_i)\\cdot\\Delta\\vec r_i$。区間を細かくする極限で、正確な仕事を求める。',
          formula: r`\Delta W_i\simeq\vec F(\vec r_i)\cdot\Delta\vec r_i`,
        },
        {
          heading: '道に沿って力が変わると、何が困るのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'ume-varying-field-path',
          body: '場所ごとに力の大きさも向きも変わる。掛けるべき $\\vec F$ が1つに決まらない。',
        },
        {
          heading: '曲線は、どうやって扱える形にするのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-chop-into-n',
          body: '曲線CをN個の短い直線に分ける。短く切れば、1本ずつはまっすぐな小区間として扱える。',
          formulaNote: '曲線 → 短い直線の集まり。これが最初の一手',
        },
        {
          heading: '各区間で決めるのは、どの2つだろう?',
          beat: '解決',
          role: '観察',
          figure: 'ume-ri-vs-dri',
          body: '代表点 $\\vec r_i$ と、小移動 $\\Delta\\vec r_i$ の2つだ。前者で力を読み、後者で進む量を決める。',
        },
        {
          heading: '道全体の仕事は、どう足し上げるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-sum-n-pieces',
          body: 'N個の内積を全部足す。$W_N=\\sum_{i=1}^{N}\\vec F(\\vec r_i)\\cdot\\Delta\\vec r_i$ となる。',
          formula: r`W_N=\sum_{i=1}^{N}\vec F(\vec r_i)\cdot\Delta\vec r_i`,
          calculation: [
            { note: 'N個の小区間の仕事を、そのまま足し合わせる', tex: r`W_N=\sum_{i=1}^{N}\vec F(\vec r_i)\cdot\Delta\vec r_i` },
          ],
        },
        {
          heading: 'Σの添字 i は、何を数えているのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-sigma-index',
          body: '$i$ は小区間の番号で、下端1から上端Nまで動く。上端が、足した区間の総数だ。',
          formulaNote: '範囲を書かないと、どこまで足したか伝わらない',
        },
        {
          heading: '数値で足すと、どんな計算になるのだろう?',
          beat: '解決',
          role: '観察',
          figure: 'ume-sum-four-edges',
          body: '4区間の仕事が $3,2,0,-2\\,\\mathrm J$ なら、$W_4=3+2+0-2=3\\,\\mathrm J$。0も負も同じように足す。',
          formula: r`W_4=3+2+0-2=3\,\mathrm J`,
        },
        {
          heading: '分割を増やすと、折れ線はどうなるのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'ume-refine-path',
          body: 'ここからは別の滑らかな電場と道で、分割数だけを変えて比較する。N=4、8、16と増やすと折れ線が曲線に近づき、和も一定の値へ近づく。前の3 Jの例とは別の計算だ。',
        },
        {
          heading: 'その落ち着き先は、どう書けばよいのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-limit-of-sum',
          body: '$N\\to\\infty$ の極限で書く。$W=\\lim_{N\\to\\infty}\\sum_{i=1}^{N}\\vec F(\\vec r_i)\\cdot\\Delta\\vec r_i$。',
          formula: r`W=\lim_{N\to\infty}\sum_{i=1}^{N}\vec F(\vec r_i)\cdot\Delta\vec r_i`,
          calculation: [
            { note: '分割を限りなく細かくした先の値をとる', tex: r`W=\lim_{N\to\infty}\sum_{i=1}^{N}\vec F(\vec r_i)\cdot\Delta\vec r_i` },
          ],
        },
        {
          heading: 'この極限に、短い名前を付けられないだろうか?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'ume-line-integral-symbol',
          body: 'この極限を $W=\\int_C\\vec F\\cdot d\\vec r$ と書き、曲線Cに沿った線積分と定義する。',
          formula: r`W=\int_C\vec F\cdot d\vec r`,
          formulaNote: '$d\\vec r$ は各点での接線方向の小移動',
        },
        {
          heading: '電場の式に直すには、何を入れればよいだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-substitute-qe',
          body: '$\\vec F=q\\vec E$ を代入する。$q$ は定数なので、積分の外へ出せる。',
          formula: r`W=q\int_C\vec E\cdot d\vec r`,
          calculation: [
            { note: '力を電場で書き直し、定数qを外に出す', tex: r`W=\int_C q\vec E\cdot d\vec r=q\int_C\vec E\cdot d\vec r` },
          ],
        },
        {
          heading: '記号の下に付いた C は、何を指しているのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-path-label-c',
          body: 'C は積分する範囲が曲線だという目印だ。$\\int_a^b$ のような数直線の端点とは違う。',
          formulaNote: '$\\int_a^b$ は数直線の区間、$\\int_C$ は空間の中の曲線',
        },
        {
          heading: '道を逆向きにたどると、値はどうなるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-direction-of-c',
          body: '$\\Delta\\vec r_i$ が全部逆を向くので、符号が反転する。大きさは同じままだ。',
        },
        {
          heading: 'この値は、道を変えても同じなのだろうか?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'ume-path-dependent',
          body: '一般には同じとは限らない。線積分の値は、両端だけでなく道 C にも依存し得る。',
          formulaNote: '曲線の長さを足しているのではない。向きの関係が毎回入る',
        },
      ],
      preview: {
        goal: r`\mathcal{E}=\oint_C\vec E\cdot d\vec r`,
        now: '有限和から極限へ進み、線積分の記号を読めること',
        later: '閉じた道を一周した値と、それが起電力になる場面',
      },
      leadsTo: ['ue-integrals', 'ue-potential', 'ue-faraday'],
      problems: [
        {
          id: 'p-umli-1',
          difficulty: 2,
          question: '$W_N=\\sum_{i=1}^{N}\\vec F(\\vec r_i)\\cdot\\Delta\\vec r_i$ の添字 $i$ と上端の $N$ は、何を表している?',
          choices: [
            '$i$ は力の番号、$N$ は力の個数',
            '$i$ は小区間の番号、$N$ は分けた小区間の総数',
            '$i$ は座標軸の番号、$N$ は次元の数',
            '$i$ は時刻、$N$ は経過時間',
          ],
          answerIndex: 1,
          hint: '曲線を何に分けたかを思い出す。',
          explanation: '曲線をN個の短い直線に分けたので、**$i$ は小区間の通し番号、上端Nは小区間の総数**を表す。範囲を書かないと、どこまで足したのかが伝わらない。Nを増やすと $\\Delta\\vec r_i$ は短くなる。',
        },
        {
          id: 'p-umli-2',
          difficulty: 2,
          question: '線積分 $\\int_C\\vec F\\cdot d\\vec r$ について、正しい説明はどれ?',
          choices: [
            '曲線 C の長さを足し合わせている',
            '各点で力の道方向の成分を選び、小移動を掛けて足している',
            '力の大きさの最大値を求めている',
            '曲線を囲む面積を求めている',
          ],
          answerIndex: 1,
          hint: '欠片1つの中身は $\\vec F\\cdot\\Delta\\vec r$ だった。',
          explanation: '欠片は $\\vec F(\\vec r_i)\\cdot\\Delta\\vec r_i$ で、**道方向の成分 × 小移動**という中身を持つ。だから力が道と直角なら、いくら長い道でも寄与は0になる。**長さを足しているのではない**点が要注意。面積を求めているのでもない。',
        },
        {
          id: 'p-umli-3',
          difficulty: 2,
          question: '同じ曲線を逆向きにたどると、$\\int_C\\vec F\\cdot d\\vec r$ はどうなる?',
          choices: [
            '同じ値になる',
            '符号が反転し、大きさは同じになる',
            '必ず0になる',
            '2倍になる',
          ],
          answerIndex: 1,
          hint: '$\\Delta\\vec r_i$ の向きがどうなるかを見る。',
          explanation: '逆向きに進むと**すべての $\\Delta\\vec r_i$ が反対を向く**ので、各項の内積の符号が一斉に変わる。大きさはそのままで符号だけ反転する。だから C の指定には、出発点と到着点、つまり進む向きまで要る。',
        },
        {
          id: 'p-umli-4',
          difficulty: 3,
          question: '$\\sum_{i=1}^{N}$ を $\\int_C$ に置き換えるとき、実際に行っている操作はどれ?',
          choices: [
            '$N$ を限りなく増やし、各 $\\Delta\\vec r_i$ を限りなく短くする極限をとった',
            '$N$ を1に固定した',
            '内積を普通の掛け算に置き換えた',
            '曲線をまっすぐな線に置き換えた',
          ],
          answerIndex: 0,
          hint: '記号が変わる前と後で、消えた文字を比べる。',
          explanation: '$\\int$ は**「分割を限りなく細かくした和」に付けた名前**で、極限をとった結果 $N$ も $i$ も記号から消える。内積はそのまま残るので $\\cdot$ は消えない。曲線をまっすぐにしたわけでもない。',
        },
        {
          id: 'p-umli-5',
          difficulty: 2,
          question: '$\\int_C\\vec F\\cdot d\\vec r$ の値について、この段階で言えることは?',
          choices: [
            '両端の点だけで決まり、道にはよらない',
            '一般には、両端だけでなく道 C にも依存し得る',
            'つねに0になる',
            '道が長いほど必ず大きくなる',
          ],
          answerIndex: 1,
          hint: '定義の中に、道の情報がどれだけ入っているかを見る。',
          explanation: '定義には各点の $\\vec F(\\vec r_i)$ と $\\Delta\\vec r_i$ が入っており、**通った道の情報がそのまま値に効く**。だから一般には道に依存し得る。道によらなくなるのは特別な場合で、次の段で静電場のときに確かめる。長さに比例するわけでもない。',
        },
      ],
    },

    // ================= 3. 静電場の電位差 =================
    {
      id: 'um-electrostatic-potential-path',
      title: '静電場の電位差',
      subtitle: '道によらないから位置で決まる',
      enemy: { name: 'ルートツイン', emoji: '🗺️', maxHp: 136 },
      theme: '静電場では線積分が道によらないことを確かめ、電位差を作る',
      goal: r`二経路の仕事が等しいことを計算で確かめ、$V_B-V_A=-\int_A^B\vec E\cdot d\vec r$ の成り立つ条件まで言える。`,
      intro: '線積分の値は、一般には道にも依存し得た。ところが静電場では、道を変えても同じ値になる。この性質があって初めて、位置だけで決まる電位が作れる。',
      outro: '一様な静電場では、二経路の仕事はどちらも24 J。静電場という特別な性質があると、違う道でも合計が同じになる。だから $\\Delta U=-W_{\\mathrm{AB}}$、$\\Delta V=\\Delta U/q$ と進めて、位置だけの電位が作れる。時間変化する磁場があると、この作り方は使えない。',
      foundation: {
        known: '線積分で道に沿った仕事が書けること。内積では、電場と直角に進む区間が寄与しないこと。',
        startingPoint: '同じ2点を結ぶ2本の道について、仕事を実際に計算して見比べるところから出発する。',
        conditions: '電荷の配置が時間で変化しない静電場だけを扱う。磁場が時間変化する場合は別に考える。',
        example: {
          given: '一様な電場(4,0) N/Cの中を、2 Cの電荷がx方向に3 m進む。',
          tex: r`W=2\times(4\times3)=24\,\mathrm J,\qquad \Delta V=-\frac{24}{2}=-12\,\mathrm V`,
          read: '仕事の単位はN/C×C×m=J、電位差はJ/C=V。',
        },
      },
      glossary: {
        ...emSymbols,
        'ΔV': '2点間の電位差 [V]。位置エネルギーの変化を電荷で割った量',
        'ΔU': '電荷の位置エネルギーの変化 [J]。電場のした仕事に負号を付けた量',
      },
      units: [
        { end: 5, goal: '2本の道で仕事を計算し、値を見比べる', gain: 'どちらも24 J。効くのは電場方向に進んだ分だけで、直角な区間は寄与しない。' },
        { end: 10, goal: '位置エネルギーを経て、電位差の式を作る', gain: 'ΔU=−W、ΔV=ΔU/q と一手ずつ進むと、V の差が線積分に負号を付けた形になる。' },
        { end: 13, goal: '単位と読み方、そして使える条件を確かめる', gain: 'J/C=V で、電場の単位はV/mとも書ける。時間変化する磁場があると、この形は置けない。' },
      ],
      slides: [
        {
          heading: '同じ2点を結ぶ道は、1本だけだろうか?',
          beat: '基本事項',
          role: '観察',
          figure: 'ume-two-endpoints',
          body: '何本でもある。一様な電場 $(4,0)\\,\\mathrm{N/C}$ の中で、$2\\,\\mathrm C$ を A(0,0) から B(3,2) m へ運ぶ。',
        },
        {
          heading: '道が違えば、仕事も違ってしまうのだろうか?',
          beat: '疑問',
          role: '問い',
          figure: 'ume-two-paths-compare',
          body: '先に右へ行く道と、先に上がる道を比べる。前の段の話では、違っていてもおかしくない。',
        },
        {
          heading: '先に右へ行く道の仕事は、いくらになるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-path-right-first',
          body: '1区間目は電場と同じ向きで24、2区間目は直角で0。合計 $24\\,\\mathrm J$ になる。',
          calculation: [
            { note: '同じ向きの区間と直角の区間を足す', tex: r`W_{\text{path1}}=2\times(4\times3)+2\times(4\times0)=24\,\mathrm J` },
          ],
        },
        {
          heading: '先に上がる道では、答えはどうなるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-path-up-first',
          body: '1区間目は直角で0、2区間目は同じ向きで24。合計はやはり $24\\,\\mathrm J$ だ。',
          calculation: [
            { note: '順番を入れ替えても、同じ2つを足すことになる', tex: r`W_{\text{path2}}=2\times(4\times0)+2\times(4\times3)=24\,\mathrm J` },
          ],
        },
        {
          heading: 'なぜ2本の道で、同じ値になったのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-x-displacement-only',
          body: '効いたのは x 方向に進んだ分だけ。どちらの道も x 方向には $3\\,\\mathrm m$ 進んでいる。',
        },
        {
          heading: '静電場では、一周するとどうなるのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'ume-loop-zero',
          body: '一周の線積分は0になる。初級で道に沿って足した経験はそのままで、静電場という特別な性質が加わったと読む。',
          formula: r`\oint_C\vec E\cdot d\vec r=0`,
          formulaNote: '静電場（電荷配置が時間変化しない）のときの性質',
        },
        {
          heading: '電場がする仕事は、どう書けるのだったろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-work-ab',
          body: 'A から B まで運ぶ間に電場がする仕事は $W_{\\mathrm{AB}}=q\\int_{\\mathrm A}^{\\mathrm B}\\vec E\\cdot d\\vec r$ だ。',
          formula: r`W_{\mathrm{AB}}=q\int_{\mathrm A}^{\mathrm B}\vec E\cdot d\vec r`,
          calculation: [
            { note: '線積分の式に、電荷qを掛けて仕事にする', tex: r`W_{\mathrm{AB}}=q\int_{\mathrm A}^{\mathrm B}\vec E\cdot d\vec r` },
          ],
        },
        {
          heading: '位置エネルギーは、どれだけ変わるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-energy-change',
          body: '電場が仕事をした分だけ、位置エネルギーは減る。だから $\\Delta U=-W_{\\mathrm{AB}}$ となる。',
          formula: r`\Delta U=-W_{\mathrm{AB}}`,
          calculation: [
            { note: '電場がした仕事の分だけ、位置エネルギーが減る', tex: r`\Delta U=U_{\mathrm B}-U_{\mathrm A}=-W_{\mathrm{AB}}` },
          ],
        },
        {
          heading: '電荷によらない量に、どうすれば直せるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-potential-def',
          body: '電荷で割ればよい。$\\Delta V=\\Delta U/q$ を電位差と定義する。単位は J/C=V。',
          formula: r`\Delta V=\frac{\Delta U}{q}`,
          calculation: [
            { note: '位置エネルギーの変化を、電荷で割って1 Cあたりにする', tex: r`\Delta V=\frac{\Delta U}{q}` },
          ],
        },
        {
          heading: '電位差は、線積分でどう書けるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-potential-formula',
          body: '$\\Delta U=-W_{\\mathrm{AB}}$ と $W_{\\mathrm{AB}}=q\\int\\vec E\\cdot d\\vec r$ を入れると、$q$ が消える。',
          formula: r`V_{\mathrm B}-V_{\mathrm A}=-\int_{\mathrm A}^{\mathrm B}\vec E\cdot d\vec r`,
          calculation: [
            { note: '2つの式を代入すると、電荷qが約分されて消える', tex: r`V_{\mathrm B}-V_{\mathrm A}=-\int_{\mathrm A}^{\mathrm B}\vec E\cdot d\vec r` },
          ],
        },
        {
          heading: '電位差の単位は、電場の単位とどうつながるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-volt-units',
          body: '$\\mathrm{N/C}\\times\\mathrm m=\\mathrm{J/C}=\\mathrm V$。だから電場の単位は V/m とも書ける。',
        },
        {
          heading: '電位は、どんなふうに読めばよいのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-potential-as-height',
          body: '標高として読む。今の例では $-24/2=-12\\,\\mathrm V$ で、B は A より 12 V 低い。',
        },
        {
          heading: 'この作り方が使えないのは、どんなときだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'ume-changing-b-warning',
          body: '磁場が時間変化するときだ。一周の線積分が0でなくなり、位置だけの電位を同じ形では置けない。',
          formulaNote: '上級のファラデーの法則で、この場合を扱う',
        },
      ],
      preview: {
        goal: r`V_{\mathrm B}-V_{\mathrm A}=-\int_{\mathrm A}^{\mathrm B}\vec E\cdot d\vec r`,
        now: '一様な静電場で、2本の道の仕事が等しいことを計算で確かめること',
        later: '一般の静電場でも道によらない理由と、時間変化する磁場でこの話が崩れること',
      },
      leadsTo: ['ue-potential', 'ue-faraday'],
      problems: [
        {
          id: 'p-umep-1',
          difficulty: 2,
          question: '一様な電場 $(4,\\;0)\\,\\mathrm{N/C}$ の中で、$2\\,\\mathrm C$ を A(0,0) から B(3,2) m へ運んだ。2本の道の仕事は?',
          choices: [
            '道によって違う',
            'どちらも $24\\,\\mathrm J$',
            'どちらも $0\\,\\mathrm J$',
            '長い道のほうが大きい',
          ],
          answerIndex: 1,
          hint: '電場と直角に進んだ区間の寄与はいくらだったか。',
          explanation: '効くのは x 方向の移動だけで、どちらの道も x 方向には3 m進む。$2\\times4\\times3=24$ で**どちらも24 J**。道の長さではなく、**電場方向に進んだ分**が値を決める。',
        },
        {
          id: 'p-umep-2',
          difficulty: 3,
          question: '$V_{\\mathrm B}-V_{\\mathrm A}=-\\int_{\\mathrm A}^{\\mathrm B}\\vec E\\cdot d\\vec r$ を「位置だけで決まる量の差」として使えるのは、どんなとき?',
          choices: [
            'どんな場合でも必ず使える',
            '静電場のとき。このとき線積分が道によらず、一周すると0になる',
            '電荷 $q$ が正のときだけ',
            '道がまっすぐなときだけ',
          ],
          answerIndex: 1,
          hint: '道ごとに値が変わる量から、位置だけの量は作れるだろうか。',
          explanation: '道ごとに値が違えば、$V_{\\mathrm B}$ という**位置だけの値**を決められない。静電場では線積分が道によらず一周0になるので、これが作れる。**磁場が時間変化すると一周が0でなくなり、同じ形では置けない**。$q$ の符号や道の形は条件ではない。',
        },
        {
          id: 'p-umep-3',
          difficulty: 2,
          question: '$W_{\\mathrm{AB}}=24\\,\\mathrm J$、$q=2\\,\\mathrm C$ のとき、$\\Delta U$ と $\\Delta V$ は?',
          choices: [
            '$\\Delta U=24\\,\\mathrm J$、$\\Delta V=12\\,\\mathrm V$',
            '$\\Delta U=-24\\,\\mathrm J$、$\\Delta V=-12\\,\\mathrm V$',
            '$\\Delta U=-24\\,\\mathrm J$、$\\Delta V=-48\\,\\mathrm V$',
            '$\\Delta U=48\\,\\mathrm J$、$\\Delta V=24\\,\\mathrm V$',
          ],
          answerIndex: 1,
          hint: '$\\Delta U=-W$、$\\Delta V=\\Delta U/q$ の順に入れる。',
          explanation: '$\\Delta U=-W_{\\mathrm{AB}}=-24\\,\\mathrm J$、$\\Delta V=\\Delta U/q=-24/2=-12\\,\\mathrm V$。**電場が正の仕事をする向きへ進むと、位置エネルギーも電位も下がる**ので負号が付く。割り算を掛け算にすると単位が $\\mathrm{J\\cdot C}$ になり、Vにならない。',
        },
        {
          id: 'p-umep-4',
          difficulty: 1,
          question: '$\\mathrm{N/C}\\times\\mathrm m$ を整理すると、どの単位になる?',
          choices: ['$\\mathrm J$', '$\\mathrm V$', '$\\mathrm C$', '$\\mathrm{Wb}$'],
          answerIndex: 1,
          hint: '$\\mathrm{N\\cdot m}$ をまず J に置き換える。',
          explanation: '$\\mathrm{N/C}\\times\\mathrm m=\\mathrm{N\\cdot m/C}=\\mathrm{J/C}=\\mathrm V$ なので**V**。だから電場の単位は $\\mathrm{V/m}$ とも書ける。J になるのはさらに電荷 C を掛けたとき。Wb は磁束の単位 $\\mathrm{T\\cdot m^2}$ で別の量。',
        },
      ],
    },

    // ================= 4. 面積ベクトル =================
    {
      id: 'um-em-area-vector',
      title: '面積ベクトル',
      subtitle: '磁束の寄与を内積で書く',
      enemy: { name: 'タイルマスター', emoji: '🧱', maxHp: 130 },
      theme: '小タイルの広さと向きを、1本の矢印にまとめる',
      goal: r`$\Delta\vec A_i=\vec n_i\Delta A_i$ を作り、小タイルの寄与を $\Delta\Phi_i=\vec B(\vec r_i)\cdot\Delta\vec A_i$ と書ける。`,
      intro: '道のときは、小区間を矢印 $\\Delta\\vec r_i$ にまとめた。面でも同じことをする。小タイル1枚を、矢印1本で表す方法を作る。',
      outro: '小タイルは面積 $\\Delta A_i$ と単位法線 $\\vec n_i$ の2つで決まる。この2つを掛けた $\\Delta\\vec A_i=\\vec n_i\\Delta A_i$ が向き付き面積。寄与は $\\Delta\\Phi_i=\\vec B(\\vec r_i)\\cdot\\Delta\\vec A_i$ で、法線を反対にすると符号が反転する。',
      foundation: {
        known: '内積が、揃った向きの成分だけを取り出す道具であること。初級で、タイル1枚の磁束を数えたこと。',
        startingPoint: '平らな小タイルは「広さ」と「向き」の2つだけで決まる、というところから出発する。',
        conditions: '小タイルの中では、磁場も法線も一定とみなす。開いた面では、どちら側を表にするかを先に決める。',
        example: {
          given: '0.5 Tの磁場が、面積0.2 m²のタイルを垂直に貫く。',
          tex: r`\Delta\Phi=0.5\times0.2=0.1\,\mathrm{T\cdot m^2}=0.1\,\mathrm{Wb}`,
          read: 'T·m²に付けた別名がWb。垂直なのでcosは1になる。',
        },
      },
      glossary: {
        ...emSymbols,
        'ΔΦ': 'i番目の小タイルを貫く磁束の寄与 [Wb]。正負は法線の向きで決まる',
        B: '磁場（磁束密度）[T]。この章では位置ごとのベクトル',
      },
      units: [
        { end: 4, goal: 'タイルの広さと向きを、別々の記号で押さえる', gain: 'ΔAは面積という正の数、nは大きさ1の単位法線。傾けると貫く量が減る。' },
        { end: 8, goal: '向き付き面積を作り、寄与を内積で書く', gain: 'ΔAベクトルは向きが法線、大きさが面積。寄与はBとの内積1回で書ける。' },
        { end: 10, goal: '符号の決まり方と、曲面での違いを確かめる', gain: '法線を反対にすると符号が反転する。曲面では法線が1枚ごとに違う向きになる。' },
      ],
      slides: [
        {
          heading: '1枚のタイルの磁束は、どう決めたのだったろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'ume-one-tile-flux',
          body: '初級では「垂直に貫く成分 × 面積」と決めた。$0.5\\,\\mathrm T$ と $0.2\\,\\mathrm m^2$ なら $0.1\\,\\mathrm{Wb}$。単位は $\\mathrm{T\\cdot m^2=Wb}$。',
          formulaNote: '$\\mathrm{T\\cdot m^2}$ に付けた別名が $\\mathrm{Wb}$',
        },
        {
          heading: '小タイル1枚を決めるのに、何が要るのだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'ume-tile-two-facts',
          body: '広さと向きの2つだけだ。広さは面積 $\\Delta A_i$ で、単位 $\\mathrm m^2$ の正の数になる。',
        },
        {
          heading: '向きは、どんな矢印で表せばよいのだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'ume-normal-intro',
          body: '面に垂直で大きさ1の矢印、単位法線 $\\vec n_i$ で表す。運ぶのは向きの情報だけだ。',
          formulaNote: '$|\\vec n_i|=1$。広さの情報は $\\Delta A_i$ が持つ',
        },
        {
          heading: '面を傾けると、貫く量はどうなるのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'ume-tile-dot-normal',
          body: '減る。磁場のうち法線に揃った成分だけが貫き、面に沿う成分は1本も貫かないからだ。',
        },
        {
          heading: '貫く成分は、どう取り出せばよいだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-unit-normal-why',
          body: '法線との内積をとる。$|\\vec n_i|=1$ なので $\\vec B\\cdot\\vec n_i$ が垂直成分そのものになる。',
          formula: r`\vec B\cdot\vec n_i=|\vec B|\cos\theta_i`,
          calculation: [
            { note: '大きさ1の法線との内積は、垂直成分そのものになる', tex: r`\vec B\cdot\vec n_i=|\vec B|\,|\vec n_i|\cos\theta_i=|\vec B|\cos\theta_i` },
          ],
        },
        {
          heading: '広さと向きを、1本の矢印にまとめられないだろうか?',
          beat: '解決',
          role: '操作',
          figure: 'ume-combine-into-arrow',
          body: 'まとめられる。向きは法線と同じ、大きさを面積にした矢印を作る。これが向き付き面積だ。',
          formula: r`\Delta\vec A_i=\vec n_i\,\Delta A_i`,
          calculation: [
            { note: '大きさ1の法線に面積を掛け、長さを面積にする', tex: r`\Delta\vec A_i=\vec n_i\,\Delta A_i` },
          ],
        },
        {
          heading: '$\\Delta A$ と $\\Delta\\vec A$ は、何が違うのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-da-vs-vec-da',
          body: '$\\Delta A$ は面積そのもので、向きを持たない正の数。$\\Delta\\vec A$ は向きを持つ矢印で、大きさが $\\Delta A$ だ。',
        },
        {
          heading: '小タイルの寄与は、結局どう書けるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-tile-flux-vector',
          body: '磁場と向き付き面積の内積1回で書ける。$\\Delta\\Phi_i=\\vec B(\\vec r_i)\\cdot\\Delta\\vec A_i$ だ。',
          formula: r`\Delta\Phi_i=\vec B(\vec r_i)\cdot\Delta\vec A_i`,
          calculation: [
            { note: '向き付き面積の定義を戻すと、前の式と同じになる', tex: r`\Delta\Phi_i=\vec B(\vec r_i)\cdot\vec n_i\,\Delta A_i` },
          ],
        },
        {
          heading: '法線を反対向きにとると、値はどうなるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-normal-side-choice',
          body: '符号が反転する。磁場も面もそのままでも、表裏の決め方だけで正負が入れ替わる。',
        },
        {
          heading: '面が曲がっていても、法線は1本で足りるだろうか?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'ume-curved-normals',
          body: '足りない。曲面ではタイルごとに傾きが違うので、法線も1枚ごとに別の向きになる。',
          formulaNote: '$\\vec n$ に添字 $i$ が要る理由がここにある',
        },
      ],
      preview: {
        goal: r`\Phi_B=\int_S\vec B\cdot d\vec A`,
        now: '小タイル1枚の寄与を、向き付き面積との内積で書けること',
        later: '全タイルを足すこと、タイルを限りなく小さくすること',
      },
      leadsTo: ['ue-integrals', 'ue-faraday'],
      problems: [
        {
          id: 'p-umav-1',
          difficulty: 1,
          question: '向き付き面積 $\\Delta\\vec A$ の「向き」と「大きさ」は、それぞれ何を表す?',
          choices: [
            '向きは面に垂直な方向、大きさは面積',
            '向きは面に沿った方向、大きさは周の長さ',
            '向きは磁場の方向、大きさは磁場の強さ',
            '向きは面に垂直な方向、大きさは1',
          ],
          answerIndex: 0,
          hint: 'タイル1枚の情報は「広さ」と「向き」の2つだけだった。',
          explanation: '$\\Delta\\vec A=\\vec n\\Delta A$ なので、**向きは法線と同じ（面に垂直）、大きさは面積 $\\Delta A$** になる。大きさが1なのは単位法線 $\\vec n$ のほうで、別の矢印。面に沿った方向を使うと、貫いていない成分を拾ってしまう。',
        },
        {
          id: 'p-umav-2',
          difficulty: 2,
          question: '磁束を求めるのに、法線ではなく「面に沿う向きの矢印」を使ってしまうと、どうなる?',
          choices: [
            '同じ答えになる',
            '面と平行な成分を拾ってしまい、貫いていない分まで数えることになる',
            '答えが必ず2倍になる',
            '単位が Wb でなくなるだけで、値は正しい',
          ],
          answerIndex: 1,
          hint: '面と平行に走る磁力線は、その面を何本貫くか。',
          explanation: '面に沿って走る磁力線は、その面を**1本も貫かない**。面に沿う矢印との内積をとると、この貫いていない成分を数えてしまう。測りたいのは**垂直成分だけ**なので、必ず法線を使う。傾きが直角の図では、正しくは0になる。',
        },
        {
          id: 'p-umav-3',
          difficulty: 2,
          question: '磁場 $0.5\\,\\mathrm T$、面積 $0.2\\,\\mathrm m^2$、法線と磁場のなす角が $120^\\circ$ のタイルの寄与は? ($\\cos120^\\circ=-0.5$)',
          choices: ['$0.1\\,\\mathrm{Wb}$', '$0.05\\,\\mathrm{Wb}$', '$-0.05\\,\\mathrm{Wb}$', '$0\\,\\mathrm{Wb}$'],
          answerIndex: 2,
          hint: '$\\cos$ が負になると、寄与の符号はどうなるか。',
          explanation: '$0.5\\times(-0.5)\\times0.2=-0.05$ で**−0.05 Wb**。法線が磁場と鈍角をなす、つまり**決めた表の側から裏へ抜けている**ので寄与は負になる。大きさだけを見て $+0.05$ と答えると、貫く向きの情報が落ちる。',
        },
        {
          id: 'p-umav-4',
          difficulty: 2,
          question: '曲がった面の磁束を計算するとき、法線 $\\vec n$ に添字 $i$ を付ける理由は?',
          choices: [
            '面積がタイルごとに違うから',
            '面の傾きがタイルごとに違い、垂直な向きも1枚ごとに変わるから',
            '磁場の単位がタイルごとに変わるから',
            'タイルの枚数を数えるため',
          ],
          answerIndex: 1,
          hint: '平らな面と曲がった面で、何が変わったかを比べる。',
          explanation: '平面ならどのタイルも同じ向きを向くので $\\vec n$ は1本で済むが、**曲面ではタイルごとに傾きが違う**ため、1枚ごとに別の法線が要る。面積の違いは $\\Delta A_i$ の添字が受け持つ。単位はどのタイルでも T のまま変わらない。',
        },
      ],
    },

    // ================= 5. 有限和から面積分へ =================
    {
      id: 'um-surface-integral-entry',
      title: '有限和から面積分へ',
      subtitle: '垂直成分を選んで足す',
      enemy: { name: 'サーフェスシンボル', emoji: '🪟', maxHp: 138 },
      theme: '小タイルの寄与を足し上げ、面積分の記号を組み上げる',
      goal: r`$\Phi_N=\sum\vec B(\vec r_i)\cdot\vec n_i\Delta A_i$ から $\Phi_B=\int_S\vec B\cdot d\vec A$ までを、理由付きで並べられる。`,
      intro: '小タイル1枚の寄与は書けた。次は面全体だ。曲面では法線が1枚ごとに違うので、まとめて掛け算はできない。分けて足し、細かくする。',
      outro: '面SをN枚に分け、各タイルの $\\vec B\\cdot\\vec n_i\\Delta A_i$ を足すと $\\Phi_N$。タイルを限りなく小さくした極限が $\\int_S\\vec B\\cdot d\\vec A$。$dA$ は面積そのもの、$d\\vec A$ は法線を含む向き付き面積。面積を掛ける操作ではなく、垂直成分を選んで足す操作だ。',
      foundation: {
        known: '小タイルの寄与が $\\vec B\\cdot\\vec n_i\\Delta A_i$ と書けること。法線を反転すると符号が反転すること。',
        startingPoint: '面をN枚の小タイルに分け、寄与を足し合わせるところから出発する。',
        conditions: '各タイルの中では磁場も法線も一定とみなす。開いた面では、表にする側を先に決めておく。',
        example: {
          given: '寄与が0.1 Wb、0.05 Wb、0 Wb、−0.05 Wbの4枚を足す。',
          tex: r`\Phi_4=\sum_{i=1}^{4}\vec B(\vec r_i)\cdot\vec n_i\,\Delta A_i=0.1\,\mathrm{Wb}`,
          read: '負の寄与は引き算になる。足す枚数は添字の上端が表す。',
        },
      },
      glossary: {
        ...emSymbols,
        Phi_N: 'N枚のタイルを足した磁束の近似値 [Wb]。Nを増やすと落ち着く',
        'dA_ベクトル': '向き付き面積を限りなく小さくしたもの。法線の情報を含む',
      },
      units: [
        { end: 3, goal: '平面と曲面を比べ、有限和を作る', gain: '平面なら全部同じ値だが、曲面では1枚ごとに違う。だから和にして足し上げる。' },
        { end: 6, goal: '極限をとり、面積分の記号と S の意味を受け取る', gain: 'タイルを限りなく小さくした極限が∫S。Sは面全体を指す名札で、Cの面版にあたる。' },
        { end: 10, goal: '記号の区別と、操作の中身を言い切る', gain: 'dAは面積、dAベクトルは向き付き。面積を掛けるのではなく、垂直成分を選んで足す。' },
      ],
      slides: [
        {
          heading: '平らな面では、4枚の寄与はどうなるだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'ume-flat-tiles-sum',
          body: '法線が全部同じ向きで磁場と平行なら、各枚 $0.1\\,\\mathrm{Wb}$。4枚で $0.4\\,\\mathrm{Wb}$ になる。',
        },
        {
          heading: '曲がった面では、1枚ずつどう変わるのだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'ume-curved-each-tile',
          body: '法線と磁場のなす角が $0^\\circ,60^\\circ,90^\\circ,120^\\circ$ なら、寄与は $0.1,0.05,0,-0.05\\,\\mathrm{Wb}$。',
        },
        {
          heading: '面全体の磁束は、どう足し上げるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-curved-tiles-sum',
          body: 'N枚の寄与を全部足す。$\\Phi_N=\\sum_{i=1}^{N}\\vec B(\\vec r_i)\\cdot\\vec n_i\\Delta A_i$ となる。',
          formula: r`\Phi_N=\sum_{i=1}^{N}\vec B(\vec r_i)\cdot\vec n_i\,\Delta A_i`,
          calculation: [
            { note: 'N枚の小タイルの寄与を、そのまま足し合わせる', tex: r`\Phi_N=\sum_{i=1}^{N}\vec B(\vec r_i)\cdot\vec n_i\,\Delta A_i` },
          ],
        },
        {
          heading: 'タイルの枚数を増やすと、何が起きるのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'ume-sum-tiles-n',
          body: '1枚あたりが小さくなり、タイルを平らとみなす無理が減る。合計はある値へ落ち着く。',
        },
        {
          heading: 'その落ち着き先には、どんな記号を使うのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'ume-surface-integral-symbol',
          body: '$\\Phi_B=\\int_S\\vec B\\cdot d\\vec A$ と書き、面Sの上の面積分と定義する。',
          formula: r`\Phi_B=\int_S\vec B\cdot d\vec A`,
          formulaNote: 'タイルを限りなく小さくした極限に付けた名前',
        },
        {
          heading: '記号の下の S は、C と何が違うのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-c-vs-s',
          body: 'C は1次元の曲線で、足す相手は $\\Delta\\vec r_i$。S は2次元の面全体で、足す相手は $\\Delta\\vec A_i$ だ。',
        },
        {
          heading: '$dA$ と $d\\vec A$ は、どう区別するのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-da-limit',
          body: '$dA$ は面積そのもので向きを持たない。$d\\vec A$ は法線を含む向き付き面積で、矢印が付く。',
        },
        {
          heading: '面積分は、面積を掛ける操作なのだろうか?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-not-area-times',
          body: '違う。各タイルで垂直成分を選び、面積を掛けて足す操作だ。面に沿う成分は捨てている。',
          formulaNote: '法線を反転すれば、全部の符号がまとめて反転する',
        },
        {
          heading: '丸の付いた積分記号は、どう使い分けるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-oint-vs-oiint',
          body: '閉じた道の一周は $\\oint_C$、閉じた面の全体は $\\oiint_S$。輪が1本か2本かで区別する。',
          formula: r`\oint_C\vec E\cdot d\vec r,\qquad \oiint_S\vec B\cdot d\vec A`,
        },
        {
          heading: '閉じていない面に、$\\oiint$ を使ってよいのだろうか?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'ume-open-vs-closed-surface',
          body: 'いけない。$\\oiint$ は袋のように閉じた面だけの記号だ。開いた面なら $\\int_S$ と書く。',
          formulaNote: '$\\oiint$ は、外向き法線という約束まで一緒に持ち込む',
        },
      ],
      preview: {
        goal: r`\oiint_S\vec B\cdot d\vec A=0`,
        now: 'タイルの和から極限へ進み、面積分の記号を読めること',
        later: '閉じた面での合計がいつも0になること、つまり磁気の湧き出しがないこと',
      },
      leadsTo: ['ue-integrals', 'ue-gauss', 'ue-faraday'],
      problems: [
        {
          id: 'p-umsi-1',
          difficulty: 2,
          question: '面積分 $\\int_S\\vec B\\cdot d\\vec A$ について、正しい説明はどれ?',
          choices: [
            '面積 $S$ に磁場を掛けているだけ',
            '各タイルで法線方向の成分を選び、面積を掛けて足している',
            '面の周の長さを足している',
            '磁場の最大値を求めている',
          ],
          answerIndex: 1,
          hint: '欠片1つの中身は $\\vec B\\cdot\\vec n_i\\Delta A_i$ だった。',
          explanation: '欠片は $\\vec B(\\vec r_i)\\cdot\\vec n_i\\Delta A_i$ で、**垂直成分 × 面積**という中身を持つ。面に沿う成分は捨てられるので、**面積を掛けるだけの操作ではない**。磁場が面と平行なら、どれだけ面積が広くても0になる。',
        },
        {
          id: 'p-umsi-2',
          difficulty: 2,
          question: '$\\Phi_N=\\sum_{i=1}^{N}\\vec B(\\vec r_i)\\cdot\\vec n_i\\Delta A_i$ で、$N$ を大きくすると何が起きる?',
          choices: [
            'タイル1枚が小さくなり、値がある1つの数へ落ち着く',
            '合計が限りなく大きくなる',
            '合計が0に近づく',
            '$\\Delta A_i$ が大きくなる',
          ],
          answerIndex: 0,
          hint: '同じ面を何枚に分けるかを考える。',
          explanation: '同じ面を $N$ 枚に分けるので、**$N$ が増えれば $\\Delta A_i$ は小さくなる**。1枚の中で磁場と法線を一定とみなす無理が減り、合計はある値へ落ち着く。この落ち着き先に付けた名前が $\\int_S\\vec B\\cdot d\\vec A$ で、0にも無限大にもならない。',
        },
        {
          id: 'p-umsi-3',
          difficulty: 2,
          question: '$\\oint$ と $\\oiint$ の使い分けとして正しいのは?',
          choices: [
            'どちらも同じで、好きなほうを使ってよい',
            '$\\oint$ は閉じた道を一周するとき、$\\oiint$ は閉じた面の全体を足すとき',
            '$\\oint$ は電場、$\\oiint$ は磁場のときに使う',
            '$\\oiint$ は積分を2回行うという意味',
          ],
          answerIndex: 1,
          hint: '積分記号の下に付く名札が C か S かを見る。',
          explanation: '輪が1本の $\\oint_C$ は**閉じた道**、輪が2本の $\\oiint_S$ は**閉じた面**の印。場が電場か磁場かとは無関係で、$\\oint_C\\vec B\\cdot d\\vec r$ も $\\oiint_S\\vec E\\cdot d\\vec A$ も書ける。**開いた面に $\\oiint$ を使ってはいけない**点が要注意。',
        },
        {
          id: 'p-umsi-4',
          difficulty: 3,
          question: '開いた面（袋になっていない面）の磁束を $\\oiint_S\\vec B\\cdot d\\vec A$ と書くのは、なぜ誤りか?',
          choices: [
            '開いた面には面積がないから',
            '$\\oiint$ は閉じた面専用の記号で、外向き法線という約束まで持ち込んでしまうから',
            '開いた面では磁束が必ず0になるから',
            '$\\oiint$ は電場にしか使えないから',
          ],
          answerIndex: 1,
          hint: '記号が持ち込む「約束」は何だったか。',
          explanation: '$\\oiint$ は**面が閉じていることの印**で、法線は外向きという約束が自動的に付く。開いた面には内外の区別がないので、その約束を置けない。正しくは $\\int_S$ と書き、**どちら側を表にするかを自分で宣言**する。開いた面の磁束が0とは限らない。',
        },
        {
          id: 'p-umsi-5',
          difficulty: 1,
          question: '$dA$ と $d\\vec A$ の違いとして正しいのは?',
          choices: [
            '同じ量で、書き方が違うだけ',
            '$dA$ は面積そのもの、$d\\vec A$ は法線を含む向き付き面積',
            '$dA$ のほうが必ず大きい',
            '$d\\vec A$ の大きさは常に1',
          ],
          answerIndex: 1,
          hint: '矢印が付いているかどうかで、持っている情報が違う。',
          explanation: '$dA$ は**単位 $\\mathrm m^2$ の正の数**で向きを持たない。$d\\vec A=\\vec n\\,dA$ は**法線の向きも持つ矢印**で、その大きさが $dA$ に等しい。同じ量ではないので書き分けを省略できない。大きさが1なのは単位法線のほう。',
        },
      ],
    },

    // ================= 6. 閉曲面の電気束 =================
    {
      id: 'um-closed-electric-flux',
      title: '閉曲面の電気束',
      subtitle: '束0でも場は0でない',
      enemy: { name: 'ボックスガーディアン', emoji: '📦', maxHp: 140 },
      theme: '閉じた箱の各面の寄与を並べ、正味の出入りを読む',
      goal: r`一様な電場に置いた箱で $\oiint_S\vec E\cdot d\vec A=0$ を計算で示し、$\vec E$ が0でないことを言える。`,
      intro: '閉じた面では法線を外向きにそろえる。すると、出ていく電場が正、入ってくる電場が負になる。箱の6面を1つずつ数えて、その合計が何を意味するのかを確かめる。',
      outro: '外向き法線にそろえると、入る束が負、出る束が正。一様な電場の箱では $-2$ と $+2$ が相殺して合計は0。だが箱の中の電場は $5\\,\\mathrm{N/C}$ のままだ。合計0は「入った分がそのまま出た」という意味で、場が0という意味ではない。',
      foundation: {
        known: '面積分が、タイルごとの内積の和で書けること。法線を反転すると符号が反転すること。',
        startingPoint: '閉じた箱の6面について、寄与を1面ずつ計算して並べるところから出発する。',
        conditions: '電場は一様で時間変化しないとする。箱の面は、電場に対して垂直か平行のどちらかにとる。',
        example: {
          given: '一様な電場5 N/C。外向き法線が電場と同じ向きの面で、面積は0.4 m²。',
          tex: r`\Delta\Phi=5\times0.4=2\,\mathrm{N\cdot m^2/C}`,
          read: '外向き法線と電場が同じ向きなので正。反対側の面では同じ大きさで負になる。',
        },
      },
      glossary: {
        ...emSymbols,
        Phi_E: '電気束。電場の面積分で、単位はN·m²/C。磁束Φとは別の量',
        'ΔΦ': '1つの面が受け持つ束の寄与。閉曲面では外向きを正とする',
      },
      units: [
        { end: 2, goal: '外向き法線の約束を決め、場の中に箱を置く', gain: '閉曲面の法線は外向きにそろえる。出ていく束が正、入ってくる束が負になる。' },
        { end: 6, goal: '6面の寄与を1面ずつ計算して足す', gain: '同じ電場でも法線の向きで符号が変わる。直角な面は0で、合計は0になる。' },
        { end: 8, goal: '合計0の意味を、場が0であることと区別する', gain: '合計0は正味の出入りが0という意味。箱の中の電場は5 N/Cのままで0ではない。' },
      ],
      slides: [
        {
          heading: '閉じた面では、法線をどちら向きにとるのだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'ume-closed-outward-normals',
          body: '外向きと約束する。袋の外へ出る向きだ。この約束で、出る束が正、入る束が負と決まる。',
          formulaNote: '閉じた面には $\\oiint$ を使う',
        },
        {
          heading: '一様な電場の中に、箱を1つ置いてみよう',
          beat: '基本事項',
          role: '観察',
          figure: 'ume-box-in-uniform-field',
          body: '電場は $(5,0)\\,\\mathrm{N/C}$ でどこでも同じ。左右2面の面積はどちらも $0.4\\,\\mathrm m^2$ とする。',
        },
        {
          heading: '電場が入ってくる面の寄与は、いくつだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-box-left-face',
          body: '左の面の外向き法線は $(-1,0)$。内積は $-5$ で、寄与は $-2\\,\\mathrm{N\\cdot m^2/C}$ になる。',
          calculation: [
            { note: '外向き法線と電場の内積に、面積を掛ける', tex: r`\Delta\Phi_{\text{left}}=(5\times(-1))\times0.4=-2\,\mathrm{N\cdot m^2/C}` },
          ],
        },
        {
          heading: '電場が出ていく面では、符号はどうなるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-box-right-face',
          body: '右の面の外向き法線は $(+1,0)$。内積は $+5$ で、寄与は $+2\\,\\mathrm{N\\cdot m^2/C}$ だ。',
          calculation: [
            { note: 'こちらの外向き法線は電場と同じ向きなので正になる', tex: r`\Delta\Phi_{\text{right}}=(5\times1)\times0.4=2\,\mathrm{N\cdot m^2/C}` },
          ],
        },
        {
          heading: '残りの4面の寄与は、どうなるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-box-side-faces',
          body: '上下と前後の面では、外向き法線が電場と直角になる。内積が0なので、寄与も0だ。',
          calculation: [
            { note: '法線が電場と直角なので、内積が0になる', tex: r`\Delta\Phi_{\text{side}}=(5\times0)\times0.4=0\,\mathrm{N\cdot m^2/C}` },
          ],
        },
        {
          heading: '6面を全部足すと、いくつになるのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'ume-box-total-zero',
          body: '$-2+2+0+0+0+0=0$。閉じた面を出入りする電気束の合計は0になる。',
          formula: r`\oiint_S\vec E\cdot d\vec A=0`,
          formulaNote: '入った分が、そのまま出ていったという意味',
        },
        {
          heading: '合計が0なら、箱の中の電場も0なのだろうか?',
          beat: '疑問',
          role: '問い',
          figure: 'ume-zero-flux-nonzero-field',
          body: '違う。箱の中でも電場はずっと $5\\,\\mathrm{N/C}$ のままだ。0になったのは出入りの差でしかない。',
        },
        {
          heading: '閉曲面の合計は、結局なにを表しているのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'ume-net-outflow-meaning',
          body: '正味の出入りだけだ。左面で入った分を右面で返しているので0になった。場の値は別の話。',
          formulaNote: '図の入出が相殺することが、0になった理由のすべて',
        },
      ],
      preview: {
        goal: r`\oiint_S\vec E\cdot d\vec A=\frac{Q_{\text{in}}}{\varepsilon_0}`,
        now: '一様な電場の箱で、各面の寄与を足して0になることを確かめること',
        later: '袋の中に電荷があるときの値と、そこから電場そのものを取り出す方法',
      },
      leadsTo: ['ue-gauss', 'ue-integrals'],
      problems: [
        {
          id: 'p-umecf-1',
          difficulty: 2,
          question: '一様な電場の中に置いた箱で $\\oiint_S\\vec E\\cdot d\\vec A=0$ になった。このとき箱の中の電場は?',
          choices: [
            'どこでも0である',
            '0とは限らない。この例では $5\\,\\mathrm{N/C}$ のまま',
            '面の近くだけ0になる',
            '電場は定義できない',
          ],
          answerIndex: 1,
          hint: '0になったのは、何と何が相殺した結果だったか。',
          explanation: '合計0は、左面の $-2$ と右面の $+2$ が**相殺しただけ**で、正味の出入りが0という意味しかない。箱の中の電場は $5\\,\\mathrm{N/C}$ で0ではない。**閉曲面を通る正味の電気束が0でも、その場所の電場がどこでも0とは限らない**。',
        },
        {
          id: 'p-umecf-2',
          difficulty: 2,
          question: '一様な電場 $(5,\\;0)\\,\\mathrm{N/C}$ の中の箱で、外向き法線が $(-1,\\;0)$ の面（面積 $0.4\\,\\mathrm m^2$）の寄与は?',
          choices: [
            '$+2\\,\\mathrm{N\\cdot m^2/C}$',
            '$-2\\,\\mathrm{N\\cdot m^2/C}$',
            '$0\\,\\mathrm{N\\cdot m^2/C}$',
            '$+5\\,\\mathrm{N\\cdot m^2/C}$',
          ],
          answerIndex: 1,
          hint: '外向き法線と電場が、同じ側を向いているか反対側かを見る。',
          explanation: '$\\vec E\\cdot\\vec n=5\\times(-1)=-5$ に面積0.4を掛けて**−2 N·m²/C**。外向き法線と電場が反対を向くので、**電場が箱へ入ってくる面**にあたり寄与は負。大きさだけを見て $+2$ とすると、出入りの向きの情報が消える。',
        },
        {
          id: 'p-umecf-3',
          difficulty: 2,
          question: '閉曲面の法線を、外向きではなく全部内向きにとって計算すると、合計はどうなる?',
          choices: [
            '同じ値になる',
            '符号が反転する',
            '必ず0になる',
            '2倍になる',
          ],
          answerIndex: 1,
          hint: 'すべての $\\vec n_i$ が反転すると、各項の内積はどうなるか。',
          explanation: 'すべての法線が反転するので、**各面の内積の符号が一斉に変わり、合計も符号が反転する**。だから閉曲面では「外向き」と約束を決めておく必要がある。この例では合計が元々0なので数値は同じに見えるが、一般には別の値になる。',
        },
        {
          id: 'p-umecf-4',
          difficulty: 1,
          question: '電気束の単位 $\\mathrm{N\\cdot m^2/C}$ は、どの掛け算から出てくる?',
          choices: [
            '$\\mathrm{N/C}\\times\\mathrm m^2$',
            '$\\mathrm N\\times\\mathrm{m/C}$',
            '$\\mathrm T\\times\\mathrm m^2$',
            '$\\mathrm{J/C}\\times\\mathrm m$',
          ],
          answerIndex: 0,
          hint: '束は「垂直成分 × 面積」だった。',
          explanation: '電場の単位 $\\mathrm{N/C}$ に面積 $\\mathrm m^2$ を掛けて**$\\mathrm{N\\cdot m^2/C}$**。単位法線は大きさ1で無次元なので、単位を増やさない。$\\mathrm{T\\times m^2=Wb}$ は磁束の単位で、電気束とは別の量になる。',
        },
      ],
    },

    // ================= 7. 中心の点電荷と球面 =================
    {
      id: 'um-gauss-sphere-preview',
      title: '中心の点電荷と球面',
      subtitle: '和が掛け算に退化するとき',
      enemy: { name: 'シンメトリースフィア', emoji: '🔮', maxHp: 145 },
      theme: '球対称のとき、面積分が掛け算1回に退化する仕組みを見る',
      goal: r`球面上で $\vec E$ が法線と平行かつ大きさ一定なので $\oiint_S\vec E\cdot d\vec A=E(4\pi r^2)$ と書けることを説明できる。`,
      intro: '閉じた面の束を数える道具はそろった。最後に、面の選び方しだいで和が掛け算1回に退化する場面を見る。上級で電場を取り出すとき、この一手が要になる。',
      outro: '中心球では電場と法線が平行で、電場の大きさも一定。クーロンの法則の電場に球面積を掛けると、電気束は $Q/\\varepsilon_0$ になる。中心がずれた球や任意形状の面でも同じになることは、上級で別に示す。',
      foundation: {
        known: '閉じた面では外向き法線をとること。面積分が、タイルごとの内積の和であること。',
        startingPoint: '点電荷を中心とする球面の上で、電場と法線の関係を1枚ずつ確かめるところから出発する。',
        conditions: '電荷は1個の点電荷で、球面の中心に置く。中心からずれていると、この書き換えはできない。',
        example: {
          given: '半径2 mの球面上で、電場の大きさが3 N/C、外向き法線と平行。',
          tex: r`\oiint_S\vec E\cdot d\vec A=3\times4\pi\times2^2=48\pi\,\mathrm{N\cdot m^2/C}`,
          read: '全タイルでcosが1、Eも同じ値だから、和が面積との掛け算になる。',
        },
      },
      glossary: {
        ...emSymbols,
        Phi_E: '電気束。電場の面積分で、単位はN·m²/C',
        Q: 'この章では、閉じた面の内側にある電荷の合計 [C]',
      },
      units: [
        { end: 2, goal: '点電荷の場を読み、閉じた面として球面を選ぶ', gain: '点電荷の電場は半径方向。球面はその対称性に合わせた面の選び方になる。' },
        { end: 6, goal: '平行と等しさを使って、和を掛け算に退化させる', gain: '全タイルでcosが1、Eも同じ。だからEを外へ出せて、残りは球の表面積4πr²。' },
        { end: 10, goal: '中心球の電気束を求め、まだ示していない範囲を区別する', gain: 'クーロンの法則から中心球でQ/ε₀を得た。任意の閉曲面でも同じになる証明は上級で行う。' },
      ],
      slides: [
        {
          heading: '点電荷のまわりの電場は、どんな形をしているだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'ume-point-charge-radial',
          body: '正の点電荷 $Q$ のまわりでは、電場はどの向きにも半径方向、外向きにまっすぐ出る。',
        },
        {
          heading: '閉じた面として、どんな形を選ぶとよいだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'ume-sphere-choice',
          body: '電荷を中心とする半径 $r$ の球面をとる。外向き法線も、中心から外への半径方向になる。',
        },
        {
          heading: '球面上では、電場と法線はどう並ぶのだろう?',
          beat: '解決',
          role: '観察',
          figure: 'ume-e-parallel-normal',
          body: 'どのタイルでも2本とも半径方向なので、平行だ。だから $\\vec E\\cdot\\vec n_i=E$ になる。',
          formula: r`\vec E\cdot\vec n_i=E\cos 0^\circ=E`,
        },
        {
          heading: '電場の大きさは、タイルごとに違うのだろうか?',
          beat: '解決',
          role: '観察',
          figure: 'ume-same-magnitude',
          body: '違わない。球面上の点はどれも中心から同じ距離 $r$ にあるので、$E$ はどこでも同じ値だ。',
        },
        {
          heading: '同じ値なら、和のどこを簡単にできるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'ume-factor-out-e',
          body: 'どのタイルの寄与も $E\\,\\Delta A_i$ なので、共通の $E$ を面積分の外へ出せる。',
          formula: r`\oiint_S\vec E\cdot d\vec A=E\oiint_S dA`,
          calculation: [
            { note: 'Eが全タイルで同じ値なので、面積分の外へ出せる', tex: r`\oiint_S\vec E\cdot d\vec A=E\oiint_S dA` },
          ],
        },
        {
          heading: '残った面積の合計は、いくつになるのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'ume-sphere-area-sum',
          body: '球の表面積 $4\\pi r^2$ だ。したがって $\\oiint_S\\vec E\\cdot d\\vec A=E(4\\pi r^2)$ と書ける。',
          formula: r`\oiint_S\vec E\cdot d\vec A=E(4\pi r^2)`,
          calculation: [
            { note: '残った面積の合計は、球の表面積そのもの', tex: r`E\oiint_S dA=E(4\pi r^2)` },
          ],
        },
        {
          heading: 'これで、ガウスの法則を証明したことになるだろうか?',
          beat: '疑問',
          role: '問い',
          figure: 'ume-not-a-proof',
          body: 'なっていない。示したのは左辺の書き換えだけで、右辺が何になるかはまだ出ていない。',
        },
        {
          heading: '対称性は、法則が成り立つための条件なのだろうか?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-symmetry-not-condition',
          body: '違う。ガウスの法則は任意の閉曲面で成り立つ。球・円筒・平面でしか使えないわけではない。',
          formulaNote: '対称性は、計算を楽にする条件にすぎない',
        },
        {
          heading: 'この一手が使えないのは、どんな場合だろう?',
          beat: '解決',
          role: '解釈',
          figure: 'ume-gauss-preview',
          body: '電荷が中心からずれた球や、いびつな面だ。$E$ がタイルごとに違い、外へ出せなくなる。',
          formulaNote: 'ずれた球では面を取り替えず、各点の内積をそのまま積分する',
        },
        {
          heading: '中心球の電気束は、クーロンの法則からいくらになる？',
          beat: '新しい基本事項',role: '固定',figure: 'gauss-sphere',
          body: '出発点はクーロンの法則。球の中心に点電荷Qを置く場合だけ計算する。電場の逆二乗と球面積の二乗が打ち消し合い、電気束は半径によらなくなる。一般の面の証明はまだ残っている。',
          formula: r`\Phi_E=\frac{Q}{\varepsilon_0}`,
          calculation: [
            {note:'クーロンの法則で中心の点電荷が作る電場を与える',tex:r`E=\frac{Q}{4\pi\varepsilon_0r^2}\quad(Q>0)`},
            {note:'中心球では電場と外向き法線が平行。全面積を掛ける',tex:r`\Phi_E=\frac{Q}{4\pi\varepsilon_0r^2}\,4\pi r^2`},
            {note:'共通の4πr²を約分。任意の面の証明とは区別する',tex:r`\Phi_E=\frac{Q}{\varepsilon_0}`},
          ],
        },
      ],
      preview: {
        goal: r`\oiint_S\vec E\cdot d\vec A=\frac{Q_{\text{in}}}{\varepsilon_0}`,
        now: '中心球に限って、クーロンの法則から電気束 $Q/\\varepsilon_0$ を計算できること',
        later: '中心がずれた球を積分し、任意の閉曲面でも内部の正味の電荷だけで決まると示すこと',
      },
      leadsTo: ['ue-gauss', 'ue-integrals'],
      problems: [
        {
          id: 'p-umgs-1',
          difficulty: 2,
          question: '中心に点電荷を置いた球面で $\\oiint_S\\vec E\\cdot d\\vec A=E(4\\pi r^2)$ と書けるのは、どんな性質のおかげ?',
          choices: [
            '球面の面積が $4\\pi r^2$ だから、それだけで十分',
            '全タイルで電場が法線と平行で、しかも大きさが等しいから',
            '電場が0だから',
            '球面が閉じているから',
          ],
          answerIndex: 1,
          hint: '$E$ を面積分の外へ出すには、何が同じである必要があるか。',
          explanation: '$E$ を外へ出すには、**全タイルで $\\vec E\\cdot\\vec n_i$ が同じ値**である必要がある。球面ではどちらも半径方向で平行（$\\cos0^\\circ=1$）、大きさも等しいので成り立つ。面積の式や「閉じている」ことだけでは、$E$ を外に出す理由にならない。',
        },
        {
          id: 'p-umgs-2',
          difficulty: 3,
          question: 'ガウスの法則と対称性の関係として正しいのは?',
          choices: [
            '球・円筒・平面のときしか成り立たない',
            '法則は任意の閉曲面で成り立つ。対称性は計算を楽にする条件',
            '対称性があると法則の右辺が変わる',
            '対称性は法則とも計算とも無関係',
          ],
          answerIndex: 1,
          hint: '「成り立つかどうか」と「$E$ が求まるかどうか」を分けて考える。',
          explanation: 'ガウスの法則は**いびつな閉曲面でも成り立つ**。ただし一般の面では $\\vec E\\cdot\\vec n$ がタイルごとに違うので、積分の値が分かっても**その場所の $E$ を取り出せない**。対称性は取り出せるようにするための条件で、法則の成立条件ではない。',
        },
        {
          id: 'p-umgs-3',
          difficulty: 2,
          question: '点電荷を球の中心からずらして置くと、$\\oiint\\vec E\\cdot d\\vec A=E(4\\pi r^2)$ という書き換えはどうなる?',
          choices: [
            'そのまま使える',
            '使えない。球面上で $E$ が場所ごとに違い、法線とも平行でなくなるから',
            '面積が $4\\pi r^2$ でなくなるから使えない',
            '積分の値そのものが0になる',
          ],
          answerIndex: 1,
          hint: '中心からずれると、球面上の各点までの距離はどうなるか。',
          explanation: '中心がずれると球面上の各点までの距離が変わるので、**$E$ が場所ごとに違い、向きも法線と平行でなくなる**。すると $E$ を外へ出せない。球の面積は $4\\pi r^2$ のままで、積分の値も0にはならない（中に電荷があるため）。',
        },
        {
          id: 'p-umgs-4',
          difficulty: 1,
          question: '半径 $2\\,\\mathrm m$ の球面上で電場の大きさが $3\\,\\mathrm{N/C}$、外向き法線と平行のとき、$\\oiint\\vec E\\cdot d\\vec A$ は?',
          choices: [
            '$48\\pi\\,\\mathrm{N\\cdot m^2/C}$',
            '$12\\pi\\,\\mathrm{N\\cdot m^2/C}$',
            '$0\\,\\mathrm{N\\cdot m^2/C}$',
            '$3\\,\\mathrm{N\\cdot m^2/C}$',
          ],
          answerIndex: 0,
          hint: '$E$ を外に出し、残った面積の合計を球の表面積に置き換える。',
          explanation: '$E(4\\pi r^2)=3\\times4\\pi\\times2^2=48\\pi$ で**$48\\pi\\,\\mathrm{N\\cdot m^2/C}$**。$12\\pi$ は $r^2$ を $r$ と書き違えた値、0は一様な電場の箱のときの答え。単位は $\\mathrm{N/C}\\times\\mathrm m^2$ から出る。',
        },
      ],
    },
  ],
};
