import type { LevelChapter } from './schema';
import { r } from './schema';

/** 数学の武器庫・中級 — 記号とグラフで、変化を式にする。
 * 初級で図として身につけた「平均から瞬間へ」「値×幅の和」「効く成分」を、
 * ここで Σ・∫・内積・面積ベクトル・変化率の式という記号へ移す。
 * 複雑な積分計算と微分方程式の解法は上級へ渡す。 */
export const um_math: LevelChapter = {
  id: 'um-math',
  title: '数学の武器庫',
  subtitle: '記号とグラフで、変化を式にする',
  familyId: 'umath',
  level: 'middle',
  stages: [
    // ================= 平均変化率から微分へ =================
    {
      id: 'um-average-rate',
      title: '平均変化率から微分へ',
      subtitle: '差商を展開して h を 0 へ',
      enemy: { name: 'サショウワーム', emoji: '🪱', maxHp: 130 },
      theme: '平均の変化率を縮めて、瞬間の変化率を作る',
      goal: r`差商 $\frac{(t+h)^2-t^2}{h}$ を展開して $2t+h$ に直し、$h\to0$ の行き先として $\frac{dx}{dt}=2t$ を書けるようになる。`,
      intro: '初級では、区間を短くすると平均が瞬間に近づくことを図で確かめた。ここでは同じ操作を文字で行う。差の割り算を $h$ の式に直せば、行き先が目で見えるようになる。',
      outro: '平均変化率は $\\frac{\\Delta x}{\\Delta t}$、その行き先が $\\frac{dx}{dt}$。$x=t^2$ なら差商は $2t+h$ で、$h\\to0$ とすると $2t$ が残る。0で割ったのではなく、0に近づけた先を見ている。',
      foundation: {
        known: '割り算で平均の速さを出せること。グラフ上の2点を結ぶ直線の傾きが、縦の差÷横の差であること。',
        startingPoint: '区間の幅を h と書き、平均の変化率を h の式として作るところから出発する。',
        conditions: 'ここで扱うのは切れ目なくつながったなめらかな関数だけ。h は 0 ではない実数とし、正でも負でもよい。',
        example: {
          given: 't = 1 s、h = 0.1 s のとき、x = t² [m] の平均変化率を求める。',
          tex: r`\frac{(1+0.1)^2-1^2}{0.1}=\frac{0.21}{0.1}=2.1\,\mathrm{m/s}`,
          read: '差商 2t+h に t=1、h=0.1 を入れた 2.1 m/s と一致する。h を小さくすると 2 m/s へ近づく。',
        },
      },
      glossary: {
        h: '区間の幅。ここでは時間の刻み [s]。0に近づけるが、0そのものにはしない',
        t: '変化率を調べたい時刻 [s]',
        x: '時刻tでの位置 [m]。この章ではx=t²を例に使う',
        'Δt': '時間の変化分。後の時刻−前の時刻 [s]。この章ではhと同じもの',
        'Δx': '位置の変化分。後の位置−前の位置 [m]',
        'Δx/Δt': '平均変化率。区間の両端だけで決まる傾き [m/s]',
        'dx/dt': 'Δx/Δtでhを0に近づけたときの行き先。瞬間の変化率 [m/s]',
        lim: '「近づけたときの行き先」を表す記号。下に近づけ方を書く',
      },
      units: [
        { end: 3, goal: '平均変化率を、区間の幅 h の式として作る', gain: '2点を結ぶ直線の傾きがΔx/Δt。hを変えると傾きも変わり、行き先が接線の傾きになる。' },
        { end: 6, goal: '差商を展開・約分して、hの式に整理する', gain: '(t+h)²−t²=2th+h²。hで割ると2t+hになり、幅hがどこに残るかが見える。' },
        { end: 9, goal: '0で割らずに、行き先としてdx/dtを定める', gain: 'h→0で2t+hは2tへ。dx/dtは割り算の答えではなく、近づけた先の値。' },
      ],
      slides: [
        {
          heading: '平均の変化率は、何と何の割り算だろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'umx-avg-two-points',
          body: 'グラフ上に2点を選ぶ。横の差が $\\Delta t$、縦の差が $\\Delta x$。この割り算 $\\frac{\\Delta x}{\\Delta t}$ が平均変化率で、2点を結ぶ直線の傾きにあたる。',
          formula: r`\frac{\Delta x}{\Delta t}`,
          formulaNote: '2点を結ぶ直線の傾き。区間の両端だけで決まる',
        },
        {
          heading: '区間の幅を縮めると、傾きはどう動くのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'umx-avg-shrink',
          body: '区間の幅を $h$ と書く。$h$ を変えるたびに、2点を結ぶ直線の傾きも変わる。どの値を「その時刻の変化率」と呼べばよいのだろう。',
        },
        {
          heading: '2点を結ぶ直線は、どこに落ち着くのだろう?',
          beat: '解決',
          role: '観察',
          figure: 'umx-avg-tangent',
          body: '$h$ を小さくしていくと、2点を結ぶ直線は1本の直線に重なる。これが接線だ。接線の傾きなら、その時刻の変化率と呼べる。',
          formulaNote: '2点を結ぶ直線の行き先が、その点の接線',
        },
        {
          heading: '数値で追うと、傾きはどんな数へ向かうのだろう?',
          beat: '解決',
          role: '観察',
          figure: 'umx-avg-table',
          body: '$x=t^2$ の $t=1$ で計算する。$h=1$ で 3、$0.1$ で 2.1、$0.01$ で 2.01、$0.001$ で 2.001。値は 2 に近づいていく。',
          calculation: [
            { note: '平均変化率の定義に h=1 を入れる', tex: r`\frac{(1+1)^2-1^2}{1}=3` },
            { note: '幅を h=0.1 に縮める', tex: r`\frac{(1.1)^2-1^2}{0.1}=2.1` },
            { note: 'さらに h=0.01 まで縮める', tex: r`\frac{(1.01)^2-1^2}{0.01}=2.01` },
          ],
        },
        {
          heading: '$(t+h)^2$ を展開すると、何が出てくるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'umx-avg-expand',
          body: '文字のまま計算する。$(t+h)^2$ を展開して $t^2$ を引くと $2th+h^2$ が残る。辺 $t$ の正方形を $h$ だけ広げて増えた面積だ。',
          calculation: [
            { note: '2乗を展開する', tex: r`(t+h)^2=t^2+2th+h^2` },
            { note: '元の t の2乗を引く', tex: r`(t+h)^2-t^2=2th+h^2` },
          ],
        },
        {
          heading: '$h$ で割ると、式はどこまで簡単になるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'umx-avg-cancel',
          body: '分子 $2th+h^2$ は、どちらの項にも $h$ を含む。$h$ は0ではないので約分でき、差商は $2t+h$ になる。',
          formula: r`\frac{(t+h)^2-t^2}{h}=2t+h`,
          formulaNote: 'hが0でないから約分できる。結果にhが1つ残る',
          calculation: [
            { note: '分子を h でくくり出す', tex: r`\frac{2th+h^2}{h}=\frac{h(2t+h)}{h}` },
            { note: 'h は 0 ではないので約分する', tex: r`\frac{h(2t+h)}{h}=2t+h` },
          ],
        },
        {
          heading: 'いきなり $h=0$ を代入してよいのだろうか?',
          beat: '疑問',
          role: '問い',
          figure: 'umx-avg-h-zero',
          body: '約分する前の式に $h=0$ を入れると $\\frac{0}{0}$ になり、値が決まらない。だから0を代入せず、0に近づける。',
          formulaNote: '0で割ってはいない。近づけた先を見ている',
        },
        {
          heading: '近づけた先の値を、どう書き表すのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'umx-avg-limit',
          body: '$2t+h$ で $h$ を0へ近づけると $2t$ が残る。この行き先を $\\lim_{h\\to0}$ と書き、得た値を $\\frac{dx}{dt}$ と書く。',
          formula: r`\frac{dx}{dt}=\lim_{h\to0}\frac{(t+h)^2-t^2}{h}=2t`,
          formulaNote: 'dx/dtは割り算の答えではなく、近づけた先の値',
        },
        {
          heading: '微分は結局、どんな対応を作る操作だろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'umx-avg-derivative-map',
          body: '$x=t^2$ から $\\frac{dx}{dt}=2t$ が出た。位置の式に、各時刻の傾きを返す式が1本対応する。微分は、傾きの関数を作る操作だ。',
          formula: r`x=t^2\ \Rightarrow\ \frac{dx}{dt}=2t`,
          formulaNote: '関数から傾きの関数へ。値はそのまま速度 [m/s]',
        },
      ],
      preview: {
        goal: r`\frac{dx}{dt}=\lim_{\Delta t\to0}\frac{\Delta x}{\Delta t}`,
        now: '差商を展開・約分して、h→0 の行き先を読むこと',
        later: 'sinやcosの微分、積や合成関数の規則、2回微分で加速度を出すこと',
      },
      leadsTo: ['um-derivative'],
      problems: [
        {
          id: 'p-umxar-1',
          difficulty: 1,
          question: '$x=t^2$ の $t=2$ での平均変化率を、幅 $h$ を使って表すと?',
          choices: ['$4+h$', '$2t$', '$4h$', '$2+h$'],
          answerIndex: 0,
          hint: '差商 $2t+h$ に $t=2$ を入れる。',
          explanation: '差商は $\\frac{(t+h)^2-t^2}{h}=2t+h$ なので、$t=2$ を入れて **$4+h$**。$h$ が残っているのが「平均」である証拠で、$h\\to0$ とすると $4$ になる。$2t$ は $h$ を先に0にした後の値で、平均変化率そのものではない。',
        },
        {
          id: 'p-umxar-2',
          difficulty: 2,
          question: '差商を約分する前に $h=0$ を代入すると、どうなる?',
          choices: ['$2t$ になる', '$\\frac{0}{0}$ となり、値が決まらない', '$0$ になる', '$h$ がそのまま残る'],
          answerIndex: 1,
          hint: '分子も分母も0になっていないか確かめる。',
          explanation: '約分前の分子 $(t+h)^2-t^2$ は $h=0$ なら0、分母も0なので $\\frac{0}{0}$ となり値が決まらない。だから微分では**0を代入せず、0に近づけた行き先**を見る。先に約分して $2t+h$ にしてから $h\\to0$ とすれば $2t$ が残る。',
        },
        {
          id: 'p-umxar-3',
          difficulty: 2,
          question: '$x$ が m、$t$ が s のとき、$\\frac{dx}{dt}$ の単位は?',
          choices: ['m', 's', 'm/s', 'm·s'],
          answerIndex: 2,
          hint: '差商は「長さの差 ÷ 時間の差」。',
          explanation: '$\\frac{\\Delta x}{\\Delta t}$ は m を s で割った量なので単位は **m/s**。$h\\to0$ としても割り算の組み立ては変わらないから、単位もそのまま。$d$ が付いても「分子の単位÷分母の単位」が残る、と読めばよい。',
        },
        {
          id: 'p-umxar-4',
          difficulty: 2,
          question: '$x=t^2$ のとき、$t=-3$ での $\\frac{dx}{dt}$ の値は?',
          choices: ['$9$', '$-6$', '$6$', '$-9$'],
          answerIndex: 1,
          hint: '$\\frac{dx}{dt}=2t$ に $t=-3$ を入れる。',
          explanation: '$2\\times(-3)=-6$。負の値は「$t$ が増えると $x$ が減る向き」という情報を持つ。$x$ の値 $(-3)^2=9$ と取り違えないこと。**変化率の符号は、増えるか減るかを表している**。',
        },
        {
          id: 'p-umxar-5',
          difficulty: 3,
          question: '$x=t^2$ の差商が $2t+h$ になる理由として正しいのは?',
          choices: [
            '肩の2が前に降りる規則だから',
            '$(t+h)^2-t^2=2th+h^2$ を $h$ で割ると $2t+h$ になるから',
            '$t^2$ を2で割ると $t$ だから',
            '$h$ は小さいので最初から無視してよいから',
          ],
          answerIndex: 1,
          hint: 'まず展開し、それから約分する。順序が大事。',
          explanation: '展開すると $(t+h)^2-t^2=2th+h^2$。どちらの項にも $h$ があるので $h$ で割れて $2t+h$ が残る。**$h$ を最初から無視するのではなく、割った後で0へ近づける**。この順序を守るから $\\frac{0}{0}$ を避けられる。',
        },
      ],
    },

    // ================= Σ から ∫ へ =================
    {
      id: 'um-sum-to-integral',
      title: 'Σ から ∫ へ',
      subtitle: '分割・代表点・和・極限',
      enemy: { name: 'シグマゴーレム', emoji: '🗿', maxHp: 140 },
      theme: '有限個の和を、分割を細かくした行き先として書き直す',
      goal: r`区間を $n$ 等分して $S_n=\sum_{i=1}^{n}f(x_i)\,\Delta x$ を作り、$n\to\infty$ の行き先を $\int_a^b f(x)\,dx$ と書けるようになる。`,
      intro: '初級では、高さ×幅の小さな長方形を足して、変わる量の合計を求めた。ここではその手順を記号にする。分割・代表点・和・極限の4つを順に決めれば、∫の意味は自分で組み立てられる。',
      outro: '区間を $n$ 等分して幅 $\\Delta x=\\frac{b-a}{n}$、代表点 $x_i$ での高さを掛けて足すと $S_n$。$n\\to\\infty$ の行き先が $\\int_a^b f(x)\\,dx$。$f(x)\\,dx$ は小さな長方形1本で、中身は速度なら距離、力なら仕事になる。',
      foundation: {
        known: '長方形の面積が縦×横であること。値×幅の小片を足すと、変わる量の合計に近づくこと。',
        startingPoint: '区間を等しい幅に分け、各区間の代表点での値を高さに使う、と決めるところから出発する。',
        conditions: '区間の幅はすべて同じ、代表点は各区間の左端に取る、と約束する。fは区間の中で大きく跳ばないとする。',
        example: {
          given: 'f(x)=x [m/s]、区間 0〜4 s を4等分し、各区間の左端を代表点にする。',
          tex: r`S_4=(0+1+2+3)\times1=6\,\mathrm{m}`,
          read: '幅は1 s、高さは0,1,2,3 m/s。掛けて足すと6 m。正しい値8 mより小さいのは、左端が区間内で最小だから。',
        },
      },
      glossary: {
        n: '区間を分けた個数。大きくするほど1区間の幅が狭くなる',
        a: '足し合わせる範囲の左端。積分では下端と呼ぶ',
        b: '足し合わせる範囲の右端。積分では上端と呼ぶ',
        'Δx': '1区間の幅。等分なら(b−a)/n。xの単位をそのまま持つ',
        'xᵢ': 'i番目の区間から選んだ代表点。高さf(xᵢ)を決める',
        i: '区間に付けた番号。1からnまで動き、合計の外には残らない',
        'Σ': '番号の付いた項を足す記号。下に i=1、上に n を書く',
        'Sₙ': 'n個の小さな長方形の合計。まだ有限個の和',
        '∫': '分割を限りなく細かくしたときの、和の行き先',
        dx: '細かくし切った後の幅の印。Δxの行き先',
        f: '各点での高さを与える関数。単位は場面ごとに決まる',
      },
      units: [
        { end: 4, goal: '範囲・分割・代表点を、記号で決める', gain: '両端がaとb、幅はΔx=(b−a)/n、高さは代表点xᵢでのf(xᵢ)。これで小さな長方形が1本決まる。' },
        { end: 8, goal: '和をΣで書き、細かくした行き先を∫と書く', gain: 'S_nは有限個の和。nを増やすと値が落ち着き、その行き先が∫。f(x)dxは長方形1本分を指す。' },
        { end: 11, goal: '中身の意味・範囲の向き・Σとの違いを確かめる', gain: '速度なら距離、力なら仕事。上端と下端を入れ替えると符号が反転する。足す操作自体はΣと同じ。' },
      ],
      slides: [
        {
          heading: '変わる量の合計は、どんな部品でできているだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'umx-sum-value-width',
          body: '合計を作る部品は、細い長方形1本だ。高さはその場所での値、幅はその区間の長さ。これを必要な数だけ足していく。',
          formulaNote: '部品は「その場所の値 × その区間の幅」1本',
        },
        {
          heading: '足し合わせる範囲に、記号で名前を付けよう',
          beat: '解決',
          role: '観察',
          figure: 'umx-sum-partition-ends',
          body: '足し合わせる範囲を先に決める。左端を $a$、右端を $b$ と書く。範囲が決まらなければ、合計も決まらない。',
          formulaNote: 'aが範囲の左端（下端）、bが右端（上端）',
        },
        {
          heading: '$n$ 等分すると、1区間の幅はいくつになるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'umx-sum-width',
          body: '全体の長さ $b-a$ を $n$ 等分する。1区間の幅は $\\Delta x=\\frac{b-a}{n}$ だ。$n$ が大きいほど、幅は狭くなる。',
          formula: r`\Delta x=\frac{b-a}{n}`,
          formulaNote: 'nは区間の個数。等分なのでどの区間も同じ幅',
          calculation: [
            { note: '範囲の長さを、区間の個数で割る', tex: r`\Delta x=\frac{b-a}{n}` },
            { note: 'a=0、b=4、n=4 を入れる', tex: r`\Delta x=\frac{4-0}{4}=1` },
          ],
        },
        {
          heading: '各区間の高さは、どの点で測るのだろう?',
          beat: '解決',
          role: '観察',
          figure: 'umx-sum-sample',
          body: '$i$ 番目の区間から1点を選び、$x_i$ と書く。その点の値 $f(x_i)$ を、その区間の高さに使う。代表点は左端に取ると約束する。',
          formulaNote: 'xᵢの i は番号。i番目の区間から選んだ1点',
        },
        {
          heading: 'たくさんの掛け算を、1行で書けないだろうか?',
          beat: '解決',
          role: '操作',
          figure: 'umx-sum-sigma',
          body: '1本分は $f(x_i)\\Delta x$。これを $i=1$ から $n$ まで足す記号が $\\sum$ だ。合計を $S_n$ と書く。',
          formula: r`S_n=\sum_{i=1}^{n}f(x_i)\,\Delta x`,
          formulaNote: 'Σの下が始まりの番号、上が終わりの番号',
          calculation: [
            { note: '番号を1からnまで並べて書く', tex: r`S_n=f(x_1)\Delta x+f(x_2)\Delta x+\cdots+f(x_n)\Delta x` },
            { note: '同じ形の項をまとめて1行にする', tex: r`S_n=\sum_{i=1}^{n}f(x_i)\,\Delta x` },
          ],
        },
        {
          heading: '$n$ を増やすと、合計はどこへ向かうのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'umx-sum-refine',
          body: '$f(x)=x$、範囲 $0$ から $4$ で $n$ を増やす。$n=4$ で 6、$n=8$ で 7、$n=16$ で 7.5。この行き先に、どんな名前を付けよう。',
        },
        {
          heading: '近づいた先の値には、どんな記号を当てるのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'umx-sum-integral-symbol',
          body: '$n\\to\\infty$ で $S_n$ が近づく値を $\\int_a^b f(x)\\,dx$ と書く。$\\int$ は和の記号を伸ばした形、$dx$ は $\\Delta x$ の行き先だ。',
          formula: r`\int_a^b f(x)\,dx=\lim_{n\to\infty}\sum_{i=1}^{n}f(x_i)\,\Delta x`,
          formulaNote: '∫の下が下端a、上が上端b。dxは幅の行き先',
        },
        {
          heading: '$f(x)\\,dx$ の1本は、何を表しているのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'umx-sum-fdx-piece',
          body: '$f(x)\\,dx$ は、高さ $f(x)$・幅 $dx$ の細い長方形1本だ。$\\int$ はそれを範囲いっぱい足せという指示。面積の暗記ではなく、小片の合計と読む。',
          formulaNote: 'f(x)dxが1本分の量。∫はその合計を指示する記号',
        },
        {
          heading: '同じ形の和は、物理で何になるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'umx-sum-meanings',
          body: '高さが速度 [m/s]、幅が時間 [s] なら1本は距離 [m]。高さが力 [N]、幅が距離 [m] なら仕事 [J]。電場 [N/C] なら単位電荷あたりの仕事 [J/C]。',
          formulaNote: '掛ける2つの単位が、合計の単位を決める',
        },
        {
          heading: '上端と下端を入れ替えると、符号はどうなるだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'umx-sum-swap',
          body: '$\\int_a^b$ を $\\int_b^a$ に変えると、たどる向きが逆になる。幅 $\\Delta x$ の符号が変わるので、値は大きさが同じで符号だけ反転する。',
          formula: r`\int_b^a f(x)\,dx=-\int_a^b f(x)\,dx`,
          formulaNote: '範囲を書く順序が、たどる向きを表している',
        },
        {
          heading: '$\\sum$ と $\\int$ は、どこが同じでどこが違うのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'umx-sum-sigma-vs-integral',
          body: 'どちらも「値×幅」を足す操作だ。違うのは細かさの約束だけ。$\\sum$ は有限個で止め、$\\int$ は限りなく細かくした行き先を指す。',
          formulaNote: '足す操作は同じ。細かさの約束だけが違う',
        },
      ],
      preview: {
        goal: r`\int_a^b f(x)\,dx=F(b)-F(a)`,
        now: '分割・代表点・和・極限の4段階で∫を組み立てること',
        later: '原始関数を使い、和を数えずに値を出す方法と置換積分',
      },
      leadsTo: ['um-integral', 'ue-integrals'],
      problems: [
        {
          id: 'p-umxsi-1',
          difficulty: 1,
          question: '$\\sum_{i=1}^{4}f(x_i)\\,\\Delta x$ で、足す項の個数は?',
          choices: ['1個', '4個', '5個', 'xの値による'],
          answerIndex: 1,
          hint: '下の番号から上の番号まで、1つずつ動かして数える。',
          explanation: '$i$ は 1, 2, 3, 4 と動くので項は**4個**。$\\sum$ の下が始まりの番号、上が終わりの番号だ。5個と数えるのは $i=0$ から始めた場合で、この式は $i=1$ から始まる。$i$ は合計の中だけで使われ、答えには残らない。',
        },
        {
          id: 'p-umxsi-2',
          difficulty: 1,
          question: '区間 $1\\le x\\le 5$ を8等分したときの、1区間の幅 $\\Delta x$ は?',
          choices: ['$0.5$', '$4$', '$8$', '$2$'],
          answerIndex: 0,
          hint: '$\\Delta x=\\frac{b-a}{n}$ に数値を入れる。',
          explanation: '$\\Delta x=\\frac{5-1}{8}=0.5$。範囲の長さ $b-a=4$ を個数8で割る。$4$ は分けない場合の全長。$2$ は $\\frac{n}{b-a}$ を計算したもので、これは長さ1あたりの区間の個数であって幅ではない。**割る順序が意味を決める**。',
        },
        {
          id: 'p-umxsi-3',
          difficulty: 2,
          question: '$\\int_0^3 f(x)\\,dx=5$ のとき、$\\int_3^0 f(x)\\,dx$ の値は?',
          choices: ['$5$', '$-5$', '$0$', '$15$'],
          answerIndex: 1,
          hint: '上端と下端を入れ替えると、たどる向きが逆になる。',
          explanation: '上端と下端を入れ替えると幅 $\\Delta x$ の符号が反転するので、和全体の符号も反転して **$-5$** になる。大きさは変わらない。積分は範囲だけでなく**たどる向き**も持つ量で、書く順序がその向きを表している。',
        },
        {
          id: 'p-umxsi-4',
          difficulty: 2,
          question: '高さが速度 [m/s]、幅が時間 [s] のとき、$\\sum f(x_i)\\,\\Delta x$ の単位は?',
          choices: ['m/s', 's', 'm', 'm/s²'],
          answerIndex: 2,
          hint: '1本分の単位は、高さの単位×幅の単位。',
          explanation: '1本は m/s × s = **m** なので、合計の単位も m。足し算では単位は変わらないからだ。高さが力 [N]、幅が距離 [m] なら1本は N·m = J になる。**何を足しているかは、単位を掛ければ分かる**。',
        },
        {
          id: 'p-umxsi-5',
          difficulty: 3,
          question: '増え続ける関数で、各区間の左端を代表点にして $S_n$ を作った。$n$ を増やすと $S_n$ はどう動く?',
          choices: [
            '正しい値より大きいまま、減っていく',
            '正しい値より小さいまま、増えていく',
            '正しい値のまま変わらない',
            '大小が毎回入れ替わる',
          ],
          answerIndex: 1,
          hint: '増え続ける関数では、区間の左端がその区間で最も小さい値になる。',
          explanation: '増え続ける関数では左端の値が区間内で最小なので、各長方形は本来より低く、$S_n$ は正しい値より**小さい**。$n$ を増やすと不足が減り、下から近づく。$f(x)=x$、範囲 $0$ から $4$ では 6、7、7.5 と 8 へ近づいた。',
        },
      ],
    },

    // ================= 内積 =================
    {
      id: 'um-inner-product',
      title: '内積で効く成分を取り出す',
      subtitle: 'cosでも成分でも同じ値',
      enemy: { name: 'ドットスカラベ', emoji: '🪲', maxHp: 135 },
      theme: '向きの違う2本の矢印から、1つの数を作る',
      goal: r`$\vec F\cdot\Delta\vec r=F\,\Delta r\cos\theta=F_x\Delta x+F_y\Delta y$ の2通りの計算が一致することを確かめ、符号の意味を言えるようになる。`,
      intro: '初級では、斜めの力のうち進む向きに揃った成分だけが効くことを見た。その「効く成分の掛け算」に名前と記号を与える。角度で計算しても成分で計算しても、答えは同じ1つの数になる。',
      outro: '内積 $\\vec A\\cdot\\vec B$ は、$AB\\cos\\theta$ とも $A_xB_x+A_yB_y$ とも書ける同じ1つの数だ。直角なら0、逆向きなら負になる。ベクトルの大きさだけを掛けるのは誤りで、必ず向きの情報が入る。',
      foundation: {
        known: '斜めの力は、進む向きに揃った成分だけが仕事に効くこと。直角三角形の辺の比がcosであること。',
        startingPoint: '効く成分の大きさを F cosθ と書き、それに移動距離を掛けるところから出発する。',
        conditions: 'この段では平面内の2次元だけを扱い、成分は直交するx軸・y軸で測る。θは2本の矢印のなす角とする。',
        example: {
          given: '力 (3, 4) N で、変位 (2, 0) m だけ動かしたときの仕事を求める。',
          tex: r`\vec F\cdot\Delta\vec r=3\times2+4\times0=6\,\mathrm{J}`,
          read: '大きさは5 Nと2 m、なす角は約53°でcos53°=0.6。5×2×0.6=6 Jとなり、成分の計算と一致する。',
        },
      },
      glossary: {
        'Fx': '力のx成分 [N]。x軸に揃った分だけを取り出した値',
        'Fy': '力のy成分 [N]。y軸に揃った分',
        'Δr': '変位ベクトル。どちらへどれだけ動いたかをまとめて表す [m]',
        'Δx': '変位のx成分 [m]',
        'Δy': '変位のy成分 [m]',
        theta: '2本の矢印のなす角。0°から180°までで測る',
        'cosθ': '効く割合。0°で1、90°で0、180°で−1',
        '·': '内積の印。2本のベクトルから1つの数を作る',
        W: 'その力がした仕事 [J]。内積の値そのもの',
      },
      units: [
        { end: 3, goal: '角度の式に、内積という名前と記号を与える', gain: '効く成分の掛け算 FΔrcosθ を内積と呼び、点の記号で書く。答えは矢印ではなく1つの数。' },
        { end: 6, goal: '角度を測らずに、成分だけで内積を計算する', gain: '成分表示ではFxΔx+FyΔy。角度の式と同じ値になり、角度を測る手間がいらない。' },
        { end: 9, goal: '符号を読み、大きさだけを掛ける誤りを避ける', gain: '直角で0、逆向きで負。大きさの積FΔrはcosθ=1の特別な場合にしか合わない。' },
      ],
      slides: [
        {
          heading: '斜めの力で効くのは、どこまでだったろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'umx-dot-cos-start',
          body: '進む向きと角 $\\theta$ をなす力は、そのままでは掛けられない。効くのは、進む向きに揃った成分 $F\\cos\\theta$ だけだ。',
          formula: r`W=F\,\Delta r\cos\theta`,
          formulaNote: '効く成分 F cosθ に、移動距離 Δr を掛ける',
        },
        {
          heading: 'この掛け算に、名前と記号を付けよう',
          beat: '解決',
          role: '操作',
          figure: 'umx-dot-notation',
          body: '「大きさ×大きさ×$\\cos\\theta$」を内積と呼び、$\\vec F\\cdot\\Delta\\vec r$ と書く。答えは矢印ではなく、ただ1つの数だ。',
          formula: r`\vec F\cdot\Delta\vec r=F\,\Delta r\cos\theta`,
          formulaNote: '内積の答えは向きを持たない1つの数',
        },
        {
          heading: '角度を測らずに計算できないだろうか?',
          beat: '疑問',
          role: '問い',
          figure: 'umx-dot-angle-problem',
          body: '$\\cos\\theta$ を使うには、毎回なす角を測らなければならない。角度を通らない計算法はないだろうか。',
        },
        {
          heading: '成分で書くと、内積はどんな形になるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'umx-dot-components',
          body: '2本を $x$ 成分と $y$ 成分に分ける。同じ軸の成分どうしを掛けて足すだけで、$\\vec A\\cdot\\vec B=A_xB_x+A_yB_y$ となる。',
          formula: r`\vec A\cdot\vec B=A_xB_x+A_yB_y`,
          formulaNote: '同じ軸の成分どうしを掛けて足す。角度は不要',
        },
        {
          heading: '2通りの計算は、本当に同じ値になるだろうか?',
          beat: '解決',
          role: '解釈',
          figure: 'umx-dot-check',
          body: '$\\vec F=(3,4)$ N、$\\Delta\\vec r=(2,0)$ m で試す。成分では $3\\times2+4\\times0=6$ J。大きさと $\\cos\\theta=0.6$ でも $5\\times2\\times0.6=6$ J。',
          calculation: [
            { note: '同じ軸の成分どうしを掛けて足す', tex: r`\vec F\cdot\Delta\vec r=3\times2+4\times0=6\,\mathrm{J}` },
            { note: '大きさとcosθで計算し直す', tex: r`F\,\Delta r\cos\theta=5\times2\times0.6=6\,\mathrm{J}` },
          ],
        },
        {
          heading: '直角のとき、内積はいくつになるだろう?',
          beat: '解決',
          role: '観察',
          figure: 'umx-dot-perpendicular',
          body: '$\\vec F=(0,4)$ N と $\\Delta\\vec r=(2,0)$ m なら $0\\times2+4\\times0=0$。$\\cos90^\\circ=0$ にあたる。真上の力は前へは効かない。',
          formula: r`\vec F\cdot\Delta\vec r=0\quad(\theta=90^\circ)`,
          formulaNote: '直角なら内積は0。真上へ引く力は前へは効かない',
        },
        {
          heading: '逆を向いていると、符号はどうなるだろう?',
          beat: '解決',
          role: '観察',
          figure: 'umx-dot-negative',
          body: '$\\vec F=(-3,0)$ N と $\\Delta\\vec r=(2,0)$ m なら $-3\\times2=-6$ J。$\\cos180^\\circ=-1$ にあたる。負号は逆向きの印だ。',
          formulaNote: '90°より大きい角ではcosθが負。内積も負になる',
        },
        {
          heading: '大きさだけを掛けては、なぜいけないのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'umx-dot-magnitude-trap',
          body: '同じ $(3,4)$ N と $(2,0)$ m で大きさだけ掛けると $5\\times2=10$ J。正しい 6 J より大きい。これは真正面に押した場合の値だ。',
          formulaNote: '大きさの積は、向きがぴたり揃った場合の上限',
        },
        {
          heading: '内積は結局、何を取り出す道具だろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'umx-dot-projection',
          body: '内積は、相手の向きに揃った分だけを取り出して掛ける道具だ。$\\cos\\theta$ でも成分でも計算でき、答えは同じ1つの数になる。',
          formula: r`\vec A\cdot\vec B=AB\cos\theta=A_xB_x+A_yB_y`,
          formulaNote: '同じ量の2通りの書き方。場面で使い分ける',
        },
      ],
      preview: {
        goal: r`W=\int_C\vec F\cdot d\vec r`,
        now: '内積を角度でも成分でも計算し、符号を読むこと',
        later: '3成分への拡張、道に沿った積分、向きを持つ外積との違い',
      },
      leadsTo: ['um-dot', 'um-vector'],
      problems: [
        {
          id: 'p-umxip-1',
          difficulty: 1,
          question: '$\\vec A=(2,3)$、$\\vec B=(4,-1)$ のとき、$\\vec A\\cdot\\vec B$ の値は?',
          choices: ['$5$', '$11$', '$(8,-3)$', '$8$'],
          answerIndex: 0,
          hint: '同じ軸の成分どうしを掛けて足す。',
          explanation: '$2\\times4+3\\times(-1)=8-3=5$。**内積の答えは1つの数**なので、$(8,-3)$ のような組にはならない。$11$ は符号を無視して足した値、$8$ は $x$ 成分だけを見た値。$y$ 成分の符号まで含めて足す。',
        },
        {
          id: 'p-umxip-2',
          difficulty: 2,
          question: '大きさ 6 N の力と、大きさ 3 m の変位が直角を向いている。内積の値は?',
          choices: ['$18\\,\\mathrm{J}$', '$0\\,\\mathrm{J}$', '$-18\\,\\mathrm{J}$', '$9\\,\\mathrm{J}$'],
          answerIndex: 1,
          hint: '$\\cos90^\\circ$ はいくつか。',
          explanation: '$\\cos90^\\circ=0$ なので $6\\times3\\times0=0$ **J**。進む向きに揃った成分が1つもないからだ。$18$ J は**ベクトルの大きさだけを掛けた**値で、真正面に押した場合にしか合わない。向きの情報を落としてはいけない。',
        },
        {
          id: 'p-umxip-3',
          difficulty: 2,
          question: '内積が負になるのは、2本の矢印がどんな関係のときか?',
          choices: ['なす角が90°のとき', 'なす角が90°より大きいとき', '両方の大きさが負のとき', 'なす角が0°のとき'],
          answerIndex: 1,
          hint: '$\\cos\\theta$ の符号が変わるのは何度からか。',
          explanation: '$\\cos\\theta$ は $90^\\circ$ を超えると負になるので、内積も負になる。$90^\\circ$ ちょうどでは0、$0^\\circ$ では最大の正。**ベクトルの大きさは常に0以上**だから、符号を決めているのは向きだけだ。',
        },
        {
          id: 'p-umxip-4',
          difficulty: 2,
          question: '力 [N] と変位 [m] の内積の単位は?',
          choices: ['N', 'm', 'N·m すなわち J', 'N/m'],
          answerIndex: 2,
          hint: '内積も掛け算なので、数と一緒に単位も掛かる。',
          explanation: '成分どうしの積 $F_x\\Delta x$ が N × m なので、単位は **N·m = J**。足し算では単位が変わらないから、合計もJのまま。$\\cos\\theta$ は辺の比で単位を持たないので、単位を変えない。',
        },
        {
          id: 'p-umxip-5',
          difficulty: 3,
          question: '$\\vec F=(3,4)$ N、$\\Delta\\vec r=(2,0)$ m のとき、仕事を $5\\times2=10$ J とした。誤りの理由は?',
          choices: [
            '掛ける順序が違うから',
            'ベクトルの大きさだけを掛けていて、向きのずれ $\\cos\\theta=0.6$ を落としているから',
            '$\\Delta\\vec r$ の大きさが 2 m ではないから',
            '答えの単位がJにならないから',
          ],
          answerIndex: 1,
          hint: '効くのは、進む向きに揃った成分だけだった。',
          explanation: '正しくは $3\\times2+4\\times0=6$ J。$5\\times2$ は大きさの積で、$\\cos\\theta=1$ の場合の値だ。実際は $\\cos\\theta=0.6$ なので $5\\times2\\times0.6=6$ J。**$y$ 方向の 4 N は、$x$ 方向へ動く間は仕事をしない**。',
        },
      ],
    },

    // ================= 曲がった道を折れ線で =================
    {
      id: 'um-path-pieces',
      title: '曲がった道を折れ線で',
      subtitle: '辺ごとに内積を作って足す',
      enemy: { name: 'カーブリザード', emoji: '🦖', maxHp: 145 },
      theme: '曲がった道を折れ線に置きかえ、辺ごとの寄与を足す',
      goal: r`曲線を折れ線で近似し、$\sum_i\vec F(\vec r_i)\cdot\Delta\vec r_i$ を作れる。逆向きにたどると符号が反転することも説明できる。`,
      intro: '内積は、まっすぐな1辺の寄与を出す道具だった。では道が曲がっていたらどうするか。曲線を短い直線の連なりに置きかえれば、1辺ずつ内積を作って足すだけで済む。',
      outro: '曲線は折れ線に置きかえ、辺ごとに $\\vec F(\\vec r_i)\\cdot\\Delta\\vec r_i$ を作って足す。辺ごとに角度が違うので、寄与には正と負が混ざる。逆向きにたどると各 $\\Delta\\vec r_i$ が反転し、合計の符号も反転する。',
      foundation: {
        known: '内積を使えば、力と変位から効く分だけを取り出せること。区間に分けて足すと合計になること。',
        startingPoint: '曲線を、頂点が曲線上にある短い折れ線に置きかえるところから出発する。',
        conditions: '各辺は十分短く、その中では力が変わらないとみなす。辺の向きは、道をたどる向きを正とする。',
        example: {
          given: '重力 (0, −2) N の中を、(0,0) から (1,1) m へ1辺だけ進む。',
          tex: r`\vec F\cdot\Delta\vec r=0\times1+(-2)\times1=-2\,\mathrm{J}`,
          read: '上りなので寄与は負。大きさ2 Nと1.41 mを掛けた2.83ではなく、向きを含めた−2 Jが答え。',
        },
      },
      glossary: {
        'rᵢ': 'i番目の辺で代表に選んだ位置。そこでの力を使う',
        'Δrᵢ': 'i番目の辺の変位ベクトル。終点−始点 [m]',
        'F(rᵢ)': '位置rᵢでの力ベクトル [N]。場所ごとに値が変わりうる',
        N: '折れ線の辺の数。増やすほど元の曲線に近づく',
        'Σ': '辺ごとの寄与を、番号の順に全部足す記号',
        C: 'たどる道そのもの。向きまで含めて指定する',
        W: '道全体で力がした仕事 [J]。辺ごとの寄与の合計',
        theta: '各辺で、力と変位のなす角。辺ごとに違う',
      },
      units: [
        { end: 3, goal: '曲線を、辺の向きが決まる折れ線に置きかえる', gain: '曲線のままでは変位が1本に決まらない。頂点を曲線上に取れば、辺ごとに直線として扱える。' },
        { end: 6, goal: '辺ごとに内積を作り、番号の順に足す', gain: '各辺で位置rᵢ・変位Δrᵢ・力F(rᵢ)が決まる。角度が辺ごとに違うので、寄与に正と負が混ざる。' },
        { end: 9, goal: '辺を増やす操作と、向きの反転を確かめる', gain: '辺を増やすと折れ線は曲線に重なる。逆向きにたどると全てのΔrᵢが反転し、合計の符号も反転する。' },
      ],
      slides: [
        {
          heading: 'まっすぐな1辺なら、寄与はどう出したろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'umx-path-straight',
          body: 'まっすぐな1辺なら、内積を1回計算すれば寄与が出る。重力 $(0,-2)$ N の中を $(1,1)$ m 進めば $-2$ J だ。',
          formula: r`\Delta W=\vec F\cdot\Delta\vec r`,
          formulaNote: '1辺の寄与は内積1回。上りなので負になる',
        },
        {
          heading: '道が曲がっていると、何が決まらなくなるだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'umx-path-curve-question',
          body: '曲がった道では、進む向きが場所ごとに変わる。掛けるべき $\\Delta\\vec r$ が、1本に決まらない。',
        },
        {
          heading: '曲線を、短い直線の連なりに置きかえよう',
          beat: '解決',
          role: '操作',
          figure: 'umx-path-polyline',
          body: '曲線の上に点を打ち、隣どうしを直線で結ぶ。できた折れ線なら、各辺の向きが1つに決まる。ここでは山なりの道を4辺にする。',
          formulaNote: '頂点は曲線上に取る。1辺の中では向きが一定',
        },
        {
          heading: '1辺を取り出すと、何が決まるのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'umx-path-one-edge',
          body: '$i$ 番目の辺では、位置 $\\vec r_i$、変位 $\\Delta\\vec r_i$、その場所の力 $\\vec F(\\vec r_i)$ が決まる。寄与はその内積1回だ。',
          formula: r`\Delta W_i=\vec F(\vec r_i)\cdot\Delta\vec r_i`,
          formulaNote: '力は位置の関数。辺ごとに値が変わりうる',
        },
        {
          heading: '辺ごとに角度が違うと、寄与はどうなるだろう?',
          beat: '解決',
          role: '観察',
          figure: 'umx-path-angles',
          body: '重力 $(0,-2)$ N の下で山を越える。上りの2辺は $(1,1)$ m で $-2$ J ずつ、下りの2辺は $(1,-1.5)$ m で $+3$ J ずつになる。',
          formulaNote: '上りは負、下りは正。角が90°を超えるかで決まる',
        },
        {
          heading: '全部の辺を足すと、どんな式になるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'umx-path-sum',
          body: '4辺の寄与 $-2,-2,+3,+3$ を足すと $2$ J。番号 $i$ を1から4まで動かすので $\\sum_{i=1}^{4}\\vec F(\\vec r_i)\\cdot\\Delta\\vec r_i$ と書ける。',
          formula: r`W\approx\sum_{i=1}^{4}\vec F(\vec r_i)\cdot\Delta\vec r_i`,
          formulaNote: '≈ なのは、有限個の辺で近似しているから',
          calculation: [
            { note: '辺ごとの寄与を、番号の順に並べる', tex: r`W\approx(-2)+(-2)+3+3` },
            { note: '符号を含めて足し合わせる', tex: r`W\approx2\,\mathrm{J}` },
          ],
        },
        {
          heading: '辺を増やすと、折れ線はどこまで近づくだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'umx-path-refine',
          body: '山なりの道を4辺、8辺、16辺と置きかえる。辺の長さの合計は道のりに近づき、差はどんどん小さくなる。',
        },
        {
          heading: '道を逆向きにたどると、符号はどうなるだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'umx-path-reverse',
          body: '同じ道を逆にたどると、どの辺でも $\\Delta\\vec r_i$ が反対を向く。内積は $-1$ 倍になり、合計は $2$ J から $-2$ J に変わる。',
          formula: r`\vec F\cdot(-\Delta\vec r_i)=-\,\vec F\cdot\Delta\vec r_i`,
          formulaNote: '道は向きまで含めて指定する。向きが変われば符号も変わる',
        },
        {
          heading: 'この和は、上級ではどう書かれるのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'umx-path-line-integral',
          body: '辺を限りなく短くした行き先を $\\int_C\\vec F\\cdot d\\vec r$ と書く。$C$ はたどる道、$d\\vec r$ は短くし切った1辺だ。',
          formula: r`W=\int_C\vec F\cdot d\vec r`,
          formulaNote: 'Cは向きを含めた道の名前。drはΔrの行き先',
        },
      ],
      preview: {
        goal: r`W=\int_C\vec F\cdot d\vec r`,
        now: '曲線を折れ線に置きかえ、辺ごとの内積を足すこと',
        later: '道を1つの変数で表し、積分として実際に計算すること',
      },
      leadsTo: ['um-dot', 'ue-integrals'],
      problems: [
        {
          id: 'p-umxpp-1',
          difficulty: 1,
          question: '重力 $(0,-2)$ N の中を、変位 $(1,1)$ m だけ進んだ。この辺の寄与は?',
          choices: ['$-2\\,\\mathrm{J}$', '$2\\,\\mathrm{J}$', '$2.83\\,\\mathrm{J}$', '$0\\,\\mathrm{J}$'],
          answerIndex: 0,
          hint: '成分どうしを掛けて足す。上りか下りかで符号が決まる。',
          explanation: '$0\\times1+(-2)\\times1=-2$ **J**。上向きに動いた分だけ重力に逆らうので負になる。$2.83$ J は**ベクトルの大きさだけを掛けた** $2\\times1.41$ で、向きのずれを落としている。符号まで含めて答える。',
        },
        {
          id: 'p-umxpp-2',
          difficulty: 2,
          question: 'ある道をたどったときの $\\sum\\vec F\\cdot\\Delta\\vec r_i$ が $5$ J だった。同じ道を逆向きにたどると?',
          choices: ['$5\\,\\mathrm{J}$', '$-5\\,\\mathrm{J}$', '$0\\,\\mathrm{J}$', '$10\\,\\mathrm{J}$'],
          answerIndex: 1,
          hint: '各辺の $\\Delta\\vec r_i$ の向きがどうなるかを見る。',
          explanation: '逆向きにたどると、どの辺でも $\\Delta\\vec r_i$ が反対を向いて $-1$ 倍になる。内積も $-1$ 倍なので、合計は **$-5$ J**。力の側は変わらない。道は**向きまで含めて指定する**量だと分かる。',
        },
        {
          id: 'p-umxpp-3',
          difficulty: 2,
          question: '$\\sum_i\\vec F(\\vec r_i)\\cdot\\Delta\\vec r_i$ の $\\vec r_i$ は、何を指しているか?',
          choices: [
            '道全体の長さ',
            'i番目の辺で選んだ代表の位置。そこでの力を決めるために使う',
            '始点から終点までの変位',
            '辺の本数',
          ],
          answerIndex: 1,
          hint: '力は場所によって変わる。どこの力を使うかを決める必要がある。',
          explanation: '$\\vec r_i$ は**i番目の辺の代表点の位置**で、その場所での力 $\\vec F(\\vec r_i)$ を決めるために使う。動いた量そのものは $\\Delta\\vec r_i$ という別の量だ。位置と変位を混同すると、どの力を掛けるかが決まらなくなる。',
        },
        {
          id: 'p-umxpp-4',
          difficulty: 2,
          question: '山を越える道を重力の中でたどると、辺ごとの寄与はどうなるか?',
          choices: [
            '全部の辺で正になる',
            '全部の辺で負になる',
            '上りの辺は負、下りの辺は正になる',
            '全部の辺で0になる',
          ],
          answerIndex: 2,
          hint: '重力は下向き。各辺の変位の上下成分を見る。',
          explanation: '重力は下向きなので、上向きに動く辺では角が $90^\\circ$ を超えて $\\cos\\theta$ が負になり寄与は負、下向きに動く辺では正になる。**同じ道の中で符号が混ざる**のが曲がった道の特徴で、合計は高さの差だけで決まる。',
        },
        {
          id: 'p-umxpp-5',
          difficulty: 3,
          question: '折れ線の辺の数を増やしていくと、$\\sum\\vec F(\\vec r_i)\\cdot\\Delta\\vec r_i$ はどうなるか?',
          choices: [
            '0に近づく',
            '限りなく大きくなる',
            'ある値に落ち着き、その行き先を $\\int_C$ と書く',
            '辺の数に比例して増える',
          ],
          answerIndex: 2,
          hint: '辺を短くすると、辺の向きは道の向きにどこまで近づくか。',
          explanation: '辺を短くするほど折れ線は元の曲線に重なり、各辺の向きも道の向きに近づく。和は**ある値に落ち着き**、その行き先を $\\int_C\\vec F\\cdot d\\vec r$ と書く。辺が増えても1辺の寄与は小さくなるので、合計は限りなく大きくはならない。',
        },
      ],
    },

    // ================= 面積ベクトルと法線 =================
    {
      id: 'um-area-vector',
      title: '面積ベクトルと法線',
      subtitle: '広さと向きを矢印1本に',
      enemy: { name: 'ノーマルクラブ', emoji: '🦀', maxHp: 140 },
      theme: '面の広さと向きを、1本の矢印にまとめて扱う',
      goal: r`$d\vec A=\vec n\,dA$ の分解を説明し、$\sum_i\vec B(\vec r_i)\cdot\vec n_i\,\Delta A_i$ を作れる。面の向きを反転すると符号も反転することを言える。`,
      intro: '面を通る量は、面の広さだけでは決まらなかった。向きも要る。広さと向きという2つの情報を矢印1本にまとめてしまえば、前の段で作った内積がそのまま使える。',
      outro: '面の情報は広さと向きだけ。向きを長さ1の法線 $\\vec n$ で表し、$\\Delta\\vec A=\\vec n\\,\\Delta A$ と1本にまとめる。通る量は $\\vec B\\cdot\\vec n\\,\\Delta A$。法線を逆に選ぶと符号が反転するので、向きの約束を先に決めておく。',
      foundation: {
        known: '面を正面から貫くときに通る量が最大で、面に沿う向きでは0になること。内積の計算のしかた。',
        startingPoint: '面の向きを、面に垂直で長さ1の矢印（法線）で表す、と決めるところから出発する。',
        conditions: '各小片は平らとみなせるほど小さいとする。法線は表裏どちらを向けてもよいが、先に決めて途中で変えない。',
        example: {
          given: '磁束密度 2 T の中に、面積 3 m² の平らな面を、法線が場と60°をなすように置く。',
          tex: r`\vec B\cdot\vec n\,\Delta A=2\times3\times\cos60^\circ=3\,\mathrm{Wb}`,
          read: '正面（0°）なら6 Wb、真横（90°）なら0 Wb。cos60°=0.5なので、ちょうど半分の3 Wb。',
        },
      },
      glossary: {
        n: '面に垂直で長さ1の矢印、法線。長さではなく向きだけを担当する',
        A: 'この章では面の面積 [m²]。振幅ではない',
        'ΔA': '小片1枚の面積 [m²]。向きを持たない正の数',
        'nΔA': '面積ベクトル。向きは法線、長さは面積 [m²]',
        dA: '小片を限りなく小さくしたときの面積の印 [m²]',
        B: 'この章では磁束密度 [T]。面を貫く矢印の場',
        'Φ': '面を通る量、磁束 [Wb]。Wb = T·m²',
        'nᵢ': 'i番目の小片の法線。小片ごとに向きが違う',
        'ΔAᵢ': 'i番目の小片の面積 [m²]',
        theta: '法線と場の矢印のなす角。面の傾きそのものではない',
      },
      units: [
        { end: 3, goal: '面の向きを、法線という1本の矢印で表す', gain: '面の情報は広さと向きの2つだけ。向きは面に垂直な長さ1の矢印で一意に表せる。' },
        { end: 6, goal: '広さと向きを1本にまとめ、通る量を内積で出す', gain: '面積ベクトルは向きが法線・長さが面積。通る量はBΔAcosθで、使う角は法線との角。' },
        { end: 9, goal: '曲がった面へ広げ、向きの反転を確かめる', gain: '曲面は小さな平らな片に分けて足す。法線を逆に選ぶと、通る量の符号がそのまま反転する。' },
      ],
      slides: [
        {
          heading: '面を通る量は、何で決まっていたのだろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'umx-area-through',
          body: '面を通る量を決めるのは、面の広さと面の向きの2つだけだ。同じ広さでも、正面を向ければ最大、寝かせれば0になる。',
          formulaNote: '効くのは広さと向きの2つだけ',
        },
        {
          heading: '面の向きを、どうやって数にするのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'umx-area-orientation-q',
          body: '広さは数1つで書ける。しかし面の中には無数の方向があり、どれを面の向きの代表に選べばよいか決まらない。',
        },
        {
          heading: '面に垂直な向きなら、1本に決まらないだろうか?',
          beat: '解決',
          role: '観察',
          figure: 'umx-area-normal',
          body: '面の中の方向は多いが、面に垂直な向きは表と裏の2つだけ。どちらかを選び、長さ1の矢印 $\\vec n$ とする。これを法線と呼ぶ。',
          formulaNote: '法線nの長さは1。長さではなく向きだけを担当する',
        },
        {
          heading: '広さと向きを、1本の矢印にまとめられないか?',
          beat: '解決',
          role: '操作',
          figure: 'umx-area-vector-build',
          body: '法線 $\\vec n$ に面積 $\\Delta A$ を掛ける。できた $\\Delta\\vec A=\\vec n\\,\\Delta A$ は、向きが法線、長さが面積の矢印だ。',
          formula: r`\Delta\vec A=\vec n\,\Delta A`,
          formulaNote: '向きはnが、長さはΔAが担当。分けて読める',
        },
        {
          heading: '傾いた面を通る量は、いくらになるだろう?',
          beat: '解決',
          role: '操作',
          figure: 'umx-area-tilt',
          body: '場 $\\vec B$ と面積ベクトルの内積を取る。$B=2$ T、$\\Delta A=3$ m²、$\\theta=60^\\circ$ なら $2\\times3\\times0.5=3$ Wb になる。',
          formula: r`\Phi=\vec B\cdot\vec n\,\Delta A=B\,\Delta A\cos\theta`,
          formulaNote: 'θは法線と場のなす角。単位は T·m² = Wb',
          calculation: [
            { note: '面積ベクトルと場の内積を取る', tex: r`\Phi=\vec B\cdot\vec n\,\Delta A=B\,\Delta A\cos\theta` },
            { note: 'cos60°=0.5 を使って数値を入れる', tex: r`\Phi=2\times3\times0.5=3\,\mathrm{Wb}` },
          ],
        },
        {
          heading: '面に沿う矢印を使うと、どうなるだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'umx-area-inplane-trap',
          body: '法線ではなく、面に沿う矢印を選ぶとどうなるか。正面から貫くとき、正しくは $6$ Wb なのに、この矢印では $0$ と出てしまう。',
          formulaNote: '向きの代表は必ず法線。面に沿う矢印では0になる',
        },
        {
          heading: '曲がった面では、どう足せばよいのだろう?',
          beat: '解決',
          role: '操作',
          figure: 'umx-area-sum',
          body: '曲面を小さな平らな片に分ける。片ごとに法線 $\\vec n_i$ と面積 $\\Delta A_i$ が決まるので、その内積を全部足せばよい。',
          formula: r`\Phi\approx\sum_i\vec B(\vec r_i)\cdot\vec n_i\,\Delta A_i`,
          formulaNote: '片ごとに法線の向きが違う。番号iで区別する',
        },
        {
          heading: '法線を逆に選ぶと、符号はどうなるだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'umx-area-flip',
          body: '法線を裏側に向けると $\\vec n$ が $-1$ 倍になる。内積も $-1$ 倍で、$3$ Wb は $-3$ Wb に変わる。向きは計算の前に決めておく。',
          formulaNote: '符号は面の向きの約束で決まる。先に決めて変えない',
        },
        {
          heading: 'この面の和は、上級ではどう書かれるのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'umx-area-flux-integral',
          body: '片を限りなく小さくした行き先を $\\int\\vec B\\cdot d\\vec A$ と書く。$d\\vec A=\\vec n\\,dA$ と分ければ、中身は向きと広さのままだ。',
          formula: r`\Phi=\int\vec B\cdot d\vec A,\quad d\vec A=\vec n\,dA`,
          formulaNote: 'dAは向きが法線、長さが小片の面積の矢印',
        },
      ],
      preview: {
        goal: r`\Phi=\int\vec B\cdot d\vec A`,
        now: '法線と面積を1本の矢印にまとめ、内積で通る量を出すこと',
        later: '閉じた面での積分、ガウスの法則、外向きを正とする約束',
      },
      leadsTo: ['um-dot', 'ue-integrals'],
      problems: [
        {
          id: 'p-umxav-1',
          difficulty: 1,
          question: '磁束密度 $2$ T の中に面積 $4$ m² の面を、法線が場と同じ向きになるように置いた。通る量は?',
          choices: ['$8\\,\\mathrm{Wb}$', '$0\\,\\mathrm{Wb}$', '$2\\,\\mathrm{Wb}$', '$0.5\\,\\mathrm{Wb}$'],
          answerIndex: 0,
          hint: '$\\cos0^\\circ$ はいくつか。',
          explanation: '$\\Phi=B\\,\\Delta A\\cos\\theta=2\\times4\\times1=8$ **Wb**。法線が場と同じ向きなら $\\theta=0^\\circ$ で $\\cos\\theta=1$ となり、通る量は最大になる。単位は T·m² = Wb で、掛けた2つの単位がそのまま残る。',
        },
        {
          id: 'p-umxav-2',
          difficulty: 2,
          question: '面を通る量を求めるとき、面に沿う向きの矢印を使って内積を取ると何が起きるか?',
          choices: [
            '正しい値が出る',
            '正しい値の2倍になる',
            '角の測り方がずれ、正面から貫く場合に $0$ と出てしまう',
            '単位が変わってしまう',
          ],
          answerIndex: 2,
          hint: '向きの代表に選ぶのは、面に垂直な矢印だった。',
          explanation: '向きの代表は**法線**であって、面に沿う矢印ではない。正面から貫く場合、法線なら $\\cos0^\\circ=1$ で最大だが、面に沿う矢印は場と直角なので $\\cos90^\\circ=0$ となり $0$ と出る。**法線でなく面に沿う矢印を使った**典型的な誤りだ。',
        },
        {
          id: 'p-umxav-3',
          difficulty: 2,
          question: 'ある面を通る量が $3$ Wb だった。法線を裏側に向け直すと、値はどうなるか?',
          choices: ['$3\\,\\mathrm{Wb}$', '$-3\\,\\mathrm{Wb}$', '$0\\,\\mathrm{Wb}$', '$6\\,\\mathrm{Wb}$'],
          answerIndex: 1,
          hint: '$\\vec n$ が $-1$ 倍になると、内積はどうなるか。',
          explanation: '法線を裏返すと $\\vec n$ が $-1$ 倍になり、内積もそのまま $-1$ 倍で **$-3$ Wb**。面も場も変えていないので大きさは同じだ。符号は**面の向きをどちらに決めたか**という約束だけで決まる。だから先に決めて途中で変えない。',
        },
        {
          id: 'p-umxav-4',
          difficulty: 2,
          question: '$d\\vec A=\\vec n\\,dA$ で、$\\vec n$ と $dA$ はそれぞれ何を担当するか?',
          choices: [
            '$\\vec n$ が面積、$dA$ が向き',
            '$\\vec n$ が向き（長さ1）、$dA$ が面積',
            'どちらも面積',
            'どちらも向き',
          ],
          answerIndex: 1,
          hint: '法線の長さはいくつと決めたか。',
          explanation: '$\\vec n$ は**長さ1**の矢印で向きだけを担当し、$dA$ が広さ [m²] を担当する。掛け合わせた $d\\vec A$ は、向きが法線・長さが面積の矢印になる。$\\vec n$ にも長さの意味を持たせると、面積を二重に数えてしまう。',
        },
        {
          id: 'p-umxav-5',
          difficulty: 3,
          question: '磁束密度 $2$ T、面積 $3$ m² の面を、法線が場と $60^\\circ$ をなすように置いた。通る量は?',
          choices: ['$6\\,\\mathrm{Wb}$', '$3\\,\\mathrm{Wb}$', '$5.2\\,\\mathrm{Wb}$', '$0\\,\\mathrm{Wb}$'],
          answerIndex: 1,
          hint: '$\\cos60^\\circ=0.5$。使う角は法線と場のなす角。',
          explanation: '$2\\times3\\times\\cos60^\\circ=2\\times3\\times0.5=3$ **Wb**。$6$ Wb は $\\cos\\theta$ を忘れて**大きさだけを掛けた**値。$5.2$ Wb は $\\sin60^\\circ$ を使った値で、角を面の傾きと取り違えている。$\\theta$ は**法線と場のなす角**だ。',
        },
      ],
    },

    // ================= 変化率が残りに比例する式 =================
    {
      id: 'um-simple-derivative-equation',
      title: '変化率が残りに比例する式',
      subtitle: '数値で1ステップずつ追う',
      enemy: { name: 'ディケイバット', emoji: '🦇', maxHp: 150 },
      theme: '変化率と今の量を結ぶ式を、言葉と数値で読む',
      goal: r`$\frac{dy}{dt}=-ky$ を「減り方が今の量に比例する」と読み、数値で1ステップずつ追って $y=y_0e^{-kt}$ の形へつなげられる。`,
      intro: '微分は、関数から変化率を作る操作だった。ここでは逆に、変化率の側に条件を付ける。「減る速さが、そのとき残っている量に比例する」。この一文を式にすると、何が決まるのだろう。',
      outro: '$\\frac{dy}{dt}=-ky$ は「減り方が今の量に比例する」という文の式だ。負号は減る向き、$k$ の単位は 1/s。数値で1ステップずつ追うと減り方がなだらかになり、行き先が $y=y_0e^{-kt}$ になる。導き方は上級で扱う。',
      foundation: {
        known: '変化率が「1秒あたりどれだけ変わるか」を表すこと。比例を掛け算で読めること。',
        startingPoint: '「減る速さが、そのとき残っている量に比例する」という言葉を、そのまま式にするところから出発する。',
        conditions: 'kは正の定数で、時間によらないとする。yは正の量とし、外から足されることはないものとする。',
        example: {
          given: 'y₀ = 100 g、k = 0.2 /s、Δt = 1 s で、1ステップだけ進める。',
          tex: r`\Delta y\approx-0.2\times100\times1=-20\,\mathrm{g}`,
          read: '1 s後はおよそ80 g。減った20 gが、そのときの量100 gに比例していることを確かめる。',
        },
      },
      glossary: {
        y: 'いま残っている量。この章では質量 [g]',
        y_0: '時刻0での量 [g]。数値計算の出発点',
        'yᵢ': 'iステップ目の量 [g]。i=0が出発点',
        k: '減りやすさを表す正の定数 [1/s]。1秒あたりの割合の目安',
        'dy/dt': 'yの時間変化率 [g/s]。負なら減っている',
        'Δt': '数値計算で1回に進める時間の刻み [s]',
        'Δy': '1ステップでの量の変化 [g]。この章では負の値',
        e: '自然対数の底、約2.718。指数関数の土台になる数',
        T: '量が半分になるまでの時間、半減期 [s]',
        t: '経過時間 [s]。kの単位とそろえる',
      },
      units: [
        { end: 4, goal: '言葉を式にし、負号とkの単位を読む', gain: 'dy/dt=−kyは「減り方が今の量に比例する」の式。負号は減る向き、kの単位は1/s。' },
        { end: 7, goal: '数値で1ステップずつ進める', gain: 'Δy≈−kyΔtで次の値を出す。100→80→64と、減る幅そのものが小さくなっていく。' },
        { end: 10, goal: '刻みを細かくして、行き先の形を予告する', gain: 'Δtを小さくすると値が落ち着く。行き先は指数関数の形で、導き方は上級で扱う。' },
      ],
      slides: [
        {
          heading: '変化率は、どんな量を表していたろう?',
          beat: '基本事項',
          role: '観察',
          figure: 'umx-ode-rate-recall',
          body: '$\\frac{dy}{dt}$ は、$y$ が1秒あたりどれだけ変わるかを表す。$y$ が g、$t$ が s なら単位は g/s。負なら減っている。',
          formulaNote: '変化率の符号が、増えるか減るかを表す',
        },
        {
          heading: '「減り方が今の量に比例する」を式にしよう',
          beat: '解決',
          role: '操作',
          figure: 'umx-ode-proportional',
          body: '残りが多いほど速く減り、少なくなればゆっくり減る。この文を式にすると、変化率が $y$ に比例する。比例定数を $k$ として $\\frac{dy}{dt}=-ky$。',
          formula: r`\frac{dy}{dt}=-ky`,
          formulaNote: '右辺に今の量yが入っているのが、この式の特徴',
        },
        {
          heading: '負号は、何を言っているのだろう?',
          beat: '解決',
          role: '解釈',
          figure: 'umx-ode-minus-sign',
          body: '$k$ は正、$y$ も正なので、右辺 $-ky$ は必ず負になる。つまり $y$ は減り続ける。負号は減る向きだけを表している。',
          formulaNote: '負号を外すと増え続ける式になり、意味が変わる',
        },
        {
          heading: '$k$ の単位は、何になるはずだろう?',
          beat: '解決',
          role: '操作',
          figure: 'umx-ode-k-unit',
          body: '左辺は g/s、右辺の $y$ は g。両辺の単位をそろえると、$k$ は 1/s になる。$k=0.2$ /s は1秒あたり2割の目安だ。',
          formulaNote: 'kの単位は1/s。量の単位を持たない割合',
          calculation: [
            { note: '両辺の単位だけを並べて書く', tex: r`\mathrm{g/s}=[k]\times\mathrm{g}` },
            { note: '両辺を g で割って k の単位を出す', tex: r`[k]=\mathrm{1/s}` },
          ],
        },
        {
          heading: '次の瞬間の量を、どう計算すればよいのだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'umx-ode-next-step-q',
          body: 'この式が教えるのは $y$ の変わり方だけだ。出発点の量が分かっているとき、その先をどう追えばよいのだろう。',
        },
        {
          heading: '小さな時間だけ進めると、いくら減るだろう?',
          beat: '解決',
          role: '操作',
          figure: 'umx-ode-euler-step',
          body: '短い $\\Delta t$ の間は、変化率を一定とみなせる。減る量は $\\Delta y\\approx-k\\,y_i\\,\\Delta t$。今の値 $y_i$ に足せば次の値が出る。',
          formula: r`y_{i+1}\approx y_i(1-k\,\Delta t)`,
          formulaNote: 'iはステップの番号。Δtが短いほど近似がよい',
          calculation: [
            { note: '変化率に、進める時間の刻みを掛ける', tex: r`\Delta y\approx-k\,y_i\,\Delta t` },
            { note: '今の値に足して、次の値の形にまとめる', tex: r`y_{i+1}\approx y_i(1-k\,\Delta t)` },
          ],
        },
        {
          heading: '1ステップずつ表にすると、どう減るだろう?',
          beat: '解決',
          role: '観察',
          figure: 'umx-ode-table',
          body: '$y_0=100$ g、$k=0.2$ /s、$\\Delta t=1$ s なら $1-k\\Delta t=0.8$。掛け続けると 100、80、64、51.2、40.96 g と減る。',
          formulaNote: '毎回0.8倍。減る幅そのものが減っていく',
        },
        {
          heading: '刻みを細かくすると、値はどう変わるだろう?',
          beat: '疑問',
          role: '問い',
          figure: 'umx-ode-finer',
          body: '$\\Delta t=1$ s では4 s後が 40.96 g。$0.5$ s 刻みなら 43.05 g、$0.25$ s 刻みなら 44.01 g。細かいほど値が上がる。',
        },
        {
          heading: '減り方をグラフにすると、どんな形だろう?',
          beat: '解決',
          role: '観察',
          figure: 'umx-ode-curve',
          body: '行き先をつなぐと、はじめ急で次第になだらかな曲線になる。100 g から 50 g、50 g から 25 g にかかる時間は、どちらも約 3.5 s だ。',
          formulaNote: '同じ割合で減るので、半分になる時間はいつも同じ',
        },
        {
          heading: 'この減り方の曲線は、どんな式で書けるのだろう?',
          beat: '新しい基本事項',
          role: '固定',
          figure: 'umx-ode-exponential',
          body: '毎回同じ割合を掛け続けた行き先は、指数関数になる。答えは $y=y_0e^{-kt}$ の形だ。どう導くかは上級で扱う。',
          formula: r`y=y_0e^{-kt}`,
          formulaNote: 'eは約2.718。t=0でy₀、以後は同じ割合で減る',
        },
      ],
      preview: {
        goal: r`y=y_0e^{-kt}`,
        now: '式を言葉で読み、数値で1ステップずつ追うこと',
        later: '変数分離で解く手順、初期条件の使い方、振動を表す微分方程式',
      },
      leadsTo: ['um-ode', 'um-derivative'],
      problems: [
        {
          id: 'p-umxsd-1',
          difficulty: 1,
          question: '$\\frac{dy}{dt}=-ky$ は、言葉でいうと何を言っているか?',
          choices: [
            '量が一定の速さで減る',
            '減る速さが、そのとき残っている量に比例する',
            '量が時間に比例して増える',
            '量が一定に保たれる',
          ],
          answerIndex: 1,
          hint: '右辺に入っているのは何かを見る。',
          explanation: '右辺に**今の量 $y$ が入っている**のが、この式の特徴だ。$y$ が大きいほど減り方も大きく、$y$ が小さくなれば減り方もゆるむ。一定の速さで減るなら右辺は定数になり、$y$ は現れない。',
        },
        {
          id: 'p-umxsd-2',
          difficulty: 2,
          question: '$y$ が g、$t$ が s のとき、$k$ の単位は?',
          choices: ['g', 'g/s', '1/s', 's'],
          answerIndex: 2,
          hint: '両辺の単位がそろうように決める。',
          explanation: '左辺 $\\frac{dy}{dt}$ は g/s、右辺の $y$ は g。g/s = [k] × g の両辺を g で割ると [k] = 1/s。**$k$ は量の単位を持たず、1秒あたりの割合**を表す。単位をそろえる作業が、$k$ の意味も教えてくれる。',
        },
        {
          id: 'p-umxsd-3',
          difficulty: 2,
          question: '$k>0$、$y>0$ のとき、$\\frac{dy}{dt}$ の符号は?',
          choices: ['正', '負', '0', '$t$ によって入れ替わる'],
          answerIndex: 1,
          hint: '$-ky$ の符号をそのまま読む。',
          explanation: '$k$ も $y$ も正なので $-ky$ は**負**。よって $y$ は減り続ける。負号を落とすと増え続ける式になり、意味が正反対になる。$y$ が0に近づくと変化率も0に近づくので、0を割り込むことはない。',
        },
        {
          id: 'p-umxsd-4',
          difficulty: 2,
          question: '$y_0=100$ g、$k=0.2$ /s、$\\Delta t=1$ s で1ステップ進めたときの量は?',
          choices: ['$80\\,\\mathrm{g}$', '$99.8\\,\\mathrm{g}$', '$20\\,\\mathrm{g}$', '$120\\,\\mathrm{g}$'],
          answerIndex: 0,
          hint: '$\\Delta y\\approx-k\\,y\\,\\Delta t$ を、今の量に足す。',
          explanation: '$\\Delta y\\approx-0.2\\times100\\times1=-20$ g なので、$100-20=80$ **g**。$20$ g は減った分そのもので、残りではない。$120$ g は負号を落とした結果。**変化分と残量を取り違えない**ことが要点だ。',
        },
        {
          id: 'p-umxsd-5',
          difficulty: 3,
          question: '同じ条件で $\\Delta t$ を小さくしていくと、4 s 後の計算値はどうなるか?',
          choices: [
            '小さくなり続ける',
            '大きくなり、ある値に落ち着く',
            'まったく変わらない',
            '毎回大きく振れて定まらない',
          ],
          answerIndex: 1,
          hint: '1ステップの間ずっと同じ変化率を使う無理は、刻みが粗いほど大きい。',
          explanation: '刻みが粗いと、ステップの間ずっと最初の大きい減り方を使うので減らし過ぎる。刻みを細かくすると 40.96、43.05、44.01 g と**上がって 44.93 g に落ち着く**。この行き先が $y=y_0e^{-kt}$ の値だ。',
        },
      ],
    },
  ],
};
