const r=String.raw;
export type EquationGuide={kind:string;read:string;symbols:[string,string][];steps:{note:string;tex:string}[]};
const s=(note:string,tex:string)=>({note,tex});
const g=(kind:string,read:string,symbols:[string,string][],...steps:{note:string;tex:string}[]):EquationGuide=>({kind,read,symbols,steps});
const work:[string,string][]=[['W','仕事 [J]'],['F','移動方向の力 [N]'],['L','移動距離 [m]']];
const sum:[string,string][]=[...work,['N','分ける区間の個数'],['i','区間の番号'],['Σ','指定した番号の項を全部足す'],['Wₙ','N分割して求めた仕事の近似値']];
const path:[string,string][]=[['r(u)','目盛りuで指定した位置 [m]'],['u','道に付けた無次元の目盛り。時間とは限らない'],['L・H','道の横幅・高さ [m]'],['r′(u)','uあたりの位置の変化 [m]'],['du・dr','微小な目盛りの変化・それに対応する移動']];
const field:[string,string][]=[['E','電場 [N/C = V/m]。矢印付きはベクトル'],['q','運ぶ電荷 [C]。電子では−e'],['e','正の電気素量 [C]'],['·','対応する成分同士の積を足す内積'],['W','電気力がする仕事 [J]']];
const surface:[string,string][]=[['ΦE','電気束 [N·m²/C]。仕事ではない'],['n','面に垂直な長さ1のベクトル'],['dA','小さな面積 [m²]'],['dA（矢印付き）','向きnと面積dAを組にしたベクトル'],['S','集計する面'],['θ','電場と法線のなす角']];
const sphere:[string,string][]=[['R','球の半径 [m]'],['θ','中心で測る、上向きの軸からの角度 [rad]'],['φ','軸の周りを回る方向の角度 [rad]'],['dθ・dφ','それぞれの角度の微小な変化。dという数との掛け算ではない'],['A・dA','球面全体の面積・細かく区切った一つ分の微小な面積 [m²]'],['rad（ラジアン）','弧の長さ÷半径で測る角度。半周はπ、一周は2π']];

/** One guide per card, including equations introduced in prose and diagrams. */
export const integralEquationGuides:Record<string,[EquationGuide,EquationGuide,EquationGuide]>={
 work:[
  g('定義の使い方','同じ向きの一定力なら、仕事＝力×距離。',work,
   s('仕事の定義を、一定の力と直線移動に使う。',r`W=FL`),
   s('本文の例はF=2N、L=3m。図のスライダーを動かした値とは区別する。',r`W=(2\,\mathrm N)(3\,\mathrm m)=6\,\mathrm J`)),
  g('足し算の表記','Σは「一区間の仕事」をN個足す、という意味。',sum,
   s('長さ3mをN等分する。Δは有限の小さな差を表す。',r`\Delta x=\frac{3}{N}\,\mathrm m`),
   s('どの区間でも力は2N。一区間の仕事は高さ×幅。',r`\Delta W_i=2\frac3N\,\mathrm J`),
   s('i=1からNまで、同じ値をN回足す。',r`W_N=\sum_{i=1}^{N}2\frac3N=N\times2\frac3N=6\,\mathrm J`)),
  g('積分の定義','∫は小区間の和の極限。[ ]は「上端の値−下端の値」。',[...sum,['dx','積分で使う微小な位置の幅'],['[G(x)]ₐᵇ','G(b)−G(a)']],
   s('何分割でも6。分割を限りなく細かくしても6。数値はSI単位で計算する。',r`\int_0^3 2\,dx=\lim_{N\to\infty}\sum_{i=1}^N2\frac3N=6`),
   s('2xは、微分すると2になる関数（原始関数）。',r`\frac{d}{dx}(2x)=2`),
   s('この例では原始関数の両端の差も、同じ6になる。',r`[2x]_0^3=2\cdot3-2\cdot0=6`)),
 ],
 linear:[
  g('今回の力・近似','左端で測った力×区間の幅。それを全部足した式です。',[...sum,['k','距離1mあたりの力の増え方 [N/m]'],['F(x)=kx','今回選んだ、距離に比例して増える力']],
   s('全長LをN等分。区間番号は0からN−1で、全部でN個。',r`\Delta x=\frac LN,\qquad i=0,1,\ldots,N-1`),
   s('i番目の左端は、幅をi個分進んだ位置。そこで力を測る。',r`x_i=i\Delta x=\frac{iL}{N},\qquad F(x_i)=k\frac{iL}{N}`),
   s('実際の力は区間内でも変わる。左端の高さの長方形で近似する。',r`\Delta W_i\approx F(x_i)\Delta x=k\frac{iL}{N}\frac LN`),
   s('近似値Wₙを、このN個の長方形の合計として定める。',r`W_N=\sum_{i=0}^{N-1}\underbrace{k\frac{iL}{N}}_{\text{高さ}}\underbrace{\frac LN}_{\text{幅}}`)),
  g('過大評価の確認','最後の力を全区間に使うと、実際より大きい長方形になる。',[...work,['k','力の増え方 [N/m]'],['W長方形','比較用の面積。実際の仕事ではない']],
   s('終点の力は、F(x)=kxにx=Lを代入する。',r`F(L)=kL`),
   s('この高さを道全体に使うと、Lが二つ掛かる。',r`W_{\rm 長方形}=F(L)L=(kL)L=kL^2`)),
  g('導いた結果','区間の和を細かくすると、三角形の面積kL²/2になる。',[...sum,['k','力の増え方 [N/m]'],['∫₀ᴸ','0からLまで集計する']],
   s('iによらない係数を、足し算の外へ出す。',r`W_N=\frac{kL^2}{N^2}\sum_{i=0}^{N-1}i`),
   s('0〜N−1を逆順に並べて足すと、各組がN−1。二重に数えたので2で割る。',r`2\sum_{i=0}^{N-1}i=N(N-1)`),
   s('代入して約分。Nを大きくすると1/Nが0へ近づく。',r`W_N=\frac{kL^2}{2}\left(1-\frac1N\right)\ \longrightarrow\ \frac{kL^2}{2}`),
   s('原始関数でも確認。微分でkxに戻るので、両端の差で積分を計算できる（微積分の基本定理）。',r`\frac{d}{dx}\frac{kx^2}{2}=kx,\qquad\int_0^Lkx\,dx=\left[\frac{kx^2}{2}\right]_0^L=\frac{kL^2}{2}`)),
 ],
 projection:[
  g('電場の定義','電場は「電荷1Cあたりの力」。実際の力は電荷を掛ける。',field,
   s('電場を測る小さな試験電荷q₀に働く力を、q₀で割って定義する。',r`\vec E=\frac{\vec F_0}{q_0}`),
   s('同じ場に置いた電荷qへの力。電子のqは負なので向きが反転する。',r`\vec F=q\vec E,\qquad q=-e\ \Rightarrow\ \vec F=-e\vec E`)),
  g('内積の意味','力のうち、移動方向に向く成分だけを使う。',[...work,['θ','力と移動のなす角'],['s','ここでの直線移動距離 [m]']],
   s('直角三角形で、隣辺＝斜辺×cosθ。力の投影にも同じ関係を使う。',r`F_{\parallel}=F\cos\theta`),
   s('移動方向の成分に距離を掛ける。力が一定の一歩についての式。',r`W=F_{\parallel}s=Fs\cos\theta=\vec F\cdot\Delta\vec r`),
   s('直角では投影が0。力そのものが0という意味ではない。',r`\theta=\frac\pi2\ \Rightarrow\ \cos\theta=0\ \Rightarrow\ W=0`)),
  g('定義をつなぐ','「力×移動」の内積に、電気力qEを代入しただけ。',[...field,['dr','向きも含む微小な移動 [m]'],['ds','その移動の長さ [m]'],['θ','電場Eと移動drの角度']],
   s('小さな移動での仕事を、力と移動の内積で表す。',r`dW=\vec F\cdot d\vec r`),
   s('電気力F=qEを代入する。',r`dW=(q\vec E)\cdot d\vec r=q\vec E\cdot d\vec r`),
   s('内積＝二つの長さ×cosθ。qの符号はそのまま残す。',r`dW=qE\,ds\cos\theta`)),
 ],
 path:[
  g('線積分の定義','道Cに沿って、一歩ごとの仕事を足す。',[...field,['C','指定した道'],['dr','各点での微小な移動']],
   s('曲がる道を短い区間に分け、その場所の電場を使う。',r`W\approx\sum_i q\vec E(\vec r_i)\cdot\Delta\vec r_i`),
   s('どの区間も限りなく短くした和を、線積分と書く。',r`W=\int_C q\vec E\cdot d\vec r`)),
  g('今回の道・微分','位置の式を成分ごとに微分し、小さな目盛りの変化を掛ける。',path,
   s('横はuに比例、縦はu²に比例する道を選んだ。物理法則ではなく、今回の設定。',r`\vec r(u)=(Lu,Hu^2),\qquad 0\le u\le1`),
   s('uをhだけ進めた実際の移動は、二つの位置の差。hは有限の刻み。',r`\vec r(u+h)-\vec r(u)=(Lh,\,2Huh+Hh^2)`),
   s('hで割ると「目盛りあたりの変化」。h→0で微分を定義する。',r`\vec r'(u)=\lim_{h\to0}(L,\,2Hu+Hh)=(L,2Hu)`),
   s('有限の一歩は接線で近似。微分の表記では、微小な変化をdu・drと書く。',r`\Delta\vec r\approx\vec r'(u)\Delta u,\qquad d\vec r=\vec r'(u)du=(L,2Hu)du`)),
  g('代入して計算','縦の電場が0だから、横の移動だけが仕事に残る。',[...path,...field,['E₀','今回の一定な横向き電場 [N/C]']],
   s('線積分を道の目盛りuで書く。場と移動の両方に、同じ道を使う。',r`W=\int_0^1q\vec E(\vec r(u))\cdot\vec r'(u)\,du`),
   s('内積は、横同士の積＋縦同士の積。',r`(E_0,0)\cdot(L,2Hu)=E_0L+0\cdot2Hu=E_0L`),
   s('uによらない定数なので、目盛りの幅1−0を掛ける。',r`W=qE_0L\int_0^1du=qE_0L(1-0)=qE_0L`)),
 ],
 'variable-path':[
  g('今回の場・代入','E(r(u))は「道の各位置で電場を調べる」という意味。',[...path,...field,['α','位置に対する電場の増え方 [V/m²]']],
   s('計算練習として、この二次元の場を選ぶ。x,yは位置の成分。',r`\vec E(x,y)=(\alpha x,\alpha y)`),
   s('道の式から、横と縦の座標を読む。',r`x=Lu,\qquad y=Hu^2`),
   s('場のxとyを、その座標で置き換える。',r`\vec E(\vec r(u))=(\alpha Lu,\alpha Hu^2)`)),
  g('内積を展開','横同士・縦同士を掛けて足すと、uとu³の積分になる。',[...path,...field,['α','電場の増え方 [V/m²]']],
   s('電子のq=−eと、場・移動の式を代入。',r`dW=-e(\alpha Lu,\alpha Hu^2)\cdot(L,2Hu)\,du`),
   s('横の積はαL²u、縦の積は2αH²u³。',r`dW=-e\left(\alpha L^2u+2\alpha H^2u^3\right)du`),
   s('両方の項にあるαを括弧の外へ出す。',r`dW=-e\alpha(L^2u+2H^2u^3)du`)),
  g('積分した結果','微分すると元に戻る関数を探し、両端の差を取る。',[...path,...field,['α','電場の増え方 [V/m²]'],['v','積分の中だけで使う目盛り'],['eV','エネルギーの単位。1eVは電気素量×1V']],
   s('現在位置uまでの和。積分の中の目盛りをvと呼び、終点uと区別する。',r`W(u)=-e\alpha\int_0^u(L^2v+2H^2v^3)dv`),
   s('微分で確かめる。v²/2はvに、v⁴/4はv³に戻る。',r`\frac d{dv}\frac{v^2}{2}=v,\qquad\frac d{dv}\frac{v^4}{4}=v^3`),
   s('項ごとに積分し、2×1/4=1/2を使う。下端0の値は0。',r`W(u)=-e\alpha\left[\frac{L^2v^2}{2}+\frac{H^2v^4}{2}\right]_0^u=-e\alpha\left(\frac{L^2u^2}{2}+\frac{H^2u^4}{2}\right)`),
   s('図の設定L=H=1m、α=1V/m²、終点u=1。負号は電気力が運ぶ向きに逆らうことを表す。',r`W(1)=-e\cdot1\,\mathrm V=-1\,\mathrm{eV}`)),
 ],
 potential:[
  g('別の道で計算','この場では、直線も放物線も終点で仕事が一致する。',[...path,...field,['α','電場の増え方 [V/m²]']],
   s('比較用の直線を選び、道の微分と場への代入をやり直す。',r`\vec r(u)=(Lu,Hu),\quad\vec r'(u)=(L,H),\quad\vec E=(\alpha Lu,\alpha Hu)`),
   s('電子の仕事を内積で書き、定数を積分の外へ出す。',r`W=-e\alpha(L^2+H^2)\int_0^1u\,du`),
   s('積分は1/2。放物線の終点の答えに一致する。',r`W=-\frac{e\alpha}{2}(L^2+H^2)=W_{\rm 放物線}`)),
  g('保存性・位置エネルギー','この場の仕事が端点だけで決まるので、位置ごとにエネルギーを割り当てられる。',[...field,['U','位置エネルギー [J]'],['A・B','移動の始点・終点'],['α','この場の定数 [V/m²]']],
   s('この場では電気力の仕事を、x方向とy方向に分けて足せる。',r`dW=q\alpha(x\,dx+y\,dy)`),
   s('x dxはx²/2の微分。yも同じなので、どの道でも端点だけが残る。',r`W_{A\to B}=\frac{q\alpha}{2}\left[(x_B^2+y_B^2)-(x_A^2+y_A^2)\right]`),
   s('保存力が正の仕事をした分、位置エネルギーは減る、という定義を使う。',r`U_B-U_A=-W_{A\to B}`)),
  g('電位の定義','電位は単位電荷あたりの位置エネルギー。負号はエネルギーの減少から来る。',[...field,['V','電位 [V = J/C]'],['U','位置エネルギー [J]'],['A・B','始点・終点'],['∮C','閉じた道を一周する線積分']],
   s('q≠0として位置エネルギーを電荷で割り、電位を定義する。',r`V=\frac Uq,\qquad V_B-V_A=\frac{U_B-U_A}{q}`),
   s('ΔU=−Wと、電気力の仕事の式を代入。qを約分する。',r`V_B-V_A=-\frac1q\int_A^B q\vec E\cdot d\vec r=-\int_A^B\vec E\cdot d\vec r`),
   s('静電場で一周して同じ点に戻れば電位差は0。変化する磁場がある場合へはそのまま使えない。',r`A=B\ \Rightarrow\ \oint_C\vec E\cdot d\vec r=0`)),
 ],
 surface:[
  g('磁束の復習・電気束の定義','磁場でも電場でも、面に垂直な成分×面積を足す。',[...surface,['B','磁束密度 [T]。元の図は磁場'],['ΦB','磁束 [Wb]'],['E','電場 [N/C]']],
   s('一様な磁場と平面では、法線方向の成分はBcosθ。',r`\Phi_B=(B\cos\theta)A`),
   s('同じ集計を電場に定義する。磁束とは違う物理量で、単位も違う。',r`\Phi_E=(E\cos\theta)A`),
   s('曲面や不均一な場では、小片に分けて内積を足す。',r`\Phi_E=\int_S\vec E\cdot\vec n\,dA`)),
  g('面積ベクトルの定義','面積だけでは向きが欠けるので、法線nを組にする。',surface,
   s('単位法線nの長さは1。面積dAを掛けても、大きさはdAのまま。',r`|\vec n|=1,\qquad d\vec A=\vec n\,dA`),
   s('場との内積を取ると、法線方向の成分が取り出される。',r`\vec E\cdot d\vec A=\vec E\cdot\vec n\,dA=E\cos\theta\,dA`),
   s('法線を逆にすると寄与の符号も逆。閉曲面では外向きを使う。',r`\vec n\to-\vec n\ \Rightarrow\ d\Phi_E\to-d\Phi_E`)),
  g('面積分の定義','小片ごとの電気束を足した極限。条件がそろえば高校の掛け算に戻る。',surface,
   s('小片の電気束は法線方向の場×小面積。',r`d\Phi_E=\vec E\cdot\vec n\,dA`),
   s('全面Sで足す。道を足す線積分とは、集計する対象が違う。',r`\Phi_E=\int_S\vec E\cdot\vec n\,dA`),
   s('Eとθが全面で同じときだけ、定数として積分の外へ出せる。',r`\Phi_E=E\cos\theta\int_SdA=EA\cos\theta`)),
 ],
 double:[
  g('今回の場と面','上向きの面を貫くのは、電場のz成分だけ。',[...surface,['β','電場の増え方 [V/m²]'],['x・y・z','空間の座標 [m]'],['L','正方形の一辺 [m]']],
   s('今回の場と、上向きの単位法線を成分で書く。',r`\vec E=\beta(z,0,x),\qquad\vec n=(0,0,1)`),
   s('内積は対応する成分同士の積の和。z=0の面でも、場のz成分βxは残る。',r`\vec E\cdot\vec n=\beta z\cdot0+0\cdot0+\beta x\cdot1=\beta x`)),
  g('内側の積分','まず横方向の一列を足す。まだ面全体の電気束ではない。',[...surface,['β','電場の増え方 [V/m²]'],['L','正方形の一辺 [m]'],['dx dy','縦横の小幅を掛けた面積']],
   s('平面の小面積はdx dy。xもyも0からLまで動かす。',r`\Phi_E=\int_0^L\left(\int_0^L\beta x\,dx\right)dy`),
   s('βは定数。xの原始関数x²/2を使い、両端の差を取る。',r`\int_0^L\beta x\,dx=\beta\left[\frac{x^2}{2}\right]_0^L=\frac{\beta L^2}{2}`),
   s('この値に、帯の幅dyを掛けたものが薄い一帯の電気束。',r`d\Phi_E=\frac{\beta L^2}{2}\,dy`)),
  g('二重積分の結果','一帯の集計を、もう一方向にも足す。',[...surface,['β','電場の増え方 [V/m²]'],['L','正方形の一辺 [m]'],['y','二回目に集計する位置']],
   s('前の段で計算した内側の積分を代入。yによらないので定数。',r`\Phi_E=\int_0^L\frac{\beta L^2}{2}\,dy`),
   s('一定値の積分は、一定値×範囲の長さ。',r`\Phi_E=\frac{\beta L^2}{2}[y]_0^L=\frac{\beta L^2}{2}(L-0)=\frac{\beta L^3}{2}`),
   s('L³があっても体積ではない。βの単位と合わせて電気束の単位になる。',r`\frac{\mathrm V}{\mathrm m^2}\,\mathrm m^3=\mathrm{V\,m}=\frac{\mathrm{N\,m^2}}{\mathrm C}`)),
 ],
 'sphere-area':[
  g('角度から長さへ','Δは二点間の変化。まず普通の長さを計算し、その関係を微分で表す。',[['R','青い円の半径 [m]。図の例は2 m'],['Δθ','二本の半径の間の角度 [rad]。位置の角度θとは別'],['Δs','二点間を円周に沿って進む長さ [m]。直線距離ではない'],['rad（ラジアン）','弧の長さ÷半径で測る角度。度数をそのまま代入しない'],...sphere.slice(1,5),['s・ds','円周に沿った長さ・その微小な変化 [m]']],
   s('ラジアンの定義。弧が半径と同じ長さなら角度は1 rad。',r`\Delta\theta=\frac{\Delta s}{R}`),
   s('両辺に同じ半径Rを掛け、右辺のRを約分する。',r`R\,\Delta\theta=R\frac{\Delta s}{R}=\Delta s`),
   s('半径2 m、角度の変化0.1 radなら、表面に沿った長さは0.2 m。',r`\Delta s=(2\,\mathrm m)\times0.1=0.2\,\mathrm m`),
   s('半径は一定。角度あたりの長さの変化は、区間を縮めてもR。極限を微分と呼ぶ。',r`\frac{ds}{d\theta}=\lim_{\Delta\theta\to0}\frac{\Delta s}{\Delta\theta}=R`),
   s('微分の関係をds＝R dθと書く。dsは微小な長さ、dθは対応する角度の微小な変化。',r`ds=R\,d\theta`),
   s('θは北極から南極まで半周、φは軸の周りに一周。',r`0\le\theta\le\pi,\qquad0\le\varphi\le2\pi`)),
  g('表面を区切った一つ分の面積','縦と横の長さを掛ける前に、それぞれが通る円の半径を確かめる。',[['ρ','同じ高さを一周する金色の輪の半径 [m]'],['dsθ・dsφ','球の表面に沿う、縦・横の微小な長さ [m]'],...sphere],
   s('軸を含む断面の直角三角形で、sinθ＝輪の半径÷球の半径。',r`\sin\theta=\frac\rho R\ \Rightarrow\ \rho=R\sin\theta`),
   s('弧の長さ＝半径×角度を、縦と横それぞれに使う。',r`ds_\theta=R\,d\theta,\qquad ds_\varphi=\rho\,d\varphi=R\sin\theta\,d\varphi`),
   s('小さく区切るほど長方形に近づく。極限で縦×横が微小な面積dAになる。',r`dA=(R\,d\theta)(R\sin\theta\,d\varphi)=R^2\sin\theta\,d\theta\,d\varphi`)),
  g('球面積を導く','θ方向の積分は2、φ方向は2π。R²と掛けて4πR²。',sphere,
   s('小面積の式を、球全体の角度の範囲で積分する。',r`A=R^2\int_0^{2\pi}\int_0^\pi\sin\theta\,d\theta\,d\varphi`),
   s('−cosθを微分するとsinθ。cos0=1、cosπ=−1を使う。',r`\int_0^\pi\sin\theta\,d\theta=[-\cos\theta]_0^\pi=1-(-1)=2`),
   s('残りは一定値の積分。0から2πまでの幅を掛ける。',r`A=2R^2\int_0^{2\pi}d\varphi=2R^2(2\pi-0)=4\pi R^2`)),
 ],
};
