export type Faq = {question:string; lines:[string,string,string,string]; sources:string[]};
export const faqSources:Record<string,{title:string;url:string}>={
 research:{title:'学習者の対称性・ガウスの法則の理解（教育研究）',url:'https://arxiv.org/abs/1602.07376'},
 line:{title:'OpenStax：線積分の定義と計算',url:'https://openstax.org/books/calculus-volume-3/pages/6-2-line-integrals'},
 surface:{title:'OpenStax：面積分と向き',url:'https://openstax.org/books/calculus-volume-3/pages/6-6-surface-integrals'},
 questions:{title:'OpenStax：電気束・ガウスの法則の概念問題',url:'https://openstax.org/books/university-physics-volume-2/pages/6-conceptual-questions'},
 potential:{title:'OpenStax：電位差と仕事',url:'https://openstax.org/books/university-physics-volume-2/pages/7-2-electric-potential-and-potential-difference'},
 feynman:{title:'Feynman Lectures：静電場の出発点と証明',url:'https://www.feynmanlectures.caltech.edu/II_04.html'},
 offsetQuestion:{title:'実際の質問：中心からずれた電荷',url:'https://physics.stackexchange.com/questions/108511/why-does-gausss-law-work-for-a-charge-off-center-in-a-spherical-surface'},
 signQuestion:{title:'実際の質問：線積分のマイナス符号',url:'https://physics.stackexchange.com/questions/436432/potential-difference-from-electric-field-and-line-integral'},
 areaQuestion:{title:'実際の質問：なぜ面積がベクトル？',url:'https://physics.stackexchange.com/questions/14165/how-can-area-be-a-vector'},
 cavityQuestion:{title:'実際の質問：導体内部と空洞の違い',url:'https://physics.stackexchange.com/questions/758903/electric-field-inside-conductor-with-a-cavity'},
};
const f=(question:string,lines:Faq['lines'],...sources:string[]):Faq=>({question,lines,sources});
// Questions are original Japanese formulations, not translations of posted answers.
// Community posts identify confusions; textbooks/research check the explanations.
export const emFaq:Record<string,Faq>={
 'r-map':f('線積分と面積分は、何が違う？',['仕事は「道に沿う移動」を足します。','電気束は「面を貫く成分」を足します。','同じ電場でも、集める対象が違います。','図の金色が、足し合わせる場所です。'],'line','surface'),
 'r-field':f('電子は電場の矢印に沿って進む？',['電場が決めるのは力で、速度ではありません。','電子の力は、電場とは逆向きです。','初速度もあるので、軌道は別に求めます。','この図は一様電場での自由運動の例です。'],'feynman'),
 'r-dot':f('垂直な力もあるのに、仕事は0？',['仕事に効くのは移動方向の成分です。','垂直な成分との内積は0になります。','力が0、という意味ではありません。','角度を変えて、投影の長さを比べます。'],'line'),
 'r-work':f('電気力の仕事が負なら、必ず減速？',['速度の変化は、合力の仕事で決まります。','外力が正の仕事をする場合もあります。','二つの仕事を足して判断してください。','図では外力の仕事だけを変えています。'],'potential'),
 'r-sum':f('小片に分けると、なぜ正確になる？',['各小片で、電場を一定として近似します。','細かくすると、その近似の差が減ります。','連続な場で極限を取るのが線積分です。','有限個の和は、まだ近似値です。'],'line'),
 'r-path':f('道の目盛りuは、時間なの？',['uは道の位置を指定するための変数です。','この章では、時間とは決めていません。','同じ道を別の目盛りでも表せます。','微分と積分範囲も一緒に変えます。'],'line'),
 'r-power':f('なぜ積分は、原始関数の差になる？',['小区間ごとの増分を順番に足します。','途中の端点の値が、正負で消えます。','最後に、終点の値−始点の値が残ります。','連続性が、和の極限との一致を支えます。'],'line'),
 'r-calculate':f('仕事のグラフが下がるのは間違い？',['ここで描くのは電気力がした仕事です。','指定した移動と電子の力は逆向きです。','だから、小区間の仕事は負になります。','累積値も0から負の側へ下がります。'],'potential','signQuestion'),
 'r-compare':f('遠回りしたら仕事は増えないの？',['距離だけでなく、力との内積を足します。','この静電場では、端点だけで決まります。','途中までの累積仕事は違ってかまいません。','一般のベクトル場では経路も効きます。'],'line','potential'),
 'r-voltage':f('電位が下がるのに、電子のエネルギーは増える？',['位置エネルギーは、電荷×電位です。','電子の電荷にはマイナスが付きます。','電位差が負なら、エネルギー差は正です。','電位とエネルギーは別の量です。'],'potential','signQuestion'),
 'r-flux':f('電気束は、電気が流れる量なの？',['電気束は、電場の面積分という量です。','電荷の移動量や、電流とは違います。','静止した電荷の場でも定義できます。','図は面だけを回し、電場は固定します。'],'surface','questions'),
 'r-patches':f('電場が場所で違うと、積分できない？',['むしろ、その違いを足すための積分です。','各小片で、電場と法線の内積を取ります。','値が違えば、共通因数にできないだけです。','色の違う小片を一つずつ見てください。'],'surface','research'),
 'r-area':f('面積に、どうして向きがある？',['面積の数値だけでは傾きが分かりません。','垂直な向きも組にして面を表します。','法線を反転すると電気束の符号が逆です。','面積そのものが負になるわけではありません。'],'surface','areaQuestion'),
 'r-spherearea':f('球面の小面積に、なぜsinθが付く？',['極の近くでは緯線の輪が小さくなります。','同じ経度差でも、横幅が短くなります。','その緯線半径がR sinθです。','赤道へ動かすと、輪が最大になります。'],'surface'),
 'r-surfacecalc':f('なぜ積分を二回するの？',['面上の場所には、二つの目盛りが必要です。','まず横に足して、一本の帯を集計します。','次に、その帯を縦に足します。','同じ面を二重に数えるわけではありません。'],'surface'),
 'g-contract':f('球で確かめたら、証明は終わり？',['球の計算だけでは、一般の面は未証明です。','面の小片を立体角に対応させます。','出入りの符号も数えて全方向を足します。','その後に、複数の電荷へ広げます。'],'feynman'),
 'g-offset':f('面をずらすと、電場が変わる？',['電荷と観測点Pを固定すれば変わりません。','変わるのは、選んだ面の場所や法線です。','別の場所の電場を集計することになります。','図のPの青い矢印は固定したままです。'],'research','offsetQuestion'),
 'g-offsetintegrand':f('電場と法線は、同じ向きでは？',['電場は電荷から放射状に向きます。','球の法線は、球の中心から向きます。','二つの中心が違えば、一般にずれます。','同じ小片で二つの矢印を比べましょう。'],'surface','offsetQuestion'),
 'g-substitution':f('置換したら、面まで変わったの？',['変えたのは、積分に使う目盛りだけです。','面・電荷・足す小片は同じままです。','新しい目盛りに合わせて微分も変えます。','端点も変えないと、別の積分になります。'],'surface'),
 'g-antiderivative':f('原始関数が合っているか確かめたい',['微分すると、元の関数に戻るか調べます。','定数を足しても微分では消えます。','定積分では、その定数も両端で消えます。','図は同じ傾きの曲線を上下に動かします。'],'line'),
 'g-endpoints':f('ずれdが消えるなら、各点の電場も同じ？',['同じなのは、面全体の合計です。','近い小片と遠い小片の寄与は変わります。','足し合わせた結果だけが一定になります。','図の局所の曲線と合計を分けて見ます。'],'research','offsetQuestion'),
 'g-outsideproof':f('外の電荷は無視していい？',['各点の電場を求めるなら無視できません。','0になるのは、閉曲面の正味の電気束です。','入る寄与と出る寄与が全体で相殺します。','電場そのものは、面上にも存在します。'],'questions','research'),
 'g-solidangle':f('立体角は、小片の面積そのもの？',['電荷から見た方向の広がりを表します。','同じ面積でも遠いほど小さく見えます。','同じ方向を覆えば、面積は距離の二乗倍。','単位球へ写した面積で測るのが立体角です。'],'feynman'),
 'g-raycount':f('凹んだ面だと、何度も数えてしまわない？',['外へ出る交差を＋、入る交差を−とします。','中からなら、出る回数が一回多くなります。','入り直した分は、次の出口と打ち消します。','図は一方向の断面。全方向を積分します。'],'feynman'),
 'g-superposition':f('正負の電荷は、絶対値で足す？',['内部電荷は、符号を残したまま足します。','＋Qと−Qなら、正味の内部電荷は0です。','それでも、局所の電場は普通は残ります。','合計が0と、各点で0は別の主張です。'],'questions','research'),
 'g-application':f('好きな面を描けば、対称になる？',['対称性を決めるのは電荷の配置です。','面を描いても、その配置は変わりません。','対称性があって初めて計算が簡単になります。','法則の成立と、簡単に解けることは別です。'],'research'),
 point:f('球を大きくしたら、電気束は減る？',['点電荷の場は、距離の二乗で弱まります。','球面積は、半径の二乗で増えます。','その二つを掛けると半径が消えます。','電場の強さと電気束を区別します。'],'questions'),
 wire:f('円筒のふたを数え忘れていない？',['無限直線の場は線から横へ向きます。','ふたの法線は、線に沿う方向です。','二つが垂直なので、ふたの寄与は0です。','閉曲面のまま、0の面も判断しています。'],'surface'),
 sheet:f('上下の電場は逆向きだから相殺？',['上面の外向き法線は上向きです。','下面の外向き法線は下向きです。','どちらも電場と法線がそろっています。','だから寄与は両方正で、合計2EAです。'],'questions'),
 shell:f('内部電荷0だけで、内部電場0？',['それだけでは結論できません。','球殻だけ、という球対称性も使います。','一様な外部電場を加えると反例になります。','図では電気束0のまま電場が残ります。'],'research','questions'),
 conductor:f('金属の内部なら、いつでも電場0？',['静電平衡の導体材料内部での結論です。','電流が流れる抵抗には電場がありえます。','電荷を含む空洞も、導体材料とは別です。','図では帯電した空洞と材料を区別します。'],'questions','cavityQuestion'),
};
