import type {PaperProblem} from '../types';

// Trial only: the first university-electromagnetism unit at each difficulty.
// Each exercise has its own diagram labels and three frames for a silent explainer.
export const emPaperProblems:Record<string,PaperProblem[]|undefined>={
 'ui-field-map':[
  {id:'paper-ui-field-1',scene:'field',labels:['電場：右へ 3 N/C','置く電荷：−2 C','力の矢印は？'],
   question:'右向きに $3\\,\\mathrm{N/C}$ の電場があります。この場所へ $-2\\,\\mathrm C$ の電荷を置きます。電荷が受ける力の大きさを計算し、向きを矢印で描いてください。ここでは、置く電荷は元の電場を変えないものとします。',
   steps:['電場は「正の $1\\,\\mathrm C$ が受ける力」の地図です。電荷を置いた場所では、電場の矢印は右向きのままです。',
    '力は $\\vec F=q\\vec E$ です。大きさは $|q|E=2\\times3=6\\,\\mathrm N$ になります。',
    '電荷 $q$ は負なので、力の矢印は電場と逆向きです。答えは「左向きに $6\\,\\mathrm N$」。']},
  {id:'paper-ui-field-2',scene:'field',labels:['地点A：右へ 2 N/C','地点B：上へ 4 N/C','電荷：+2 C'],
   question:'電場の地図で、地点Aの電場は右向きに $2\\,\\mathrm{N/C}$、地点Bの電場は上向きに $4\\,\\mathrm{N/C}$ です。$+2\\,\\mathrm C$ の電荷をそれぞれの地点に置いたとき、受ける力の矢印を2本描き、大きさを求めてください。',
   steps:['地点Aと地点Bは別の場所です。電場の向きと強さは、まず地図の矢印から読み取ります。',
    '地点Aでは $F_A=qE_A=2\\times2=4\\,\\mathrm N$。正の電荷なので、力は右向きです。',
    '地点Bでは $F_B=qE_B=2\\times4=8\\,\\mathrm N$。力は上向きです。同じ電荷でも、場所が違えば力は変わります。']},
  {id:'paper-ui-field-3',scene:'field',labels:['中心：正の点電荷 +Q','右側の点 R','左側の点 L'],
   question:'中心に正の点電荷を1個置き、その左右に点Lと点Rを取ります。LとRでの電場の向きを矢印で描いてください。次に、各点へ負の電荷を置いたとき、その電荷が受ける力の向きも別の色で描いてください。',
   steps:['正の点電荷は、正の試験電荷を中心から押し出します。電場は中心から外向きです。',
    'したがって、Rの電場は右向き、Lの電場は左向きです。左右で矢印の向きが異なります。',
    '負の電荷が受ける力は電場と逆向きです。Rの力は左向き、Lの力は右向きになります。']},
 ],
 'um-line-element':[
  {id:'paper-um-line-1',scene:'path',labels:['電場 E=(3, 4) N/C','移動 Δr=(0.20, −0.10) m','電荷 q=+2 C'],
   question:'ある小区間で、電場は $\\vec E=(3,4)\\,\\mathrm{N/C}$、電荷は $q=+2\\,\\mathrm C$、移動は $\\Delta\\vec r=(0.20,-0.10)\\,\\mathrm m$ です。電場が電荷にする仕事を、成分ごとの掛け算を書いて求めてください。',
   steps:['電荷が受ける力は $\\vec F=q\\vec E=(6,8)\\,\\mathrm N$ です。電場をそのまま仕事の式へ入れないようにします。',
    '同じ方向の成分を掛けて足します。$\\Delta W=\\vec F\\cdot\\Delta\\vec r=6(0.20)+8(-0.10)$ です。',
    '$\\Delta W=1.2-0.8=0.4\\,\\mathrm J$。上向きの力に逆らって下へ進んだ分は、負の仕事になります。']},
  {id:'paper-um-line-2',scene:'path',labels:['力：右へ 5 N','移動①：上へ 0.40 m','移動②：左へ 0.20 m'],
   question:'右向きに $5\\,\\mathrm N$ の力を受ける物体が、まず上へ $0.40\\,\\mathrm m$、次に左へ $0.20\\,\\mathrm m$ 動きます。二つの小区間について力と移動の矢印を描き、各区間の仕事と合計を求めてください。',
   steps:['最初の移動は力と直角です。右向きの力は上向きの移動に寄与しないので、仕事は $0\\,\\mathrm J$ です。',
    '次の移動は力と逆向きです。大きさは $5\\times0.20=1\\,\\mathrm J$、符号は負になります。',
    '二つの区間を足すと $W=0-1=-1\\,\\mathrm J$。距離だけを足して力を掛けると、向きを見落とします。']},
  {id:'paper-um-line-3',scene:'path',labels:['電場：E=(1, 2) N/C','移動：Δr=(0.30, 0.40) m','電荷：+2 C'],
   question:'小区間の仕事の式 $\\Delta W=q\\vec E\\cdot\\Delta\\vec r$ を、「進む向きの力 × 進んだ距離」から導いてください。その後、$q=+2\\,\\mathrm C$、$\\vec E=(1,2)\\,\\mathrm{N/C}$、$\\Delta\\vec r=(0.30,0.40)\\,\\mathrm m$ で計算してください。',
   steps:['力と移動のなす角を $\\theta$ とすると、進む向きの力は $|\\vec F|\\cos\\theta$。仕事は $|\\vec F||\\Delta\\vec r|\\cos\\theta$ です。',
    '内積の定義により、これは $\\vec F\\cdot\\Delta\\vec r$ です。$\\vec F=q\\vec E$ を代入すると $\\Delta W=q\\vec E\\cdot\\Delta\\vec r$ になります。',
    '数値を入れると $\\Delta W=2(1\\times0.30+2\\times0.40)=2.2\\,\\mathrm J$ です。']},
 ],
 'ue-integrals':[
  {id:'paper-ue-integrals-1',scene:'path',labels:['E(x,y)=α(y,x)','r(u)=(2u,u²) m','0≤u≤1, q=+1 C'],
   question:'静電場を $\\vec E(x,y)=\\alpha(y,x)$、$\\alpha=1\\,\\mathrm{N/(C\\,m)}$ とします。$+1\\,\\mathrm C$ の電荷が $\\vec r(u)=(2u,u^2)\\,\\mathrm m$（$0\\leq u\\leq1$）に沿って動くとき、電場がする仕事を線積分で求めてください。$u$ は道をたどるための目盛りです。',
   steps:['道の上では $x=2u\\,\\mathrm m$、$y=u^2\\,\\mathrm m$ です。したがって、電場は $\\vec E=(u^2,2u)\\,\\mathrm{N/C}$ になります。',
    '$u$ を $du$ 増やすと、移動は $d\\vec r=(2,2u)du\\,\\mathrm m$。内積は $\\vec E\\cdot d\\vec r=(2u^2+4u^2)du=6u^2du$ です。',
    '仕事は $W=q\\int_0^1\\vec E\\cdot d\\vec r=\\int_0^1 6u^2du=2\\,\\mathrm J$ です。']},
  {id:'paper-ue-integrals-2',scene:'surface',labels:['立方体：一辺 1 m','E=(αx,0,0)','α=2 N/(C·m)'],
   question:'$0\\leq x,y,z\\leq1\\,\\mathrm m$ の立方体があり、電場は $\\vec E=(\\alpha x,0,0)$、$\\alpha=2\\,\\mathrm{N/(C\\,m)}$ です。六つの面の外向きの電気束をそれぞれ調べ、閉曲面全体の電気束を面積分で求めてください。',
   steps:['$x=1\\,\\mathrm m$ の面では、電場は外向きに $2\\,\\mathrm{N/C}$、面積は $1\\,\\mathrm{m^2}$ です。束は $2\\,\\mathrm{N\\,m^2/C}$ です。',
    '$x=0$ の面では電場がゼロです。$y$ と $z$ が一定の四つの面では、電場と法線が直角なので束はゼロです。',
    '六面の和は $\\oint_S\\vec E\\cdot d\\vec A=2+0+0=2\\,\\mathrm{N\\,m^2/C}$ です。各面で外向き法線を使いました。']},
  {id:'paper-ue-integrals-3',scene:'path',labels:['Eₓ=3x² N/C（xはm）','A：x=0 m','B：x=2 m'],
   question:'$x$ をメートルで測るとき、静電場は $E_x(x)=\\bigl(3\\,\\mathrm{N/(C\\,m^2)}\\bigr)x^2$ です。$+1\\,\\mathrm C$ の電荷を $x=0$ から $x=2\\,\\mathrm m$ へ動かします。電場がする仕事を積分し、$V(B)-V(A)$ を求めてください。',
   steps:['電場が変化するので、短い移動 $dx$ の仕事 $dW=qE_x(x)dx$ を足します。$q=1\\,\\mathrm C$ を入れます。',
    '$W=\\int_0^2 3x^2dx=[x^3]_0^2=8\\,\\mathrm J$。電場は右向きの電荷に正の仕事をします。',
    '電位差は、正の電荷 $1\\,\\mathrm C$ あたりの電気的位置エネルギーの変化です。$V(B)-V(A)=-W/q=-8\\,\\mathrm V$ です。']},
 ],
};
