import type { Formula } from "../types";

export const formulas: Formula[] = [
  // ---------- 力学 ----------
  {
    id: "f-velocity",
    name: "速さの定義",
    tex: "v = \\dfrac{x}{t}",
    meaning: "速さ =「1秒あたりに進む距離」。距離÷時間は 1秒あたりに直す操作。",
    category: "力学",
    stageId: "m1-velocity",
  },
  {
    id: "f-distance",
    name: "等速直線運動の距離",
    tex: "x = vt",
    meaning: "1秒あたり v 進むなら、t 秒でその t 倍進む。",
    category: "力学",
    stageId: "m1-velocity",
  },
  {
    id: "f-acceleration",
    name: "加速度の定義",
    tex: "a = \\dfrac{v - v_0}{t}",
    meaning: "加速度 =「1秒あたりの速度の変化」。(あと − はじめ) ÷ 時間。",
    category: "力学",
    stageId: "m1-acceleration",
  },
  {
    id: "f-ua-1",
    name: "等加速度運動 第1式",
    tex: "v = v_0 + at",
    meaning: "加速度の定義を並べ替えただけ。はじめの速度に毎秒 a を t 秒ぶん積み増す。",
    category: "力学",
    stageId: "m1-uniform-accel",
  },
  {
    id: "f-ua-2",
    name: "等加速度運動 第2式",
    tex: "x = v_0 t + \\tfrac{1}{2}at^2",
    meaning: "v-tグラフの下の面積。長方形 v₀t + 三角形 ½at²。½は三角形の面積の½。",
    category: "力学",
    stageId: "m1-uniform-accel",
  },
  {
    id: "f-ua-3",
    name: "等加速度運動 第3式",
    tex: "v^2 - v_0^2 = 2ax",
    meaning: "第1式と第2式から t を消去した式。時間が与えられない問題用。",
    category: "力学",
    stageId: "m1-uniform-accel",
  },
  {
    id: "f-freefall",
    name: "自由落下",
    tex: "v = gt, \\quad y = \\tfrac{1}{2}gt^2",
    meaning: "3公式に v₀=0, a=g(9.8 m/s²)を代入しただけ。新しい公式ではない。",
    category: "力学",
    stageId: "m-freefall",
  },
  {
    id: "f-newton2",
    name: "運動方程式",
    tex: "ma = F",
    meaning: "力は「加速度」を作る。加速度は力に比例し、質量に反比例する。",
    category: "力学",
    stageId: "m-force",
  },
  {
    id: "f-weight",
    name: "重力(重さ)",
    tex: "W = mg",
    meaning: "質量 m の物体にはたらく重力。質量(kg)と重さ(N)は別の量。",
    category: "力学",
    stageId: "m-force",
  },
  {
    id: "f-work",
    name: "仕事",
    tex: "W = Fx",
    meaning: "力 × 力の向きに動いた距離。動かなければ仕事はゼロ。",
    category: "力学",
    stageId: "m-energy",
  },
  {
    id: "f-kinetic",
    name: "運動エネルギー",
    tex: "K = \\tfrac{1}{2}mv^2",
    meaning: "した仕事 Fx がこの形で蓄わる。½ は v² = 2ax の 2 から来ている。",
    category: "力学",
    stageId: "m-energy",
  },
  {
    id: "f-potential",
    name: "重力による位置エネルギー",
    tex: "U = mgh",
    meaning: "高さ h まで持ち上げる仕事 mg×h の貯金。落とせば運動エネルギーに戻せる。",
    category: "力学",
    stageId: "m-energy",
  },
  {
    id: "f-conservation",
    name: "力学的エネルギー保存則",
    tex: "\\tfrac{1}{2}mv^2 + mgh = \\text{一定}",
    meaning: "摩擦・空気抵抗がなければ K と U の合計は変わらない。",
    category: "力学",
    stageId: "m-energy",
  },
  // ---------- 熱力学 ----------
  {
    id: "f-kelvin",
    name: "絶対温度",
    tex: "T = t + 273",
    meaning: "分子運動が止まる −273℃ を 0 とした温度。気体の法則では必ずこちらを使う。",
    category: "熱力学",
    stageId: "t-heat",
  },
  {
    id: "f-heat",
    name: "熱量",
    tex: "Q = mc\\Delta T",
    meaning: "「1gを1K上げるのに c(J)」という比熱の定義を、m倍・ΔT倍しただけ。",
    category: "熱力学",
    stageId: "t-heat",
  },
  {
    id: "f-boyle-charles",
    name: "ボイル・シャルルの法則",
    tex: "\\dfrac{P_1V_1}{T_1} = \\dfrac{P_2V_2}{T_2}",
    meaning: "圧力=分子の衝突、と考えれば導ける。T は必ず絶対温度(K)で。",
    category: "熱力学",
    stageId: "t-gas",
  },
  {
    id: "f-firstlaw",
    name: "熱力学第一法則",
    tex: "\\Delta U = Q + W",
    meaning: "内部エネルギーの増加 = もらった熱 + された仕事。エネルギーの帳簿。",
    category: "熱力学",
    stageId: "t-firstlaw",
  },
  {
    id: "f-efficiency",
    name: "熱効率",
    tex: "e = \\dfrac{W}{Q}",
    meaning: "もらった熱のうち仕事に変わる割合。原理的に1(100%)にはできない。",
    category: "熱力学",
    stageId: "t-firstlaw",
  },
  // ---------- 波動 ----------
  {
    id: "f-freq",
    name: "振動数と周期",
    tex: "f = \\dfrac{1}{T}",
    meaning: "1回に T 秒 ⇔ 1秒に 1/T 回。逆数の関係。",
    category: "波動",
    stageId: "w-basics",
  },
  {
    id: "f-wave",
    name: "波の基本式",
    tex: "v = f\\lambda",
    meaning: "1秒に f 個の波が、それぞれ長さ λ で送り出される。1振動で1波長進む。",
    category: "波動",
    stageId: "w-basics",
  },
  {
    id: "f-beat",
    name: "うなり",
    tex: "f_{\\text{うなり}} = |f_1 - f_2|",
    meaning: "わずかに違う2音の、強め合い・打ち消し合いの繰り返し。回数は振動数の差。",
    category: "波動",
    stageId: "w-sound",
  },
  {
    id: "f-refraction",
    name: "屈折率",
    tex: "n = \\dfrac{c}{v}",
    meaning: "媒質中で光が何倍遅くなるか。速さが変わるから光は曲がる。",
    category: "波動",
    stageId: "w-light",
  },
  // ---------- 電磁気 ----------
  {
    id: "f-current",
    name: "電流の定義",
    tex: "I = \\dfrac{Q}{t}",
    meaning: "1秒あたりに断面を通過する電気量。速度・加速度と同じ「1秒あたり」の発想。",
    category: "電磁気",
    stageId: "e-current",
  },
  {
    id: "f-ohm",
    name: "オームの法則",
    tex: "V = RI",
    meaning: "電圧(押す力)= 抵抗(通りにくさ)× 電流(流れ)。",
    category: "電磁気",
    stageId: "e-current",
  },
  {
    id: "f-power",
    name: "電力",
    tex: "P = VI = RI^2 = \\dfrac{V^2}{R}",
    meaning: "1秒あたりの電気エネルギー。後ろ2つはオームの法則を代入しただけ。",
    category: "電磁気",
    stageId: "e-power",
  },
  {
    id: "f-energy",
    name: "電力量(ジュール熱)",
    tex: "W = Pt",
    meaning: "電力(1秒あたり)× 秒数 = 使ったエネルギー総量。1kWh = 3.6×10⁶ J。",
    category: "電磁気",
    stageId: "e-power",
  },
  // ---------- 原子 ----------
  {
    id: "f-photon",
    name: "光子のエネルギー",
    tex: "E = h\\nu",
    meaning: "光は粒(光子)の集まり。1個のエネルギーは振動数に比例。明るさは個数。",
    category: "原子",
    stageId: "a-photon",
  },
  {
    id: "f-halflife",
    name: "半減期",
    tex: "N = N_0 \\left(\\tfrac{1}{2}\\right)^{t/T}",
    meaning: "半減期 T が1回過ぎるごとに半分。2回で1/4、3回で1/8。",
    category: "原子",
    stageId: "a-nucleus",
  },
  {
    id: "f-emc2",
    name: "質量とエネルギーの等価性",
    tex: "E = mc^2",
    meaning: "質量はエネルギーの塊。換算レート c² が巨大なので、微小な質量差が莫大なエネルギーになる。",
    category: "原子",
    stageId: "a-nucleus",
  },
  // ---------- 追加分: 力学(発展) ----------
  { id: "f-momentum", name: "運動量", tex: "p = mv", meaning: "質量つきの勢い。向きを持つベクトル量。", category: "力学", stageId: "m-momentum" },
  { id: "f-impulse", name: "力積と運動量の変化", tex: "F\\Delta t = \\Delta p", meaning: "力×時間のぶんだけ運動量が変わる。時間を稼げば力は小さい(エアバッグ)。", category: "力学", stageId: "m-momentum" },
  { id: "f-p-conserve", name: "運動量保存則", tex: "m_1v_1 + m_2v_2 = \\text{一定}", meaning: "外力がなければ合計の運動量は不変。衝突・分裂はまずこれ。", category: "力学", stageId: "m-momentum" },
  { id: "f-centripetal-a", name: "向心加速度", tex: "a = \\dfrac{v^2}{r}", meaning: "円運動の加速度。向きは常に中心向き。", category: "力学", stageId: "m-circular" },
  { id: "f-centripetal-f", name: "向心力", tex: "F = \\dfrac{mv^2}{r}", meaning: "円運動を保つのに必要な中心向きの力。", category: "力学", stageId: "m-circular" },
  { id: "f-gravity", name: "万有引力の法則", tex: "F = G\\dfrac{Mm}{r^2}", meaning: "すべての物体は引き合う。距離の2乗に反比例。月を回す力=リンゴを落とす力。", category: "力学", stageId: "m-circular" },
  { id: "f-hooke", name: "復元力(フックの法則)", tex: "F = -kx", meaning: "ずれに比例して引き戻す力。これがあると単振動が生まれる。", category: "力学", stageId: "m-shm" },
  { id: "f-shm-spring", name: "ばね振り子の周期", tex: "T = 2\\pi\\sqrt{\\dfrac{m}{k}}", meaning: "重いほどゆっくり、硬いほど速い。振幅にはよらない。", category: "力学", stageId: "m-shm" },
  { id: "f-pendulum", name: "単振り子の周期", tex: "T = 2\\pi\\sqrt{\\dfrac{l}{g}}", meaning: "長さとgだけで決まる(等時性)。質量・振幅は無関係。", category: "力学", stageId: "m-shm" },
  // ---------- 追加分: 熱力学(発展) ----------
  { id: "f-ideal-gas", name: "理想気体の状態方程式", tex: "PV = nRT", meaning: "気体の法則の完成形。ボイル・シャルルの「一定」の正体は nR。", category: "熱力学", stageId: "t-ideal" },
  { id: "f-internal-u", name: "内部エネルギー(単原子)", tex: "U = \\tfrac{3}{2}nRT", meaning: "分子の運動エネルギーの合計。絶対温度に比例。", category: "熱力学", stageId: "t-ideal" },
  // ---------- 追加分: 波動(発展) ----------
  { id: "f-doppler", name: "ドップラー効果(音源接近)", tex: "f' = f\\,\\dfrac{V}{V - v_s}", meaning: "前方は波面が詰まって高い音に。「詰まるから高い」を式にしただけ。", category: "波動", stageId: "w-doppler" },
  { id: "f-interference", name: "干渉条件", tex: "\\text{強: } m\\lambda, \\quad \\text{弱: } (m+\\tfrac{1}{2})\\lambda", meaning: "経路差が波長の整数倍なら強め合い、半端なら打ち消し合い。", category: "波動", stageId: "w-interference" },
  // ---------- 追加分: 電磁気(発展) ----------
  { id: "f-coulomb-law", name: "クーロンの法則", tex: "F = k\\dfrac{q_1q_2}{r^2}", meaning: "電気版・万有引力。同符号は反発、異符号は引力。", category: "電磁気", stageId: "e-field" },
  { id: "f-efield", name: "電場の定義", tex: "E = \\dfrac{F}{q}", meaning: "+1Cあたりが受ける力の「地図」。電荷qが受ける力は F = qE。", category: "電磁気", stageId: "e-field" },
  { id: "f-epotential", name: "一様電場と電位差", tex: "V = Ed", meaning: "電場は電位の坂の傾き。傾き×距離=高低差。", category: "電磁気", stageId: "e-field" },
  { id: "f-capacitor-q", name: "コンデンサー", tex: "Q = CV", meaning: "たまる電気量は電圧に比例。Cは電気容量(F)。", category: "電磁気", stageId: "e-capacitor" },
  { id: "f-capacitor-u", name: "コンデンサーのエネルギー", tex: "U = \\tfrac{1}{2}CV^2", meaning: "½はQ-Vグラフの三角形の面積(平均電圧V/2で運ぶ)。", category: "電磁気", stageId: "e-capacitor" },
  // ---------- 追加分: 原子(発展) ----------
  { id: "f-debroglie", name: "物質波(ド・ブロイ波)", tex: "\\lambda = \\dfrac{h}{mv}", meaning: "電子などの粒子も波。速いほど波長が短い(電子顕微鏡の原理)。", category: "原子", stageId: "a-bohr" },
];
