import type { Formula } from "../types";

const baseFormulas: Formula[] = [
  // ---------- 力学 ----------
  {
    id: "f-velocity",
    name: "速さの定義",
    tex: "v = \\dfrac{x}{t}",
    meaning: "速さ =「1秒あたりに進む距離」。距離÷時間は 1秒あたりに直す操作。",
    category: "力学",
    stageId: "m1-velocity",
  },
  {
    id: "f-distance",
    name: "等速直線運動の距離",
    tex: "x = vt",
    meaning: "1秒あたり v 進むなら、t 秒でその t 倍進む。",
    category: "力学",
    stageId: "m1-velocity",
  },
  {
    id: "f-acceleration",
    name: "加速度の定義",
    tex: "a = \\dfrac{v - v_0}{t}",
    meaning: "加速度 =「1秒あたりの速度の変化」。(あと − はじめ) ÷ 時間。",
    category: "力学",
    stageId: "m1-acceleration",
  },
  {
    id: "f-ua-1",
    name: "等加速度運動 第1式",
    tex: "v = v_0 + at",
    meaning: "加速度の定義を並べ替えただけ。はじめの速度に毎秒 a を t 秒ぶん積み増す。",
    category: "力学",
    stageId: "m1-uniform-accel",
  },
  {
    id: "f-ua-2",
    name: "等加速度運動 第2式",
    tex: "x = v_0 t + \\tfrac{1}{2}at^2",
    meaning: "v-tグラフの下の面積。長方形 v₀t + 三角形 ½at²。½は三角形の面積の½。",
    category: "力学",
    stageId: "m1-uniform-accel",
  },
  {
    id: "f-ua-3",
    name: "等加速度運動 第3式",
    tex: "v^2 - v_0^2 = 2ax",
    meaning: "第1式と第2式から t を消去した式。時間が与えられない問題用。",
    category: "力学",
    stageId: "m1-uniform-accel",
  },
  {
    id: "f-freefall",
    name: "自由落下",
    tex: "v = gt, \\quad y = \\tfrac{1}{2}gt^2",
    meaning: "3公式に v₀=0, a=g(9.8 m/s²)を代入しただけ。新しい公式ではない。",
    category: "力学",
    stageId: "m-freefall",
  },
  {
    id: "f-newton2",
    name: "運動方程式",
    tex: "ma = F",
    meaning: "力は「加速度」を作る。加速度は力に比例し、質量に反比例する。",
    category: "力学",
    stageId: "m-force",
  },
  {
    id: "f-weight",
    name: "重力(重さ)",
    tex: "W = mg",
    meaning: "質量 m の物体にはたらく重力。質量(kg)と重さ(N)は別の量。",
    category: "力学",
    stageId: "m-force",
  },
  {
    id: "f-work",
    name: "仕事",
    tex: "W = Fx",
    meaning: "力 × 力の向きに動いた距離。動かなければ仕事はゼロ。",
    category: "力学",
    stageId: "m-energy",
  },
  {
    id: "f-kinetic",
    name: "運動エネルギー",
    tex: "K = \\tfrac{1}{2}mv^2",
    meaning: "した仕事 Fx がこの形で蓄わる。½ は v² = 2ax の 2 から来ている。",
    category: "力学",
    stageId: "m-energy",
  },
  {
    id: "f-potential",
    name: "重力による位置エネルギー",
    tex: "U = mgh",
    meaning: "高さ h まで持ち上げる仕事 mg×h の貯金。落とせば運動エネルギーに戻せる。",
    category: "力学",
    stageId: "m-energy",
  },
  {
    id: "f-conservation",
    name: "力学的エネルギー保存則",
    tex: "\\tfrac{1}{2}mv^2 + mgh = \\text{一定}",
    meaning: "摩擦・空気抵抗がなければ K と U の合計は変わらない。",
    category: "力学",
    stageId: "m-energy",
  },
  // ---------- 熱力学 ----------
  {
    id: "f-kelvin",
    name: "絶対温度",
    tex: "T = t + 273",
    meaning: "分子運動が止まる −273℃ を 0 とした温度。気体の法則では必ずこちらを使う。",
    category: "熱力学",
    stageId: "t-heat",
  },
  {
    id: "f-heat",
    name: "熱量",
    tex: "Q = mc\\Delta T",
    meaning: "「1gを1K上げるのに c(J)」という比熱の定義を、m倍・ΔT倍しただけ。",
    category: "熱力学",
    stageId: "t-heat",
  },
  {
    id: "f-boyle-charles",
    name: "ボイル・シャルルの法則",
    tex: "\\dfrac{P_1V_1}{T_1} = \\dfrac{P_2V_2}{T_2}",
    meaning: "圧力=分子の衝突、と考えれば導ける。T は必ず絶対温度(K)で。",
    category: "熱力学",
    stageId: "t-gas",
  },
  {
    id: "f-firstlaw",
    name: "熱力学第一法則",
    tex: "\\Delta U = Q + W",
    meaning: "内部エネルギーの増加 = もらった熱 + された仕事。エネルギーの帳簿。",
    category: "熱力学",
    stageId: "t-firstlaw",
  },
  {
    id: "f-efficiency",
    name: "熱効率",
    tex: "e = \\dfrac{W}{Q}",
    meaning: "もらった熱のうち仕事に変わる割合。原理的に1(100%)にはできない。",
    category: "熱力学",
    stageId: "t-firstlaw",
  },
  // ---------- 波動 ----------
  {
    id: "f-freq",
    name: "振動数と周期",
    tex: "f = \\dfrac{1}{T}",
    meaning: "1回に T 秒 ⇔ 1秒に 1/T 回。逆数の関係。",
    category: "波動",
    stageId: "w-basics",
  },
  {
    id: "f-wave",
    name: "波の基本式",
    tex: "v = f\\lambda",
    meaning: "1秒に f 個の波が、それぞれ長さ λ で送り出される。1振動で1波長進む。",
    category: "波動",
    stageId: "w-basics",
  },
  {
    id: "f-beat",
    name: "うなり",
    tex: "f_{\\text{うなり}} = |f_1 - f_2|",
    meaning: "わずかに違う2音の、強め合い・打ち消し合いの繰り返し。回数は振動数の差。",
    category: "波動",
    stageId: "w-sound",
  },
  {
    id: "f-refraction",
    name: "屈折率",
    tex: "n = \\dfrac{c}{v}",
    meaning: "媒質中で光が何倍遅くなるか。速さが変わるから光は曲がる。",
    category: "波動",
    stageId: "w-light",
  },
  // ---------- 電磁気 ----------
  {
    id: "f-current",
    name: "電流の定義",
    tex: "I = \\dfrac{Q}{t}",
    meaning: "1秒あたりに断面を通過する電気量。速度・加速度と同じ「1秒あたり」の発想。",
    category: "電磁気",
    stageId: "e-current",
  },
  {
    id: "f-ohm",
    name: "オームの法則",
    tex: "V = RI",
    meaning: "電圧(押す力)= 抵抗(通りにくさ)× 電流(流れ)。",
    category: "電磁気",
    stageId: "e-current",
  },
  {
    id: "f-power",
    name: "電力",
    tex: "P = VI = RI^2 = \\dfrac{V^2}{R}",
    meaning: "1秒あたりの電気エネルギー。後ろ2つはオームの法則を代入しただけ。",
    category: "電磁気",
    stageId: "e-power",
  },
  {
    id: "f-energy",
    name: "電力量(ジュール熱)",
    tex: "W = Pt",
    meaning: "電力(1秒あたり)× 秒数 = 使ったエネルギー総量。1kWh = 3.6×10⁶ J。",
    category: "電磁気",
    stageId: "e-power",
  },
  // ---------- 原子 ----------
  {
    id: "f-photon",
    name: "光子のエネルギー",
    tex: "E = h\\nu",
    meaning: "光は粒(光子)の集まり。1個のエネルギーは振動数に比例。明るさは個数。",
    category: "原子",
    stageId: "a-photon",
  },
  {
    id: "f-halflife",
    name: "半減期",
    tex: "N = N_0 \\left(\\tfrac{1}{2}\\right)^{t/T}",
    meaning: "半減期 T が1回過ぎるごとに半分。2回で1/4、3回で1/8。",
    category: "原子",
    stageId: "a-nucleus",
  },
  {
    id: "f-emc2",
    name: "質量とエネルギーの等価性",
    tex: "E = mc^2",
    meaning: "質量はエネルギーの塊。換算レート c² が巨大なので、微小な質量差が莫大なエネルギーになる。",
    category: "原子",
    stageId: "a-nucleus",
  },
  // ---------- 追加分: 力学(発展) ----------
  { id: "f-momentum", name: "運動量", tex: "p = mv", meaning: "質量つきの勢い。向きを持つベクトル量。", category: "力学", stageId: "m-momentum" },
  { id: "f-impulse", name: "力積と運動量の変化", tex: "F\\Delta t = \\Delta p", meaning: "力×時間のぶんだけ運動量が変わる。時間を稼げば力は小さい(エアバッグ)。", category: "力学", stageId: "m-momentum" },
  { id: "f-p-conserve", name: "運動量保存則", tex: "m_1v_1 + m_2v_2 = \\text{一定}", meaning: "外力がなければ合計の運動量は不変。衝突・分裂はまずこれ。", category: "力学", stageId: "m-momentum" },
  { id: "f-centripetal-a", name: "向心加速度", tex: "a = \\dfrac{v^2}{r}", meaning: "円運動の加速度。向きは常に中心向き。", category: "力学", stageId: "m-circular" },
  { id: "f-centripetal-f", name: "向心力", tex: "F = \\dfrac{mv^2}{r}", meaning: "円運動を保つのに必要な中心向きの力。", category: "力学", stageId: "m-circular" },
  { id: "f-gravity", name: "万有引力の法則", tex: "F = G\\dfrac{Mm}{r^2}", meaning: "すべての物体は引き合う。距離の2乗に反比例。月を回す力=リンゴを落とす力。", category: "力学", stageId: "m-circular" },
  { id: "f-hooke", name: "復元力(フックの法則)", tex: "F = -kx", meaning: "ずれに比例して引き戻す力。これがあると単振動が生まれる。", category: "力学", stageId: "m-shm" },
  { id: "f-shm-spring", name: "ばね振り子の周期", tex: "T = 2\\pi\\sqrt{\\dfrac{m}{k}}", meaning: "重いほどゆっくり、硬いほど速い。振幅にはよらない。", category: "力学", stageId: "m-shm" },
  { id: "f-pendulum", name: "単振り子の周期", tex: "T = 2\\pi\\sqrt{\\dfrac{l}{g}}", meaning: "長さとgだけで決まる(等時性)。質量・振幅は無関係。", category: "力学", stageId: "m-shm" },
  // ---------- 追加分: 熱力学(発展) ----------
  { id: "f-ideal-gas", name: "理想気体の状態方程式", tex: "PV = nRT", meaning: "気体の法則の完成形。ボイル・シャルルの「一定」の正体は nR。", category: "熱力学", stageId: "t-ideal" },
  { id: "f-internal-u", name: "内部エネルギー(単原子)", tex: "U = \\tfrac{3}{2}nRT", meaning: "分子の運動エネルギーの合計。絶対温度に比例。", category: "熱力学", stageId: "t-ideal" },
  // ---------- 追加分: 波動(発展) ----------
  { id: "f-doppler", name: "ドップラー効果(音源接近)", tex: "f' = f\\,\\dfrac{V}{V - v_s}", meaning: "前方は波面が詰まって高い音に。「詰まるから高い」を式にしただけ。", category: "波動", stageId: "w-doppler" },
  { id: "f-interference", name: "干渉条件", tex: "\\text{強: } m\\lambda, \\quad \\text{弱: } (m+\\tfrac{1}{2})\\lambda", meaning: "経路差が波長の整数倍なら強め合い、半端なら打ち消し合い。", category: "波動", stageId: "w-interference" },
  // ---------- 追加分: 電磁気(発展) ----------
  { id: "f-coulomb-law", name: "クーロンの法則", tex: "F = k\\dfrac{q_1q_2}{r^2}", meaning: "電気版・万有引力。同符号は反発、異符号は引力。", category: "電磁気", stageId: "e-field" },
  { id: "f-efield", name: "電場の定義", tex: "E = \\dfrac{F}{q}", meaning: "+1Cあたりが受ける力の「地図」。電荷qが受ける力は F = qE。", category: "電磁気", stageId: "e-field" },
  { id: "f-epotential", name: "一様電場と電位差", tex: "V = Ed", meaning: "電場は電位の坂の傾き。傾き×距離=高低差。", category: "電磁気", stageId: "e-field" },
  { id: "f-capacitor-q", name: "コンデンサー", tex: "Q = CV", meaning: "たまる電気量は電圧に比例。Cは電気容量(F)。", category: "電磁気", stageId: "e-capacitor" },
  { id: "f-capacitor-u", name: "コンデンサーのエネルギー", tex: "U = \\tfrac{1}{2}CV^2", meaning: "½はQ-Vグラフの三角形の面積(平均電圧V/2で運ぶ)。", category: "電磁気", stageId: "e-capacitor" },
  // ---------- 追加分: 原子(発展) ----------
  { id: "f-debroglie", name: "物質波(ド・ブロイ波)", tex: "\\lambda = \\dfrac{h}{mv}", meaning: "電子などの粒子も波。速いほど波長が短い(電子顕微鏡の原理)。", category: "原子", stageId: "a-bohr" },
  // ---------- 大学編: 数学の武器庫 ----------
  { id: "fu-derivative", name: "速度・加速度(微分)", tex: "v = \\dfrac{dx}{dt}, \\quad a = \\dfrac{d^2x}{dt^2}", meaning: "速度は位置の瞬間変化率(接線の傾き)、加速度はその変化率。", category: "大学: 数学の武器庫", stageId: "um-derivative" },
  { id: "fu-integral", name: "位置(積分)", tex: "x = \\int v\\, dt", meaning: "距離=速さ×微小時間の無限の足し合わせ。グラフの面積の正体。", category: "大学: 数学の武器庫", stageId: "um-integral" },
  { id: "fu-chain", name: "チェインルール", tex: "\\dfrac{dy}{dt} = \\dfrac{dy}{du}\\cdot\\dfrac{du}{dt}", meaning: "変化率はギア比のように掛け算でつながる。外を微分×中を微分。", category: "大学: 数学の武器庫", stageId: "um-rules" },
  { id: "fu-product", name: "積の微分", tex: "(fg)' = f'g + fg'", meaning: "両方変わるなら寄与は2口。長方形の面積の増え方。", category: "大学: 数学の武器庫", stageId: "um-rules" },
  { id: "fu-smallangle", name: "微小角近似", tex: "\\sin\\theta \\approx \\theta \\quad (\\theta \\ll 1)", meaning: "滑らかな曲線は拡大すれば直線。振り子を単振動に変える近似。", category: "大学: 数学の武器庫", stageId: "um-taylor" },
  { id: "fu-binomial", name: "二項近似", tex: "(1+x)^n \\approx 1 + nx", meaning: "物理で最頻出の近似。|x|が小さければ高次項は無視できる。", category: "大学: 数学の武器庫", stageId: "um-taylor" },
  { id: "fu-dot", name: "内積", tex: "\\vec{A}\\cdot\\vec{B} = AB\\cos\\theta = A_xB_x + A_yB_y", meaning: "「同じ向き度」を測る掛け算。仕事の定義の心臓部。", category: "大学: 数学の武器庫", stageId: "um-dot" },
  { id: "fu-cross", name: "外積", tex: "|\\vec{A}\\times\\vec{B}| = AB\\sin\\theta", meaning: "平行四辺形の面積。向きは右ねじ。トルク・角運動量・ローレンツ力の言語。", category: "大学: 数学の武器庫", stageId: "um-cross" },
  { id: "fu-decay", name: "指数関数的減衰", tex: "\\dfrac{dN}{dt} = -\\lambda N \\ \\Rightarrow\\ N = N_0e^{-\\lambda t}", meaning: "減り方が今の量に比例→指数減衰。変数分離で解ける。", category: "大学: 数学の武器庫", stageId: "um-ode" },
  { id: "fu-shm-eq", name: "単振動の方程式", tex: "\\dfrac{d^2x}{dt^2} = -\\omega^2 x", meaning: "「変位に比例して中心へ引き戻す」。解は x = A sin(ωt+φ)。", category: "大学: 数学の武器庫", stageId: "um-shm-ode" },
  // ---------- 大学編: 力学 ----------
  { id: "fu-newton", name: "運動方程式(ベクトル)", tex: "m\\dfrac{d^2\\vec{r}}{dt^2} = \\vec{F}", meaning: "位置r(t)を未知関数とする微分方程式。解けば未来の軌道が全て分かる。", category: "大学: 力学", stageId: "uc-newton" },
  { id: "fu-terminal", name: "終端速度", tex: "v_\\infty = \\dfrac{mg}{k}", meaning: "重力と空気抵抗のつり合い。右辺=0と置くだけで出る情報。", category: "大学: 力学", stageId: "uc-drag" },
  { id: "fu-work", name: "仕事(一般形)", tex: "W = \\int \\vec{F}\\cdot d\\vec{r}", meaning: "刻んで足す×効く成分だけ。曲がる道・変わる力でも通用する完全版。", category: "大学: 力学", stageId: "uc-work" },
  { id: "fu-ke-theorem", name: "運動エネルギー定理", tex: "\\tfrac{1}{2}mv^2 - \\tfrac{1}{2}mv_0^2 = W", meaning: "運動方程式にvを掛けて積分しただけ。新法則ではなく ma=F の別の顔。", category: "大学: 力学", stageId: "uc-work" },
  { id: "fu-power", name: "仕事率", tex: "P = \\vec{F}\\cdot\\vec{v}", meaning: "毎秒流れ込むエネルギー。車の馬力も電気のワットもこれ。", category: "大学: 力学", stageId: "uc-work" },
  { id: "fu-potential", name: "力とポテンシャル", tex: "F = -\\dfrac{dU}{dx}", meaning: "力はエネルギーの地形の坂を下る向きに、傾きの分だけ働く。", category: "大学: 力学", stageId: "uc-potential" },
  { id: "fu-impulse", name: "力積と運動量", tex: "\\int F\\,dt = \\Delta p", meaning: "力×時間の蓄積=勢いの変化。エアバッグの設計式。", category: "大学: 力学", stageId: "uc-momentum" },
  { id: "fu-torque", name: "トルク", tex: "\\vec{N} = \\vec{r}\\times\\vec{F}", meaning: "回す効き目=腕×力×直角度。ドアノブが端に付いている理由。", category: "大学: 力学", stageId: "uc-angular" },
  { id: "fu-angmom", name: "角運動量", tex: "\\vec{L} = \\vec{r}\\times\\vec{p}, \\quad \\dfrac{d\\vec{L}}{dt} = \\vec{N}", meaning: "回転の勢いと、その回転版運動方程式。トルク0ならLは保存。", category: "大学: 力学", stageId: "uc-angular" },
  { id: "fu-inertia", name: "慣性モーメント", tex: "I = \\sum m_ir_i^2", meaning: "回転の「質量」。軸からの距離の2乗で効く — 遠いほど回しにくい。", category: "大学: 力学", stageId: "uc-rigid1" },
  { id: "fu-parallel", name: "平行軸の定理", tex: "I = I_G + Md^2", meaning: "軸を重心からdずらすと、重心を回す分 Md² が上乗せされる。", category: "大学: 力学", stageId: "uc-rigid1" },
  { id: "fu-rot-eq", name: "回転の運動方程式", tex: "I\\dfrac{d\\omega}{dt} = N", meaning: "ma=Fの回転版。m→I、a→dω/dt、F→N の辞書で翻訳するだけ。", category: "大学: 力学", stageId: "uc-rigid2" },
  { id: "fu-rot-ke", name: "回転+転がりのエネルギー", tex: "K = \\tfrac{1}{2}Mv^2 + \\tfrac{1}{2}I\\omega^2", meaning: "転がる物体のエネルギーは並進と回転の2口。滑らない条件は v = Rω。", category: "大学: 力学", stageId: "uc-rigid2" },
  { id: "fu-centrifugal", name: "遠心力(回転系)", tex: "F = mr\\omega^2", meaning: "回転する視点で現れる見かけの力。実在するのは内向きの向心力。", category: "大学: 力学", stageId: "uc-frontier" },
  // ---------- 大学編: 電磁気 ----------
  { id: "fu-flux", name: "磁束(面積分)", tex: "\\Phi = \\int\\vec{B}\\cdot d\\vec{A}", meaning: "面を貫く本数の集計。一様なら BAcosθ に退化。", category: "大学: 電磁気", stageId: "ue-integrals" },
  { id: "fu-gauss", name: "ガウスの法則", tex: "\\oint\\vec{E}\\cdot d\\vec{A} = \\dfrac{Q_{\\text{内}}}{\\varepsilon_0}", meaning: "袋から出る本数=中の電荷÷ε₀。球・円筒・平面の電場が一撃で出る。", category: "大学: 電磁気", stageId: "ue-gauss" },
  { id: "fu-vdef", name: "電位の定義", tex: "V = -\\int\\vec{E}\\cdot d\\vec{r}", meaning: "電気の標高。逆向きの関係は E = −dV/dr(電場は電位の坂)。", category: "大学: 電磁気", stageId: "ue-potential" },
  { id: "fu-cap", name: "平行板コンデンサ", tex: "C = \\dfrac{\\varepsilon_0 S}{d}", meaning: "ガウス→E→V=Ed→C=Q/V の4手で導出できる。広く・狭くで大容量。", category: "大学: 電磁気", stageId: "ue-capacitor" },
  { id: "fu-udensity", name: "電場のエネルギー密度", tex: "u = \\tfrac{1}{2}\\varepsilon_0E^2", meaning: "エネルギーは電場という空間の状態に宿る。電磁波の理解への伏線。", category: "大学: 電磁気", stageId: "ue-capacitor" },
  { id: "fu-current", name: "電流の微視形", tex: "I = enSv", meaning: "電荷×密度×断面積×平均速度。電子はノロノロ、合図は光速。", category: "大学: 電磁気", stageId: "ue-current" },
  { id: "fu-lorentz", name: "ローレンツ力", tex: "\\vec{F} = q\\vec{v}\\times\\vec{B}", meaning: "動く電荷を直角に押す力。仕事をしないので速さ不変、向きだけ曲げる。", category: "大学: 電磁気", stageId: "ue-lorentz" },
  { id: "fu-cyclotron", name: "円運動の半径(磁場中)", tex: "r = \\dfrac{mv}{qB}", meaning: "重い・速いほど大回り、強磁場で小回り。質量分析器の物差し。", category: "大学: 電磁気", stageId: "ue-lorentz" },
  { id: "fu-ampere", name: "アンペールの法則", tex: "\\oint\\vec{B}\\cdot d\\vec{r} = \\mu_0 I_{\\text{貫}}", meaning: "輪の一周集計=貫く電流。直線電流とソレノイドが一撃で出る。", category: "大学: 電磁気", stageId: "ue-ampere" },
  { id: "fu-solenoid", name: "ソレノイドの磁場", tex: "B = \\mu_0 n I", meaning: "内部は一様磁場。巻き密度×電流だけで決まる。MRIの心臓部。", category: "大学: 電磁気", stageId: "ue-ampere" },
  { id: "fu-faraday", name: "ファラデーの法則", tex: "V = -\\dfrac{d\\Phi}{dt}", meaning: "磁束の変化率が起電力。マイナス(レンツ)はエネルギー保存の番人。", category: "大学: 電磁気", stageId: "ue-faraday" },
  { id: "fu-inductance", name: "自己誘導とコイルのエネルギー", tex: "V = -L\\dfrac{dI}{dt}, \\quad U = \\tfrac{1}{2}LI^2", meaning: "Lは電流の慣性。½LI²は½mv²の電気版。", category: "大学: 電磁気", stageId: "ue-faraday" },
  { id: "fu-rc", name: "RC回路の時定数", tex: "\\tau = RC", meaning: "63%充電までの時間。回路の反応速度の設計パラメータ。", category: "大学: 電磁気", stageId: "ue-transient" },
  { id: "fu-lc", name: "LC振動", tex: "\\omega = \\dfrac{1}{\\sqrt{LC}}", meaning: "電気のばね振り子(L↔m、1/C↔k)。ラジオの選局の原理。", category: "大学: 電磁気", stageId: "ue-transient" },
  { id: "fu-light", name: "電磁波の速さ", tex: "c = \\dfrac{1}{\\sqrt{\\varepsilon_0\\mu_0}}", meaning: "マクスウェル方程式から出てきた速さが光速と一致。光=電磁波の発見。", category: "大学: 電磁気", stageId: "ue-maxwell" },
];

// Keep IDs stable while making the formula book use the same assumptions as lessons.
const notes: Record<string, Partial<Formula>> = {
  'f-velocity': { meaning:'平均の速さ＝道のり÷経過時間。平均速度は変位÷経過時間で、往復では区別する。' },
  'f-distance': { meaning:'一定速度、開始時刻0・初期位置0の式。一般の位置はx=x₀+vt。' },
  'f-acceleration': { meaning:'経過時間tの平均加速度。一定加速度なら瞬間の値と等しい。' },
  'f-ua-2': { meaning:'加速度一定。xは開始位置からの変位。v-tグラフの符号付き面積を長方形と三角形で足す。' },
  'f-kelvin': { tex:'T[\\mathrm K]=t[{}^\\circ\\mathrm C]+273.15', meaning:'温度目盛りの0をずらした定義。概算では273。絶対零度でも量子的な零点運動まで消えるとは限らない。' },
  'f-p-conserve': { meaning:'外力の合計または衝突中の外力の力積が無視できる系で成立する。作用・反作用で内力が相殺するため。' },
  'f-pendulum': { meaning:'小角・抵抗なし・軽い糸の近似。sinθ≈θから導く。大きい振幅では周期にも補正が必要。' },
  'f-coulomb-law': { tex:'F=k\\dfrac{|q_1q_2|}{r^2}', meaning:'点電荷間の力の大きさ。向きは同符号で反発・異符号で引力。実験から得られた基本法則。' },
  'f-epotential': { meaning:'一様な電場と平行な距離dでの電圧の大きさ。電場方向への移動はV後−V前=−Ed。' },
  'f-photon': { meaning:'光子1個のエネルギーを与える量子の基本関係。光電効果では保存則からK最大=hν−仕事関数を導く。' },
  'f-emc2': { meaning:'静止質量mの静止エネルギー。相対論に基づく関係。核反応の放出量は質量差Δmを使いΔE=Δmc²。' },
  'f-debroglie': { meaning:'量子の基本関係λ=h/pへ低速のp=mvを代入。電子を古典的な軌道上の波と同一視しない。' },
  'fu-integral': { tex:'x(t)-x(t_0)=\\int_{t_0}^t v(s)\\,ds', meaning:'速度×微小時間を足すと変位になる。位置を求めるには初期位置を加える。' },
  'fu-rot-eq': { meaning:'固定軸などの回転でI一定なら、L=IωとdL/dt=Nから導く。一般の3D回転には拡張が必要。' },
  'fu-flux': { meaning:'面に垂直な磁場成分の面積分。線の本数はたとえ。一様なB・平面ならBAcosθ。θは法線との角度。' },
  'fu-gauss': { meaning:'閉曲面の外向き電気束は内部電荷/ε₀。Eを積分の外へ出すには適切な対称性が必要。' },
  'fu-vdef': { tex:'V_B-V_A=-\\int_A^B\\vec E\\cdot d\\vec r', meaning:'静電場の電位差。逆にE=−∇V。誘導起電力と単なる静電位差は区別する。' },
  'fu-current': { meaning:'電子電荷の大きさ×数密度×断面積×ドリフト速度。信号速度と電子自身の移動速度は異なる。' },
  'fu-cyclotron': { tex:'r=\\dfrac{mv_\\perp}{|q|B}', meaning:'一様磁場、電場なし。垂直速度による円運動の半径。平行速度を含むとらせんになる。' },
  'fu-ampere': { meaning:'定常電流の場合の周回積分。時間変化する電場にはマクスウェルの補正項を加える。' },
  'fu-solenoid': { meaning:'十分長い真空のコイル中央部での近似。n=N/lは単位長さあたりの巻数。端の影響を無視する。' },
  'fu-faraday': { tex:'\\mathcal E=-\\dfrac{d\\Psi}{dt}', meaning:'Ψは鎖交磁束。N巻きで同じ磁束Φを共有すればΨ=NΦ。起電力は静電位差とは区別する。' },
};
export const formulas: Formula[] = baseFormulas.map(formula=>({...formula,...notes[formula.id]}));
