import type { Formula } from "../types";

export const formulas: Formula[] = [
  // ---------- 力学 ----------
  {
    id: "f-velocity",
    name: "速さの定義",
    tex: "v = \\dfrac{x}{t}",
    meaning: "速さ =「1秒あたりに進む距離」。距離÷時間は 1秒あたりに直す操作。",
    category: "力学",
    stageId: "m1-velocity",
  },
  {
    id: "f-distance",
    name: "等速直線運動の距離",
    tex: "x = vt",
    meaning: "1秒あたり v 進むなら、t 秒でその t 倍進む。",
    category: "力学",
    stageId: "m1-velocity",
  },
  {
    id: "f-acceleration",
    name: "加速度の定義",
    tex: "a = \\dfrac{v - v_0}{t}",
    meaning: "加速度 =「1秒あたりの速度の変化」。(あと − はじめ) ÷ 時間。",
    category: "力学",
    stageId: "m1-acceleration",
  },
  {
    id: "f-ua-1",
    name: "等加速度運動 第1式",
    tex: "v = v_0 + at",
    meaning: "加速度の定義を並べ替えただけ。はじめの速度に毎秒 a を t 秒ぶん積み増す。",
    category: "力学",
    stageId: "m1-uniform-accel",
  },
  {
    id: "f-ua-2",
    name: "等加速度運動 第2式",
    tex: "x = v_0 t + \\tfrac{1}{2}at^2",
    meaning: "v-tグラフの下の面積。長方形 v₀t + 三角形 ½at²。½は三角形の面積の½。",
    category: "力学",
    stageId: "m1-uniform-accel",
  },
  {
    id: "f-ua-3",
    name: "等加速度運動 第3式",
    tex: "v^2 - v_0^2 = 2ax",
    meaning: "第1式と第2式から t を消去した式。時間が与えられない問題用。",
    category: "力学",
    stageId: "m1-uniform-accel",
  },
  {
    id: "f-freefall",
    name: "自由落下",
    tex: "v = gt, \\quad y = \\tfrac{1}{2}gt^2",
    meaning: "3公式に v₀=0, a=g(9.8 m/s²)を代入しただけ。新しい公式ではない。",
    category: "力学",
    stageId: "m-freefall",
  },
  {
    id: "f-newton2",
    name: "運動方程式",
    tex: "ma = F",
    meaning: "力は「加速度」を作る。加速度は力に比例し、質量に反比例する。",
    category: "力学",
    stageId: "m-force",
  },
  {
    id: "f-weight",
    name: "重力(重さ)",
    tex: "W = mg",
    meaning: "質量 m の物体にはたらく重力。質量(kg)と重さ(N)は別の量。",
    category: "力学",
    stageId: "m-force",
  },
  {
    id: "f-work",
    name: "仕事",
    tex: "W = Fx",
    meaning: "力 × 力の向きに動いた距離。動かなければ仕事はゼロ。",
    category: "力学",
    stageId: "m-energy",
  },
  {
    id: "f-kinetic",
    name: "運動エネルギー",
    tex: "K = \\tfrac{1}{2}mv^2",
    meaning: "した仕事 Fx がこの形で蓄わる。½ は v² = 2ax の 2 から来ている。",
    category: "力学",
    stageId: "m-energy",
  },
  {
    id: "f-potential",
    name: "重力による位置エネルギー",
    tex: "U = mgh",
    meaning: "高さ h まで持ち上げる仕事 mg×h の貯金。落とせば運動エネルギーに戻せる。",
    category: "力学",
    stageId: "m-energy",
  },
  {
    id: "f-conservation",
    name: "力学的エネルギー保存則",
    tex: "\\tfrac{1}{2}mv^2 + mgh = \\text{一定}",
    meaning: "摩擦・空気抵抗がなければ K と U の合計は変わらない。",
    category: "力学",
    stageId: "m-energy",
  },
  // ---------- 熱力学 ----------
  {
    id: "f-kelvin",
    name: "絶対温度",
    tex: "T = t + 273",
    meaning: "分子運動が止まる −273℃ を 0 とした温度。気体の法則では必ずこちらを使う。",
    category: "熱力学",
    stageId: "t-heat",
  },
  {
    id: "f-heat",
    name: "熱量",
    tex: "Q = mc\\Delta T",
    meaning: "「1gを1K上げるのに c(J)」という比熱の定義を、m倍・ΔT倍しただけ。",
    category: "熱力学",
    stageId: "t-heat",
  },
  {
    id: "f-boyle-charles",
    name: "ボイル・シャルルの法則",
    tex: "\\dfrac{P_1V_1}{T_1} = \\dfrac{P_2V_2}{T_2}",
    meaning: "圧力=分子の衝突、と考えれば導ける。T は必ず絶対温度(K)で。",
    category: "熱力学",
    stageId: "t-gas",
  },
  {
    id: "f-firstlaw",
    name: "熱力学第一法則",
    tex: "\\Delta U = Q + W",
    meaning: "内部エネルギーの増加 = もらった熱 + された仕事。エネルギーの帳簿。",
    category: "熱力学",
    stageId: "t-firstlaw",
  },
  {
    id: "f-efficiency",
    name: "熱効率",
    tex: "e = \\dfrac{W}{Q}",
    meaning: "もらった熱のうち仕事に変わる割合。原理的に1(100%)にはできない。",
    category: "熱力学",
    stageId: "t-firstlaw",
  },
  // ---------- 波動 ----------
  {
    id: "f-freq",
    name: "振動数と周期",
    tex: "f = \\dfrac{1}{T}",
    meaning: "1回に T 秒 ⇔ 1秒に 1/T 回。逆数の関係。",
    category: "波動",
    stageId: "w-basics",
  },
  {
    id: "f-wave",
    name: "波の基本式",
    tex: "v = f\\lambda",
    meaning: "1秒に f 個の波が、それぞれ長さ λ で送り出される。1振動で1波長進む。",
    category: "波動",
    stageId: "w-basics",
  },
  {
    id: "f-beat",
    name: "うなり",
    tex: "f_{\\text{うなり}} = |f_1 - f_2|",
    meaning: "わずかに違う2音の、強め合い・打ち消し合いの繰り返し。回数は振動数の差。",
    category: "波動",
    stageId: "w-sound",
  },
  {
    id: "f-refraction",
    name: "屈折率",
    tex: "n = \\dfrac{c}{v}",
    meaning: "媒質中で光が何倍遅くなるか。速さが変わるから光は曲がる。",
    category: "波動",
    stageId: "w-light",
  },
  // ---------- 電磁気 ----------
  {
    id: "f-current",
    name: "電流の定義",
    tex: "I = \\dfrac{Q}{t}",
    meaning: "1秒あたりに断面を通過する電気量。速度・加速度と同じ「1秒あたり」の発想。",
    category: "電磁気",
    stageId: "e-current",
  },
  {
    id: "f-ohm",
    name: "オームの法則",
    tex: "V = RI",
    meaning: "電圧(押す力)= 抵抗(通りにくさ)× 電流(流れ)。",
    category: "電磁気",
    stageId: "e-current",
  },
  {
    id: "f-power",
    name: "電力",
    tex: "P = VI = RI^2 = \\dfrac{V^2}{R}",
    meaning: "1秒あたりの電気エネルギー。後ろ2つはオームの法則を代入しただけ。",
    category: "電磁気",
    stageId: "e-power",
  },
  {
    id: "f-energy",
    name: "電力量(ジュール熱)",
    tex: "W = Pt",
    meaning: "電力(1秒あたり)× 秒数 = 使ったエネルギー総量。1kWh = 3.6×10⁶ J。",
    category: "電磁気",
    stageId: "e-power",
  },
  // ---------- 原子 ----------
  {
    id: "f-photon",
    name: "光子のエネルギー",
    tex: "E = h\\nu",
    meaning: "光は粒(光子)の集まり。1個のエネルギーは振動数に比例。明るさは個数。",
    category: "原子",
    stageId: "a-photon",
  },
  {
    id: "f-halflife",
    name: "半減期",
    tex: "N = N_0 \\left(\\tfrac{1}{2}\\right)^{t/T}",
    meaning: "半減期 T が1回過ぎるごとに半分。2回で1/4、3回で1/8。",
    category: "原子",
    stageId: "a-nucleus",
  },
  {
    id: "f-emc2",
    name: "質量とエネルギーの等価性",
    tex: "E = mc^2",
    meaning: "質量はエネルギーの塊。換算レート c² が巨大なので、微小な質量差が莫大なエネルギーになる。",
    category: "原子",
    stageId: "a-nucleus",
  },
];
