"""Inventory every current film; resynthesize every explicit manuscript reading."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
cache=Path('/private/tmp/physics-furigana-resynthesis')
cache.mkdir(exist_ok=True)
rows=[];plan=[]
for file in sorted((root/'public/media').rglob('*.json')):
    if not file.with_suffix('.mp4').exists():continue
    c=json.loads(file.read_text())
    count=sum(u.get('reading') is not None for s in c.get('scenes',[]) for u in s.get('utterances',[]))
    rows.append({'file':str(file.relative_to(root)),'explicitReadings':count,'selected':bool(count)})
    if not count:continue
    for key in ['renderKey','duration','fluencyRepair','fluencyRepairVersion','fluencyVersion','spacingVersion','readingMode']:
        c.pop(key,None)
    for s in c['scenes']:
        for key in ['start','end','captions']:s.pop(key,None)
    plan.append(c)
(cache/'plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2))
out=root/'docs/video-fluency-20260924/resynthesis-inventory.json'
out.write_text(json.dumps({'scope':'Every currently encoded film with an explicit manuscript reading; normal Japanese/word-dictionary-only films have no such formatting spaces. Pending manuscripts are generated by the same spacing policy.','scanned':len(rows),'selected':len(plan),'videos':rows},ensure_ascii=False,indent=2))
print(f'{len(rows)} media inspected; {len(plan)} explicit-furigana videos selected')
