import { calc as c, r } from './schema';
export const fieldCalculations = [
c('混ぜたあとの温度を文字にする|熱平衡の式を最後まで整理',r`失った熱 = 得た熱 :: m_1c_1(T_1-T)=m_2c_2(T-T_2)`,r`両方のかっこを展開 :: m_1c_1T_1-m_1c_1T=m_2c_2T-m_2c_2T_2`,r`T の項を右、残りを左へ :: m_1c_1T_1+m_2c_2T_2=m_1c_1T+m_2c_2T`,r`共通の T をくくる :: m_1c_1T_1+m_2c_2T_2=(m_1c_1+m_2c_2)T`,r`T の係数で割る :: T=\frac{m_1c_1T_1+m_2c_2T_2}{m_1c_1+m_2c_2}`),
c('反比例を式に直す',r`比例定数 k を使う（分子数・温度一定） :: P=\frac{k}{V}`,r`両辺に V :: PV=k`,r`前後で同じ定数 :: P_1V_1=P_2V_2`),
c('2つの変化を順につなぐ|途中の体積を消す',r`温度一定で圧力を変える :: V_*=\frac{P_1V_1}{P_2}`,r`次に圧力一定で温度を変える :: V_2=V_*\frac{T_2}{T_1}`,r`途中の体積を代入 :: V_2=\frac{P_1V_1T_2}{P_2T_1}`,r`両辺に P₂/T₂ を掛ける :: \frac{P_2V_2}{T_2}=\frac{P_1V_1}{T_1}`),
c('衝突1回で壁に渡す運動量',r`壁へ渡す運動量の大きさ :: \Delta p=2m|v_x|`,r`同じ壁へ戻る時間 :: \Delta t=\frac{2L}{|v_x|}`,r`平均力 = 運動量 ÷ 時間 :: \bar F=\frac{2m|v_x|}{2L/|v_x|}`,r`逆数を掛けて約分 :: \bar F=\frac{mv_x^2}{L}`),
c('全分子の衝突から圧力を作る',r`全分子の平均力を面積で割る :: P=\frac{Nm\langle v_x^2\rangle/L}{L^2}`,r`V = L³ を使う :: PV=Nm\langle v_x^2\rangle`,r`3方向が同等 :: \langle v_x^2\rangle=\frac13\langle v^2\rangle`,r`代入 :: PV=\frac13Nm\langle v^2\rangle`),
c('3/2は3方向の運動から現れる',r`分子の並進エネルギーの和 :: U=\frac12Nm\langle v^2\rangle`,r`圧力の式から置き換える :: Nm\langle v^2\rangle=3PV`,r`まず U = 3PV/2 :: U=\frac32PV`,r`状態方程式を代入 :: U=\frac32nRT`),
c('ピストンの仕事を力×距離から',r`外へする微小仕事 :: dW_{\rm out}=F\,dx`,r`F = PA を代入 :: dW_{\rm out}=PA\,dx`,r`体積増加 dV = A dx :: dW_{\rm out}=P\,dV`,r`圧力一定なら足し合わせる :: W_{\rm out}=P(V_2-V_1)`),
c('定積なら、熱がそのまま内部へ',r`第一法則（外からの仕事を正） :: \Delta U=Q+W`,r`体積変化なし、仕事0 :: \Delta U=Q`,r`単原子理想気体の U を使う :: Q=\frac32nR(T_2-T_1)`),
c('1サイクルではUが元へ戻る|効率の式と、100%にならない根拠',r`1周で内部エネルギー変化0 :: 0=Q_h-Q_c-W_{\rm out}`,r`両辺に仕事を足す :: W_{\rm out}=Q_h-Q_c`,r`効率の定義に代入 :: \eta=\frac{W_{\rm out}}{Q_h}=\frac{Q_h-Q_c}{Q_h}`,r`分数を2項に分ける :: \eta=1-\frac{Q_c}{Q_h}`),
c('波の式の中の「−」を読む',r`同じ位相の点を追う :: \frac{x}{\lambda}-\frac{t}{T}=k`,r`両辺に t/T を足す :: \frac{x}{\lambda}=\frac{t}{T}+k`,r`両辺に λ :: x=\frac{\lambda}{T}t+k\lambda`,r`直線の傾きが波速 :: v=\frac{\lambda}{T}=f\lambda`),
c('やまびこを2で割る理由',r`往復距離 :: vt=2L`,r`両辺を2で割る :: L=\frac{vt}{2}`,r`音速340、往復1秒 :: L=\frac{340\times1}{2}=170\,\mathrm m`),
c('定常波の長さから音の高さを導く',r`両端固定では半波長が n 個 :: L=n\frac{\lambda_n}{2}`,r`波長について解く :: \lambda_n=\frac{2L}{n}`,r`v = fλ を使う :: f_n=\frac{v}{\lambda_n}`,r`波長を代入、逆数を掛ける :: f_n=\frac{v}{2L/n}=\frac{nv}{2L}`),
c('前方の波長を引き算で作る|次の山を出すまでに音源も進む',r`1周期の間に進んだ距離の差 :: \lambda_{\rm 前}=VT-v_sT`,r`共通の T をくくる :: \lambda_{\rm 前}=(V-v_s)T`,r`T = 1/f を代入 :: \lambda_{\rm 前}=\frac{V-v_s}{f}`),
c('短い波長を振動数へ直す',r`波速 ÷ 山の間隔 :: f'=\frac{V}{\lambda_{\rm 前}}`,r`前方の波長を代入 :: f'=\frac{V}{(V-v_s)/f}`,r`分数の逆数を掛ける :: f'=V\frac{f}{V-v_s}=f\frac{V}{V-v_s}`),
c('遠ざかる場合は間隔が広がる',r`後方では距離を足す :: \lambda_{\rm 後}=VT+v_sT`,r`T = 1/f を代入 :: \lambda_{\rm 後}=\frac{V+v_s}{f}`,r`振動数に戻す :: f'=\frac V{\lambda_{\rm 後}}=f\frac V{V+v_s}`),
c('聞き手だけが動く場合',r`静止音源の波長 :: \lambda=\frac Vf`,r`山との相対速さを波長で割る :: f'=\frac{V+v_o}{\lambda}`,r`波長を代入 :: f'=\frac{V+v_o}{V/f}=f\frac{V+v_o}{V}`),
c('屈折率を入れてスネルの法則へ|波面の両端の進み方を比べる',r`同じ斜辺をもつ三角形 :: \frac{\sin\theta_1}{\sin\theta_2}=\frac{v_1}{v_2}`,r`v = c/n を代入 :: \frac{\sin\theta_1}{\sin\theta_2}=\frac{c/n_1}{c/n_2}`,r`共通の c を約分 :: \frac{\sin\theta_1}{\sin\theta_2}=\frac{n_2}{n_1}`,r`両辺に n₁ sinθ₂ :: n_1\sin\theta_1=n_2\sin\theta_2`),
c('臨界角を、屈折角90°から求める',r`スネルの法則 :: n_1\sin\theta_c=n_2\sin90^\circ`,r`sin90° = 1 :: n_1\sin\theta_c=n_2`,r`n₁ で割る（n₁ > n₂） :: \sin\theta_c=\frac{n_2}{n_1}`),
c('ヤングの実験の経路差を図形から',r`遠方での経路差 :: \delta\simeq d\sin\theta`,r`中央付近の小さい角度 :: \sin\theta\simeq\tan\theta=\frac yL`,r`代入 :: \delta\simeq\frac{dy}{L}`),
c('縞の間隔を1本ずつ導く',r`明るい位置の条件（近軸近似） :: \frac{dy_m}{L}=m\lambda`,r`L/d を掛ける :: y_m=\frac{m\lambda L}{d}`,r`隣の位置も書く :: y_{m+1}=\frac{(m+1)\lambda L}{d}`,r`引き算して m を相殺 :: \Delta y=\frac{[(m+1)-m]\lambda L}{d}=\frac{\lambda L}{d}`),
c('直列では流量が同じ',r`直列の電圧降下を足す :: V=IR_1+IR_2`,r`同じ電流 I をくくる :: V=I(R_1+R_2)`,r`全体の V = IR と比較 :: R=R_1+R_2`),
c('並列では電圧が同じ',r`分岐電流を足す :: I=\frac V{R_1}+\frac V{R_2}`,r`全体の I = V/R を代入 :: \frac VR=\frac V{R_1}+\frac V{R_2}`,r`共通の V ≠ 0 で割る :: \frac1R=\frac1{R_1}+\frac1{R_2}`),
c('並列抵抗を数で確かめる',r`逆数の和 :: \frac1R=\frac16+\frac13`,r`分母を6にそろえる :: \frac1R=\frac16+\frac26=\frac36`,r`約分して逆数を取る :: \frac1R=\frac12\quad\Rightarrow\quad R=2\,\Omega`),
c('P=VIの途中：電荷を数える',r`t 秒間に通る電荷 :: Q=It`,r`電圧 × 電荷でエネルギー :: E=VQ=VIt`,r`時間で割る :: P=\frac Et=\frac{VI\cancel t}{\cancel t}`,r`電力の式 :: P=VI`),
c('RI²の2乗を省かずに計算',r`電力の定義 :: P=VI`,r`V だけを RI で置き換える :: P=(RI)I`,r`2つの I を掛ける :: P=R\cdot I\cdot I=RI^2`),
c('V²/Rでは、何を一定にしている？',r`電力 :: P=VI`,r`I = V/R を代入 :: P=V\left(\frac VR\right)`,r`分子を掛ける :: P=\frac{V^2}{R}`),
c('送電損失を同じ電力の条件で比べる|送電の電圧と線の電圧降下は別',r`送る電力を固定 :: I=\frac{P_{\rm 送}}{V_{\rm 送}}`,r`線の抵抗による損失へ代入 :: P_{\rm 損}=R_{\rm 線}\left(\frac{P_{\rm 送}}{V_{\rm 送}}\right)^2`,r`送電電圧だけ10倍に :: P'_{\rm 損}=R_{\rm 線}\left(\frac{P_{\rm 送}}{10V_{\rm 送}}\right)^2`,r`2乗なので100分の1 :: P'_{\rm 損}=\frac1{100}P_{\rm 損}`),
c('2倍離すと、なぜ1/4になる？',r`クーロン力の大きさ :: F(r)=\frac{k|q_1q_2|}{r^2}`,r`r を 2r にする :: F(2r)=\frac{k|q_1q_2|}{(2r)^2}`,r`分母の2も2乗 :: F(2r)=\frac{k|q_1q_2|}{4r^2}=\frac14F(r)`),
c('点電荷の電場を導く',r`Q > 0、q > 0 で力の大きさ :: F=\frac{kQq}{r^2}`,r`電場の定義 :: E=\frac Fq`,r`F を代入して q を約分 :: E=\frac{kQ\cancel q}{r^2\cancel q}=\frac{kQ}{r^2}`),
c('一様な電場と電圧の関係を導く',r`電場に沿って d 移動 :: W=qEd`,r`位置エネルギーの減少 :: q\Delta V=-W=-qEd`,r`q ≠ 0 で割る :: \Delta V=-Ed`),
c('平行板の容量を式でも導く|容量の導出でQが消えるところ',r`真空、端の影響を無視（面積 S） :: E=\frac{Q}{\varepsilon_0 S}`,r`電圧の大きさ :: V=Ed=\frac{Qd}{\varepsilon_0 S}`,r`容量の定義に代入 :: C=\frac QV=\frac Q{Qd/(\varepsilon_0 S)}`,r`分母の逆数を掛ける :: C=Q\frac{\varepsilon_0 S}{Qd}`,r`Q を約分（面積 A 表記でも同じ） :: C=\frac{\cancel Q\varepsilon_0 S}{\cancel Qd}=\frac{\varepsilon_0 S}{d}`),
c('縦が電圧、横が電荷の三角形|エネルギーは充電途中の仕事の合計',r`途中の電圧は q/C :: dU=\frac qC\,dq`,r`0 から Q まで積分 :: U=\frac1C\int_0^Q q\,dq`,r`原始関数を上下限で引く :: U=\frac1C\left[\frac{q^2}{2}\right]_0^Q`,r`下端0を引く :: U=\frac{Q^2-0}{2C}=\frac12QV`),
c('CV²とQ²/Cを使い分ける',r`充電の仕事 :: U=\frac12QV`,r`Q = CV を代入する場合 :: U=\frac12(CV)V=\frac12CV^2`,r`V = Q/C を代入する場合 :: U=\frac12Q\left(\frac QC\right)=\frac{Q^2}{2C}`),
c('限界振動数は、残りが0の境目',r`光電効果のエネルギー収支 :: K_{\max}=h\nu-W_0`,r`ぎりぎりの条件 K = 0 :: 0=h\nu_0-W_0`,r`W₀ を両辺に足す :: W_0=h\nu_0`,r`h で割る :: \nu_0=\frac{W_0}{h}`),
c('波長から光子のエネルギーへ',r`真空の波の関係 :: c=\nu\lambda`,r`λ で割る :: \nu=\frac c\lambda`,r`光子の基本関係に代入 :: E=h\nu=h\frac c\lambda=\frac{hc}{\lambda}`),
c('光の色を準位の差から計算',r`光子へ渡る準位差 :: \Delta E=h\nu`,r`ν = c/λ を代入 :: \Delta E=\frac{hc}{\lambda}`,r`両辺に λ を掛ける :: \lambda\Delta E=hc`,r`ΔE > 0 で割る :: \lambda=\frac{hc}{\Delta E}`),
c('波の条件を運動量の条件へ',r`一周で波がつながる条件 :: 2\pi r=n\lambda`,r`物質波 λ = h/(mv) を代入 :: 2\pi r=\frac{nh}{mv}`,r`両辺に mv を掛ける :: 2\pi mvr=nh`,r`2π で割り ℏ と書く :: mvr=n\frac h{2\pi}=n\hbar`),
c('円運動の力と連立する',r`角運動量の条件から速度 :: v=\frac{n\hbar}{mr}`,r`向心力へ代入 :: \frac{ke^2}{r^2}=\frac mr\left(\frac{n\hbar}{mr}\right)^2`,r`2乗して約分 :: \frac{ke^2}{r^2}=\frac{n^2\hbar^2}{mr^3}`,r`両辺に r³、さらに ke² で割る :: r_n=\frac{n^2\hbar^2}{mke^2}`),
c('エネルギーの負号は基準を表す',r`力のつり合いから :: mv^2=\frac{ke^2}{r}`,r`運動エネルギー :: K=\frac12mv^2=\frac{ke^2}{2r}`,r`無限遠を0とする位置エネルギーを足す :: E=\frac{ke^2}{2r}-\frac{ke^2}{r}`,r`分母をそろえて引く :: E=\frac{ke^2-2ke^2}{2r}=-\frac{ke^2}{2r}`),
c('半径を代入して準位を導く',r`エネルギーと軌道半径 :: E_n=-\frac{ke^2}{2r_n}`,r`許された半径を代入 :: E_n=-\frac{ke^2}{2}\frac{mke^2}{n^2\hbar^2}`,r`分子を掛ける :: E_n=-\frac{mk^2e^4}{2\hbar^2n^2}`),
c('半減期を指数関数へ入れる',r`半減期 T の条件 :: e^{-\lambda T}=\frac12`,r`一般の時刻を T の何倍かで書く :: e^{-\lambda t}=\left(e^{-\lambda T}\right)^{t/T}`,r`1/2 を代入 :: N=N_0\left(\frac12\right)^{t/T}`),
c('mc²は相対論の静止エネルギー',r`相対論の出発点 :: E^2=p^2c^2+m^2c^4`,r`静止時 p = 0 :: E^2=m^2c^4`,r`正のエネルギーを選ぶ :: E=mc^2`),
c('核反応で使うのは、質量の差',r`反応前後の静止エネルギーの差 :: \Delta E=m_{\rm 前}c^2-m_{\rm 後}c^2`,r`共通の c² をくくる :: \Delta E=(m_{\rm 前}-m_{\rm 後})c^2`,r`質量差を Δm と書く :: \Delta E=\Delta m c^2`),
];
