import { calc as c, r } from './schema';
export const mathCalculations = [
c('差の分子を先に展開する',r`平均の変化率（h ≠ 0） :: \frac{(t+h)^2-t^2}{h}`,r`かっこを展開 :: \frac{t^2+2th+h^2-t^2}{h}`,r`t² を消し、h をくくる :: \frac{h(2t+h)}{h}`,r`h を約分してから極限へ :: 2t+h\xrightarrow{h\to0}2t`),
c('n乗の微分を、展開の最初の項から',r`正の整数 n の二項展開 :: (t+h)^n=t^n+nt^{n-1}h+O(h^2)`,r`tⁿ を引く :: (t+h)^n-t^n=nt^{n-1}h+O(h^2)`,r`h ≠ 0 で割る :: \frac{(t+h)^n-t^n}{h}=nt^{n-1}+O(h)`,r`h → 0、定数倍 a も残す :: \frac d{dt}(at^n)=ant^{n-1}`),
c('sinの差を加法定理でほどく',r`差の比を作る :: \frac{\sin(t+h)-\sin t}{h}`,r`加法定理で分子を展開 :: \frac{\sin t\cos h+\cos t\sin h-\sin t}{h}`,r`sin t をくくり2項に分ける :: \sin t\frac{\cos h-1}{h}+\cos t\frac{\sin h}{h}`,r`ラジアンで h → 0 :: \sin t\cdot0+\cos t\cdot1=\cos t`),
c('cosの負号も同じ手順',r`差の比 :: \frac{\cos(t+h)-\cos t}{h}`,r`加法定理を代入 :: \frac{\cos t\cos h-\sin t\sin h-\cos t}{h}`,r`2項に分ける :: \cos t\frac{\cos h-1}{h}-\sin t\frac{\sin h}{h}`,r`ラジアンで h → 0 :: \cos t\cdot0-\sin t\cdot1=-\sin t`),
c('不定積分と定積分の違い',r`原始関数は定数 C だけ違ってもよい :: (F(x)+C)'=f(x)`,r`上下限での値を引く :: \int_a^b f(x)dx=[F(x)+C]_a^b`,r`同じ C が消える :: F(b)+\cancel C-F(a)-\cancel C=F(b)-F(a)`),
c('べき乗の積分を微分で検算',r`n ≠ −1 の原始関数候補 :: F(t)=\frac{t^{n+1}}{n+1}`,r`べき乗を微分 :: F'(t)=\frac{(n+1)t^n}{n+1}`,r`係数を約分 :: F'(t)=t^n`,r`n = −1 は別の公式（t ≠ 0） :: \frac d{dt}\ln|t|=\frac1t`),
c('初期位置の定数も忘れない',r`速度を積分 :: x(t)=\int(v_0+at)\,dt`,r`項ごとに積分 :: x(t)=v_0t+\frac12at^2+C`,r`t = 0 の初期条件 :: x_0=0+0+C`,r`C を決める :: x(t)=x_0+v_0t+\frac12at^2`),
c('数値で定積分を完了させる',r`0〜3秒の変位 :: \int_0^3 2t\,dt=[t^2]_0^3`,r`上端から下端を引く :: 3^2-0^2=9\,\mathrm m`,r`2〜3秒なら下端が違う :: \int_2^3 2t\,dt=3^2-2^2=5\,\mathrm m`),
c('合成関数は、計算が2段につながる',r`2段の関数 :: y=u^2,\quad u=3t`,r`それぞれを微分 :: \frac{dy}{du}=2u,\quad\frac{du}{dt}=3`,r`変化の倍率を掛ける :: \frac{dy}{dt}=(2u)\times3`,r`u = 3t を代入 :: \frac{dy}{dt}=2(3t)\times3=18t`),
c('2回目の微分も中身の倍率が要る|sinを代入して、2回微分する',r`位置の候補 :: x=A\sin(\omega t+\phi)`,r`sin の微分 × 中身の微分 :: \dot x=A\cos(\omega t+\phi)\cdot\omega`,r`もう一度、ω を掛ける :: \ddot x=-A\omega\sin(\omega t+\phi)\cdot\omega`,r`元の x でまとめる :: \ddot x=-\omega^2[A\sin(\omega t+\phi)]=-\omega^2x`),
c('積の微分で角の項が消える理由',r`積の変化分 :: \Delta(fg)=(f+\Delta f)(g+\Delta g)-fg`,r`展開して fg を消す :: \Delta(fg)=g\Delta f+f\Delta g+\Delta f\Delta g`,r`時間で割る :: \frac{\Delta(fg)}{\Delta t}=g\frac{\Delta f}{\Delta t}+f\frac{\Delta g}{\Delta t}+\frac{\Delta f}{\Delta t}\Delta g`,r`微分可能なら最後の Δg が0へ :: (fg)'=gf'+fg'`),
c('積の微分をx×xで検算',r`積の微分 :: \frac d{dx}(x\cdot x)=1\cdot x+x\cdot1`,r`2つの増加を足す :: \frac d{dx}(x^2)=x+x=2x`),
c('偏微分の計算を両方向で比べる',r`2変数の関数 :: h(x,y)=x^2y`,r`y を一定にして x で微分 :: \frac{\partial h}{\partial x}=y\frac{d(x^2)}{dx}=2xy`,r`x を一定にして y で微分 :: \frac{\partial h}{\partial y}=x^2\frac{dy}{dy}=x^2`),
c('2次の係数を実際に決める',r`2次までの候補 :: P(x)=a_0+a_1x+a_2x^2`,r`x = 0 で値を合わせる :: a_0=f(0)`,r`1回微分して x = 0 :: P'(0)=a_1=f'(0)`,r`2回微分して x = 0 :: P''(0)=2a_2=f''(0)`,r`両辺を2で割る :: a_2=\frac{f''(0)}2`),
c('階乗は、何度も微分した回数の跡',r`xⁿ を n 回微分 :: \frac{d^n}{dx^n}x^n=n(n-1)\cdots1=n!`,r`係数 aₙ を付けて微分値を合わせる :: n!a_n=f^{(n)}(0)`,r`n! で割る :: a_n=\frac{f^{(n)}(0)}{n!}`),
c('谷底がばねと同じになる条件',r`安定な底 a の近く（U′(a) = 0） :: U(x)\simeq U(a)+\frac12U''(a)(x-a)^2`,r`力は負の微分 :: F=-\frac{dU}{dx}\simeq-\frac12U''(a)\cdot2(x-a)`,r`2 を約分、曲率がばね定数 :: F\simeq-U''(a)(x-a)`),
c('足し算は、行き先を継ぎ足す',r`成分を同じ方向どうしで足す :: (3,-2)+(-1,4)=(3-1,-2+4)`,r`行き先 :: \vec A+\vec B=(2,2)`),
c('3次元の長さは三平方を2回',r`xy 平面への影 :: L_{xy}^2=A_x^2+A_y^2`,r`影と高さでもう一度三平方 :: |\vec A|^2=L_{xy}^2+A_z^2`,r`影を代入 :: |\vec A|^2=A_x^2+A_y^2+A_z^2`,r`長さは正の平方根 :: |\vec A|=\sqrt{A_x^2+A_y^2+A_z^2}`),
c('単位ベクトルを自分で作る',r`元のベクトルの大きさ :: |(3,4)|=\sqrt{3^2+4^2}=5`,r`各成分を大きさで割る :: \hat A=\frac{(3,4)}5=\left(\frac35,\frac45\right)`,r`長さ1か確認 :: |\hat A|=\sqrt{\frac9{25}+\frac{16}{25}}=1`),
c('ベクトルの加速度を成分で計算',r`位置 :: \vec r=(4t,5t-5t^2)`,r`各成分を時間微分 :: \vec v=(4,5-10t)`,r`もう一度各成分を時間微分 :: \vec a=(0,-10)`),
c('成分展開の4項を全部書く',r`2次元の成分表示 :: \vec A\cdot\vec B=(A_x\hat x+A_y\hat y)\cdot(B_x\hat x+B_y\hat y)`,r`同方向の項 :: A_xB_x(\hat x\cdot\hat x)+A_yB_y(\hat y\cdot\hat y)`,r`交差する項 :: A_xB_y(\hat x\cdot\hat y)+A_yB_x(\hat y\cdot\hat x)`,r`同方向は1、垂直は0 :: \vec A\cdot\vec B=A_xB_x+A_yB_y+0+0`),
c('数で内積を計算して意味を読む',r`対応する成分を掛けて足す :: (3,4)\cdot(4,-3)=3\times4+4\times(-3)`,r`2項が相殺 :: 12-12=0`,r`どちらも0ベクトルでないので垂直 :: \cos\theta=\frac{0}{|\vec A||\vec B|}=0`),
c('外積の成分式を展開する',r`x 成分に寄与する2項 :: A_yB_z(\hat y\times\hat z)+A_zB_y(\hat z\times\hat y)`,r`正順は +x、逆順は −x :: (A_yB_z-A_zB_y)\hat x`,r`y 成分も巡回順で作る :: (A_zB_x-A_xB_z)\hat y`,r`z 成分も巡回順で作る :: (A_xB_y-A_yB_x)\hat z`,r`3成分を一つのベクトルに :: \vec A\times\vec B=\begin{pmatrix}A_yB_z-A_zB_y\\A_zB_x-A_xB_z\\A_xB_y-A_yB_x\end{pmatrix}`),
c('トルクを数で確認する',r`位置と力 :: \vec r=(2,0,0),\quad\vec F=(0,3,0)`,r`外積の z 成分 :: N_z=r_xF_y-r_yF_x=2\times3-0\times0`,r`トルク :: \vec N=(0,0,6)\,\mathrm{N\,m}`),
c('変数分離を連鎖律から確かめる',r`v ≠ 0 の区間で連鎖律 :: \frac d{dt}\ln|v|=\frac{v'}v`,r`微分方程式 v′ = −kv :: \frac d{dt}\ln|v|=-k`,r`時間で積分 :: \ln|v|=-kt+C`),
c('対数から指数へ戻す途中',r`積分して得た対数 :: \ln|v|=-kt+C`,r`両辺の指数を取る :: |v|=e^{-kt+C}=e^Ce^{-kt}`,r`符号も含めて定数 A に :: v=Ae^{-kt}`,r`初期値を代入 :: v(0)=A=v_0`,r`初期値の決まった解 :: v=v_0e^{-kt}`),
c('半減期を対数で解く',r`半分になる時刻の条件 :: e^{-\lambda T}=\frac12`,r`両辺の自然対数 :: -\lambda T=\ln\frac12`,r`対数の性質 :: -\lambda T=-\ln2`,r`−λ で割る :: T=\frac{\ln2}{\lambda}`),
c('求めた関数を元の式へ戻す',r`解の候補 :: v=v_0e^{-kt}`,r`連鎖律で微分 :: v'=v_0e^{-kt}(-k)`,r`元の v をくくる :: v'=-k(v_0e^{-kt})=-kv`,r`初期条件も確認 :: v(0)=v_0e^0=v_0`),
c('cosも解なので、2つを足せる',r`2つの解の和 :: x=A\cos\omega t+B\sin\omega t`,r`速度を求める :: v=-A\omega\sin\omega t+B\omega\cos\omega t`,r`t = 0 の2条件 :: x_0=A,\quad v_0=B\omega`,r`係数を代入 :: x=x_0\cos\omega t+\frac{v_0}{\omega}\sin\omega t`),
c('エネルギーが一定か式で確認|sin²とcos²を同じ係数へそろえる',r`x = A cosωt、v = −Aω sinωt :: E=\frac12mA^2\omega^2\sin^2\omega t+\frac12kA^2\cos^2\omega t`,r`mω² = k を代入 :: E=\frac12kA^2\sin^2\omega t+\frac12kA^2\cos^2\omega t`,r`共通係数でくくる :: E=\frac12kA^2(\sin^2\omega t+\cos^2\omega t)`,r`sin² + cos² = 1 :: E=\frac12kA^2`),
];
