import { calc as c, r } from './schema';
export const mechanicsCalculations = [
c('式の両辺に同じ時間を掛ける|等速直線運動と x-t グラフ',r`速度の定義（t > 0） :: v=\frac{x-x_0}{t}`,r`両辺に同じ t を掛ける :: vt=\frac{x-x_0}{\cancel t}\cancel t=x-x_0`,r`両辺に x₀ を足す :: vt+x_0=x-x_0+x_0`,r`左右を入れ替える :: x=x_0+vt`),
c('km/hをm/sへ直す途中計算',r`時間と距離の単位を置き換える :: 72\,\frac{\mathrm{km}}{\mathrm h}=\frac{72\times1000\,\mathrm m}{3600\,\mathrm s}`,r`分子と分母を3600で割る :: \frac{72000}{3600}=20`,r`1秒あたりの距離 :: v=20\,\mathrm{m/s}`),
c('往復の平均を足して2で割れない理由',r`行きの所要時間 :: t_1=\frac{120}{60}=2\,\mathrm h`,r`帰りの所要時間 :: t_2=\frac{120}{40}=3\,\mathrm h`,r`総距離を総時間で割る :: \bar v=\frac{120+120}{2+3}=48\,\mathrm{km/h}`),
c('第1式: 定義を並べ替えるだけ',r`加速度一定 :: a=\frac{v-v_0}{t}`,r`両辺に t を掛ける :: at=v-v_0`,r`両辺に v₀ を足す :: at+v_0=v-v_0+v_0`,r`求める速度を左にする :: v=v_0+at`),
c('第3式の途中：平均速度で面積を書く',r`台形の面積 :: x=\frac{v_0+v}{2}t`,r`両辺を2倍 :: 2x=(v_0+v)t`),
c('第3式の途中：両辺にaを掛ける|第3式: 時間 t を消去する',r`台形の面積を2倍 :: 2x=(v+v_0)t`,r`両辺に a を掛ける :: 2ax=(v+v_0)at`,r`at = v − v₀ を代入 :: 2ax=(v+v_0)(v-v_0)`,r`かっこを展開 :: 2ax=v^2-vv_0+v_0v-v_0^2`,r`交差項を相殺 :: 2ax=v^2-\cancel{vv_0}+\cancel{v_0v}-v_0^2`,r`v² を左側に :: v^2=v_0^2+2ax`),
c('停止距離の符号を確認',r`停止時 v = 0 を代入 :: 0^2-10^2=2(-2)x`,r`左右を計算 :: -100=-4x`,r`両辺を −4 で割る :: x=\frac{-100}{-4}=25\,\mathrm m`),
c('重いほど強く引かれるのになぜ同じ？',r`運動方程式 :: ma=mg`,r`質量 m > 0 で両辺を割る :: a=\frac{\cancel m g}{\cancel m}`,r`同じ重力加速度 :: a=g`),
c('自由落下 = 「初速0、a = g」の等加速度運動',r`初速度0、下向き正 :: v=v_0+at`,r`v₀ = 0、a = g を代入 :: v=0+gt=gt`,r`変位にも同じ値を代入 :: y=0t+\frac12gt^2=\frac12gt^2`),
c('落ちた距離から時間を逆算',r`下向き正の落下距離 :: h=\frac12gt^2`,r`両辺を2倍 :: 2h=gt^2`,r`両辺を g で割る :: \frac{2h}{g}=t^2`,r`時間なので正の平方根 :: t=\sqrt{\frac{2h}{g}}`),
c('最高点までの時間を導く',r`最高点で速度0 :: 0=v_0-gt_{\rm top}`,r`両辺に gt を足す :: gt_{\rm top}=v_0`,r`両辺を g で割る :: t_{\rm top}=\frac{v_0}{g}`),
c('最高点の高さも代入から',r`上向き正の変位 :: y=v_0t-\frac12gt^2`,r`最高点の時刻を代入 :: h=v_0\frac{v_0}{g}-\frac12g\left(\frac{v_0}{g}\right)^2`,r`2乗と約分 :: h=\frac{v_0^2}{g}-\frac{v_0^2}{2g}`,r`分母を 2g にそろえて引く :: h=\frac{2v_0^2-v_0^2}{2g}=\frac{v_0^2}{2g}`),
c('対称になるのは、同じ高さまで戻るとき',r`同じ高さ y = 0 :: 0=v_0t-\frac12gt^2`,r`t をくくる :: 0=t\left(v_0-\frac12gt\right)`,r`出発以外では t > 0 :: v_0-\frac12gt=0`,r`gt = 2v₀ を解く :: t=\frac{2v_0}{g}`),
c('横に力がないと速度が一定になる理由',r`水平成分の運動方程式 :: ma_x=0`,r`m で割る :: a_x=0`,r`鉛直成分（下向き正） :: ma_y=mg`,r`m を約分 :: a_y=g`),
c('水平投射の届く距離',r`鉛直落下で時刻を求める :: t=\sqrt{\frac{2h}{g}}`,r`横方向も同じ時刻 :: x=v_0t`,r`時刻を代入 :: x=v_0\sqrt{\frac{2h}{g}}`),
c('sinとcosは直角三角形の辺の比',r`隣辺 ÷ 斜辺 :: \cos\theta=\frac{v_x}{v_0}`,r`両辺に v₀ を掛ける :: v_x=v_0\cos\theta`,r`対辺 ÷ 斜辺 :: \sin\theta=\frac{v_y}{v_0}`,r`両辺に v₀ を掛ける :: v_y=v_0\sin\theta`),
c('軌道が放物線になる途中計算',r`水平方向の位置 :: x=v_0\cos\theta\,t`,r`v₀ cosθ ≠ 0 として割る :: t=\frac{x}{v_0\cos\theta}`,r`鉛直の式へ t を代入 :: y=v_0\sin\theta\frac{x}{v_0\cos\theta}-\frac g2\left(\frac{x}{v_0\cos\theta}\right)^2`,r`約分し、2乗を展開 :: y=x\tan\theta-\frac{gx^2}{2v_0^2\cos^2\theta}`),
c('同じ高さへ着地するときの飛距離',r`出発以外の y = 0 :: t=\frac{2v_0\sin\theta}{g}`,r`水平方向へ代入 :: R=v_0\cos\theta\frac{2v_0\sin\theta}{g}`,r`倍角公式を使う :: R=\frac{v_0^2}{g}(2\sin\theta\cos\theta)`,r`飛距離 :: R=\frac{v_0^2\sin2\theta}{g}`),
c('机が支える力はどこにある？',r`上向き正、鉛直加速度0 :: N-mg=0`,r`両辺に mg を足す :: N-mg+mg=mg`,r`垂直抗力 :: N=mg`),
c('運動エネルギー ½mv² の出どころ|初めから動いていた場合も導く',r`一定加速度の式 :: v^2-v_0^2=2ax`,r`両辺に m/2 を掛ける :: \frac m2(v^2-v_0^2)=max`,r`ma = F を代入 :: \frac12mv^2-\frac12mv_0^2=Fx`,r`仕事 W とエネルギーの差 :: K-K_0=W`),
c('保存則の途中：増加と減少を足す',r`仕事と運動エネルギー :: \Delta K=W`,r`保存力の仕事 :: W=-\Delta U`,r`W を消去 :: \Delta K=-\Delta U`,r`両辺に ΔU を足す :: \Delta K+\Delta U=0`,r`変化が0なので一定 :: K+U=K_0+U_0`),
c('落下速度をエネルギーから求める',r`静止から高さ h だけ落下 :: mgh=\frac12mv^2`,r`質量を約分 :: gh=\frac12v^2`,r`両辺を2倍 :: 2gh=v^2`,r`速さは正の平方根 :: v=\sqrt{2gh}`),
c('F=maから時間に注目する',r`一定力の運動方程式 :: F=m\frac{v-v_0}{\Delta t}`,r`両辺に Δt を掛ける :: F\Delta t=m(v-v_0)`,r`かっこを展開 :: F\Delta t=mv-mv_0`,r`p = mv の定義を使う :: F\Delta t=\Delta p`),
c('2本の変化の式を足す',r`球1と球2の変化 :: \Delta p_1=F_{12}\Delta t,\quad\Delta p_2=F_{21}\Delta t`,r`辺どうしを足す :: \Delta p_1+\Delta p_2=(F_{12}+F_{21})\Delta t`,r`作用反作用で内力の和が0 :: \Delta(p_1+p_2)=0`),
c('くっつく衝突を最後まで解く',r`運動量保存 :: 2\times3+1\times0=(2+1)u`,r`数字を計算 :: 6=3u`,r`両辺を3で割る :: u=2\,\mathrm{m/s}`),
c('向心加速度の導出：小さな三角形',r`弧の長さ :: v\Delta t=r\Delta\theta`,r`r で割る :: \Delta\theta=\frac{v\Delta t}{r}`,r`小角での速度矢印の差 :: |\Delta\vec v|\simeq v\Delta\theta=\frac{v^2\Delta t}{r}`,r`時間で割り極限へ :: a=\lim_{\Delta t\to0}\frac{|\Delta\vec v|}{\Delta t}=\frac{v^2}{r}`),
c('向心力という新しい力は追加しない',r`中心向きの合力 :: F=ma`,r`向心加速度を代入 :: F=m\frac{v^2}{r}=\frac{mv^2}{r}`),
c('円軌道の速さを求める',r`重力が向心力を担う :: \frac{GMm}{r^2}=\frac{mv^2}{r}`,r`m を約分、両辺に r :: \frac{GM}{r}=v^2`,r`速さは正の平方根 :: v=\sqrt{\frac{GM}{r}}`),
c('周期と半径の関係までつなぐ|円軌道の第3法則を省略せず整理',r`円周 ÷ 速さ :: T=\frac{2\pi r}{v}`,r`両辺を2乗 :: T^2=\frac{4\pi^2r^2}{v^2}`,r`v² = GM/r を代入 :: T^2=\frac{4\pi^2r^2}{GM/r}`,r`逆数を掛ける :: T^2=4\pi^2r^2\frac r{GM}=\frac{4\pi^2r^3}{GM}`),
c('ばねの式を加速度の式へ|ω²という置き換えの意味',r`ばねの力を代入 :: ma=-kx`,r`両辺を m > 0 で割る :: a=-\frac{k}{m}x`,r`正の定数を ω² と名付ける :: \omega^2=\frac{k}{m}`,r`単振動の形 :: a=-\omega^2x`),
c('周期の2πと平方根はどこから？|周期は同じ角度へ戻る時間',r`1周期で角度が2π増える :: \omega T=2\pi`,r`ω で割る :: T=\frac{2\pi}{\omega}`,r`ω の正の平方根を使う :: \omega=\sqrt{\frac{k}{m}}`,r`逆数の平方根 :: T=2\pi\sqrt{\frac{m}{k}}`),
c('振り子の戻す力を取り出す',r`接線方向の重力 :: F=-mg\sin\theta`,r`小さい角度だけで近似 :: F\simeq-mg\theta`,r`弧の変位 x = lθ :: F\simeq-mg\frac{x}{l}=-\frac{mg}{l}x`),
c('振り子の周期は小さい振れの近似|振り子の等時性',r`小角での運動方程式 :: a=-\frac gl x`,r`単振動の係数と比較 :: \omega^2=\frac gl`,r`角振動数の正の平方根 :: \omega=\sqrt{\frac gl}`,r`周期に代入 :: T=\frac{2\pi}{\sqrt{g/l}}=2\pi\sqrt{\frac lg}`),
];
