import { calc as c, r } from './schema';
export const universityCalculations = [
c('ベクトルの式から縦の式を取り出す',r`上向き正の鉛直成分 :: m\ddot y=-mg`,r`m で両辺を割る :: \ddot y=-g`,r`水平成分は力0 :: m\ddot x=0\quad\Rightarrow\quad\ddot x=0`),
c('1回目の積分の上下限を付ける',r`加速度を時間で足す :: \int_0^t\frac{dv}{ds}ds=\int_0^t(-g)ds`,r`左辺は速度の差 :: v(t)-v(0)=-gt`,r`v(0) = v₀ を移す :: v(t)=v_0-gt`),
c('2回目も初期位置を残す',r`速度を積分 :: y(t)-y_0=\int_0^t(v_0-gs)ds`,r`原始関数に直す :: y(t)-y_0=\left[v_0s-\frac12gs^2\right]_0^t`,r`上端から下端を引く :: y(t)-y_0=v_0t-\frac12gt^2`,r`初期位置を足す :: y(t)=y_0+v_0t-\frac12gt^2`),
c('解を2回微分して確かめる',r`求めた位置 :: y=y_0+v_0t-\frac12gt^2`,r`1回微分 :: \dot y=v_0-gt`,r`2回微分 :: \ddot y=-g`,r`初期条件 :: y(0)=y_0,\quad\dot y(0)=v_0`),
c('終端までの差を新しい変数にする',r`終端速度を使ってくくる :: v'=g-\frac km v=\frac km(v_\infty-v)`,r`差 w を定義 :: w=v_\infty-v`,r`定数 v∞ の微分は0 :: w'=-v'`,r`差だけの式になる :: w'=-\frac km w`),
c('差の式を積分する|初速が0でない場合にも広げる',r`差が指数減衰（w = 0 も解） :: \frac{w'}w=-\frac km`,r`積分 :: \ln|w|=-\frac km t+C`,r`初期値 w(0) = v∞ − v₀ :: w=(v_\infty-v_0)e^{-kt/m}`,r`元の速度へ戻す :: v=v_\infty-w=v_\infty+(v_0-v_\infty)e^{-kt/m}`),
c('時間の尺度m/kを単位から読む',r`初速0の解 :: v=\frac{mg}{k}(1-e^{-t/\tau}),\quad\tau=\frac mk`,r`t が τ より十分小さい :: e^{-t/\tau}\simeq1-\frac t\tau`,r`近似を代入 :: v\simeq\frac{mg}{k}\frac t\tau`,r`τ を戻して約分 :: v\simeq\frac{mg}{k}\frac{kt}{m}=gt`),
c('2乗抵抗の終端速度は平方根',r`下向きの運動方程式 :: mv'=mg-cv^2`,r`終端で加速度0 :: 0=mg-cv_\infty^2`,r`両辺を整理 :: v_\infty^2=\frac{mg}{c}`,r`下向きの正の根 :: v_\infty=\sqrt{\frac{mg}{c}}`),
c('曲線の仕事を時刻でパラメータ化',r`経路に沿う仕事 :: W=\int\vec F\cdot d\vec r`,r`微小変位を時間で表す :: d\vec r=\vec v\,dt`,r`代入 :: W=\int\vec F\cdot\vec v\,dt`),
c('速度ベクトルの2乗を微分する',r`積の微分 :: \frac d{dt}(\vec v\cdot\vec v)=\vec a\cdot\vec v+\vec v\cdot\vec a`,r`同じ内積を足す :: \frac d{dt}(v^2)=2\vec v\cdot\vec a`,r`m/2 を掛ける（m 一定） :: \frac d{dt}\left(\frac12mv^2\right)=m\vec a\cdot\vec v`,r`m a = F :: \frac{dK}{dt}=\vec F\cdot\vec v`),
c('時間積分して境界の値を取る',r`仕事率の関係 :: \frac{dK}{dt}=\vec F\cdot\vec v`,r`t₀ から t まで積分 :: \int_{t_0}^t\frac{dK}{ds}ds=\int_{t_0}^t\vec F\cdot\vec v\,ds`,r`左は境界値、右は仕事 :: K(t)-K(t_0)=W`),
c('ばねのUを力の積分から作る',r`位置エネルギーの定義 :: U(x)-U(0)=-\int_0^x F(s)ds`,r`F(s) = −ks :: U(x)-U(0)=\int_0^x ks\,ds`,r`積分して上下限を入れる :: U(x)-U(0)=k\left[\frac{s^2}{2}\right]_0^x`,r`U(0) = 0 と選ぶ :: U(x)=\frac12kx^2`),
c('万有引力のUが負になる途中',r`外向き成分 F = −GMm/r² :: U(r)=-\int_\infty^r\frac{-GMm}{s^2}ds`,r`負号を相殺し積分 :: U(r)=GMm\left[-\frac1s\right]_\infty^r`,r`無限遠では 1/s → 0 :: U(r)=GMm\left(-\frac1r-0\right)=-\frac{GMm}{r}`),
c('保存則を時間微分でも検算',r`合計を時間微分 :: \frac{d(K+U)}{dt}=\frac{dK}{dt}+\frac{dU}{dx}v`,r`dK/dt = Fv を代入 :: \frac{d(K+U)}{dt}=\left(F+\frac{dU}{dx}\right)v`,r`時間に依存しない保存力 F = −U′ :: \frac{d(K+U)}{dt}=\left(-\frac{dU}{dx}+\frac{dU}{dx}\right)v=0`),
c('外力を残した形で足し算する',r`粒子ごとの方程式 :: \vec p_1'=\vec F_{12}+\vec F_{\rm 外1}`,r`もう1つの粒子 :: \vec p_2'=\vec F_{21}+\vec F_{\rm 外2}`,r`足して内力を消す :: (\vec p_1+\vec p_2)'=\cancel{\vec F_{12}}-\cancel{\vec F_{12}}+\vec F_{\rm 外1}+\vec F_{\rm 外2}`,r`外力の和だけが残る :: \vec P'=\vec F_{\rm 外}`),
c('連立方程式を最後まで解く',r`反発係数から後の速度を表す :: v_2'=v_1'+e(v_1-v_2)`,r`運動量保存へ代入 :: m_1v_1+m_2v_2=m_1v_1'+m_2[v_1'+e(v_1-v_2)]`,r`右を展開し v₁′ をくくる :: m_1v_1+m_2v_2=(m_1+m_2)v_1'+em_2v_1-em_2v_2`,r`v₁′ 以外を左へ :: (m_1-em_2)v_1+(1+e)m_2v_2=(m_1+m_2)v_1'`,r`質量の和で割る :: v_1'=\frac{(m_1-em_2)v_1+(1+e)m_2v_2}{m_1+m_2}`),
c('外積を時間微分する途中|残った項がトルクになる',r`角運動量の定義 :: \vec L=\vec r\times\vec p`,r`積の微分 :: \vec L'=\vec r'\times\vec p+\vec r\times\vec p'`,r`r′ = v、p = mv、p′ = F :: \vec L'=m(\vec v\times\vec v)+\vec r\times\vec F`,r`同方向の外積は0 :: \vec L'=0+\vec r\times\vec F=\vec N`),
c('面積速度を小さな三角形から導く',r`微小三角形の面積 :: dA=\frac12r v_\perp dt`,r`時間で割る :: \frac{dA}{dt}=\frac12r v_\perp`,r`L = mr v⊥ を使う :: \frac{dA}{dt}=\frac L{2m}`),
c('小角近似でのみ線形になる',r`接線方向の運動方程式 :: ml\ddot\theta=-mg\sin\theta`,r`m を約分 :: l\ddot\theta=-g\sin\theta`,r`小角なら sinθ ≈ θ :: l\ddot\theta\simeq-g\theta`,r`l で割る :: \ddot\theta\simeq-\frac gl\theta`),
c('周期を測ってgを逆算する',r`小角振り子の周期 :: T=2\pi\sqrt{\frac lg}`,r`両辺を2乗 :: T^2=\frac{4\pi^2l}{g}`,r`g を掛ける :: gT^2=4\pi^2l`,r`T² で割る :: g=\frac{4\pi^2l}{T^2}`),
c('減衰解の指数は変数分離だけでなく代入',r`指数をくくった解を試す :: x=e^{-\gamma t}y`,r`積の微分を1回 :: x'=e^{-\gamma t}(y'-\gamma y)`,r`さらにもう1回 :: x''=e^{-\gamma t}(y''-2\gamma y'+\gamma^2y)`,r`元の方程式へ代入し指数で割る :: my''+(b-2m\gamma)y'+(m\gamma^2-b\gamma+k)y=0`,r`γ = b/(2m) で y′ の項を消す :: y''+\left(\frac km-\gamma^2\right)y=0`,r`係数が正なら振動 :: x=Ae^{-\gamma t}\cos\left(\sqrt{k/m-\gamma^2}\,t+\phi\right)`),
c('共振の式の途中：同じ周波数の解を入れる|共振は入力と損失のつり合い',r`同じ周波数の定常解 :: x=C\cos\Omega t+D\sin\Omega t`,r`1回微分 :: x'=-C\Omega\sin\Omega t+D\Omega\cos\Omega t`,r`2回微分 :: x''=-C\Omega^2\cos\Omega t-D\Omega^2\sin\Omega t`,r`cos の係数を比較 :: (k-m\Omega^2)C+b\Omega D=F_0`,r`sin の係数を比較 :: (k-m\Omega^2)D-b\Omega C=0`),
c('共振の式の途中：位相を消して振幅へ',r`係数を短く書く :: a=k-m\Omega^2,\quad d=b\Omega`,r`2つの係数方程式 :: aC+dD=F_0,\quad aD-dC=0`,r`2乗して足す :: (aC+dD)^2+(aD-dC)^2=F_0^2`,r`交差項が相殺、C² + D² をくくる :: (a^2+d^2)(C^2+D^2)=F_0^2`,r`振幅 A = √(C² + D²) :: A=\frac{F_0}{\sqrt{(k-m\Omega^2)^2+(b\Omega)^2}}`),
c('重心を、トルクのつり合いで求める',r`支点 xG まわりのトルク :: \sum_i m_i g(x_i-x_G)=0`,r`g を消して展開 :: \sum_i m_ix_i-x_G\sum_i m_i=0`,r`xG の項を右へ :: \sum_i m_ix_i=x_G\sum_i m_i`,r`全質量で割る :: x_G=\frac{\sum_i m_ix_i}{\sum_i m_i}`),
c('輪と円板を積分で求める',r`薄い輪の質量 :: dm=\frac{M}{\pi R^2}2\pi r\,dr=\frac{2Mr}{R^2}dr`,r`r² dm を足す :: I=\frac{2M}{R^2}\int_0^R r^3dr`,r`原始関数の上端と下端 :: I=\frac{2M}{R^2}\left[\frac{r^4}{4}\right]_0^R`,r`R² と係数を約分 :: I=\frac{2M}{R^2}\frac{R^4}{4}=\frac12MR^2`),
c('棒の係数1/12を積分する',r`左右対称なので片側の2倍 :: I=\frac{2M}{l}\int_0^{l/2}x^2dx`,r`積分 :: I=\frac{2M}{l}\left[\frac{x^3}{3}\right]_0^{l/2}`,r`l/2 全体を3乗 :: I=\frac{2M}{l}\frac{l^3}{24}`,r`約分 :: I=\frac{Ml^2}{12}`),
c('球を薄い円板に分ける|球の積分を展開して計算する',r`z にある円板の寄与 :: dI=\frac12\rho\pi(R^2-z^2)^2dz`,r`対称性を使い、2乗を展開 :: I=\rho\pi\int_0^R(R^4-2R^2z^2+z^4)dz`,r`項ごとに積分 :: I=\rho\pi\left[R^4z-\frac{2R^2z^3}{3}+\frac{z^5}{5}\right]_0^R`,r`上端を代入 :: I=\rho\pi R^5\left(1-\frac23+\frac15\right)=\frac8{15}\rho\pi R^5`,r`M = 4πρR³/3 を使う :: I=\frac25MR^2`),
c('平行軸の定理の交差項はなぜ消える？',r`ずらした軸からの距離 :: I=\sum_i m_i[(x_i+d)^2+y_i^2]`,r`2乗を展開 :: I=\sum_i m_i(x_i^2+y_i^2)+2d\sum_i m_ix_i+d^2\sum_i m_i`,r`重心原点なので Σmᵢxᵢ = 0 :: I=I_G+0+Md^2`,r`平行軸の定理 :: I=I_G+Md^2`),
c('Iが一定なら角加速度の式になる',r`軸方向の角運動量 :: L=I\omega`,r`I 一定として時間微分 :: L'=I\omega'`,r`L′ = N、ω′ = α :: N=I\alpha`),
c('接地点の速度を足して0にする',r`床に対する接地点の速度 :: v_{\rm 接地}=v-R\omega`,r`滑らない条件 :: 0=v-R\omega`,r`両辺に Rω :: v=R\omega`),
c('坂を下る速さを2種類のエネルギーから',r`並進と回転のエネルギー :: Mgh=\frac12Mv^2+\frac12I\omega^2`,r`滑らない条件 ω = v/R :: Mgh=\frac12Mv^2+\frac12I\frac{v^2}{R^2}`,r`両辺を2倍し v² をくくる :: 2Mgh=\left(M+\frac I{R^2}\right)v^2`,r`M で割って係数をそろえる :: 2gh=\left(1+\frac I{MR^2}\right)v^2`,r`v² の係数で割る :: v^2=\frac{2gh}{1+I/(MR^2)}`),
c('Iが半分なら角速度は2倍',r`外力トルク0で保存 :: I_1\omega_1=I_2\omega_2`,r`I₂ = I₁/2 を代入 :: I_1\omega_1=\frac{I_1}{2}\omega_2`,r`I₁ を消して両辺を2倍 :: \omega_2=2\omega_1`),
c('速く回るぶんのエネルギーはどこから？',r`角速度を L で表す :: \omega=\frac LI`,r`回転エネルギーに代入 :: K=\frac12I\left(\frac LI\right)^2`,r`I を約分 :: K=\frac{L^2}{2I}`),
c('位置の関係を2回微分する',r`車内位置を ξ と書く :: \xi=x-X`,r`速度 :: \dot\xi=\dot x-\dot X`,r`加速度 :: a'=a-A`,r`m を掛け、地上の ma = F を代入 :: ma'=F-mA`),
c('楕円の導出：距離の逆数で書き換える',r`h = r²θ̇、u = 1/r :: \dot\theta=hu^2`,r`連鎖律で半径を微分 :: \dot r=-u^{-2}\frac{du}{d\theta}\dot\theta=-h\frac{du}{d\theta}`,r`もう一度時間微分 :: \ddot r=-h^2u^2\frac{d^2u}{d\theta^2}`,r`半径方向の運動方程式へ代入 :: -h^2u^2u''-h^2u^3=-GMu^2`,r`−h²u² で割る（h ≠ 0） :: u''+u=\frac{GM}{h^2}`),
c('楕円の導出：振動の式を解く',r`定数からのずれを置く :: w=u-\frac{GM}{h^2}`,r`ずれは単振動 :: w''+w=0`,r`角度原点を選んだ解 :: u=\frac{GM}{h^2}+A\cos\theta`,r`A = eGM/h² と名付ける :: u=\frac{GM}{h^2}(1+e\cos\theta)`,r`r = 1/u に戻す :: r=\frac{h^2/GM}{1+e\cos\theta}`),
];
